using System.Globalization;
using System.Security.Cryptography;
using System.Reflection;
using System.Runtime.ExceptionServices;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;
using Game.Simulation.Research.Adaptive;

CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;CultureInfo.CurrentUICulture=CultureInfo.InvariantCulture;
var diagnosticRoot=args.Length>0?args[0]:"<missing>";var diagnosticFixture=args.Length>1?args[1]:"<missing>";
try{
 if(args.Length!=2)throw new ArgumentException("Expected research root and fixture path.");
 var root=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);var options=new JsonSerializerOptions{NumberHandling=JsonNumberHandling.AllowNamedFloatingPointLiterals};
 JsonElement Freeze(object? value)=>JsonSerializer.SerializeToElement(value,options);
 string Fingerprint(string? directory=null){directory??=root;using var hash=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);foreach(var path in Directory.GetFiles(directory,"*.json").OrderBy(Path.GetFileName,StringComparer.Ordinal)){hash.AppendData(Encoding.UTF8.GetBytes(Path.GetFileName(path)));hash.AppendData(File.ReadAllBytes(path));}return Convert.ToHexString(hash.GetHashAndReset());}
 var before=Fingerprint();var authority=AdaptiveResearchAuthority.LoadFromDirectory(root);var pressureCatalog=AdaptiveResearchPressureCatalog.LoadFromDirectory(root,authority.Catalog);var pressure=new AdaptiveResearchPressureRuntime(authority.Kernel,pressureCatalog);var catalog=AdaptiveResearchOutcomeCatalog.LoadFromDirectory(root,authority.Catalog);var runtime=new AdaptiveResearchOutcomeRuntime(authority,catalog,pressure);var after=Fingerprint();if(before!=after)throw new InvalidOperationException("Outcome loading changed canonical inputs.");
 var rows=new List<object>();
 rows.Add(new{Name="catalog-canonical",BeforeFingerprint=before,AfterFingerprint=after,Result=Freeze(new{catalog.Policy,SideDiscoveryCandidatesByNode=catalog.SideDiscoveryCandidatesByNode.Select(pair=>new{NodeId=pair.Key,Candidates=pair.Value}).ToArray()})});
 foreach(var text in new[]{"","abc","The quick brown fox jumps over the lazy dog","abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq","π🚀"})rows.Add(new{Name="sha256-"+Convert.ToHexString(Encoding.UTF8.GetBytes(text)),Input=text,BeforeFingerprint=Fingerprint(),AfterFingerprint=Fingerprint(),Result=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text)))});
 var state=authority.ComposeReferenceProfile("fixture:outcome","reference_humanlike_solar_2050","fixture:context",2050).State;
 var planSeeds=new Dictionary<ResearchOutcomeKind,(string NodeId,string Seed)>();
 foreach(var outcome in Enum.GetValues<ResearchOutcomeKind>()){
  var profile=catalog.Policy.BaseWeights.First(pair=>pair.Value.ContainsKey(outcome)).Key;var node=authority.Catalog.Nodes.Values.First(value=>catalog.GetProfile(value)==profile);PlannedResearchOutcome? planned=null;string? seed=null;
  for(var index=0;index<200000;++index){var candidate="fixture:"+outcome+":"+index;var value=runtime.PlanOutcome(state,node.Id,candidate,"fixture_checkpoint");if(value.Outcome==outcome){planned=value;seed=candidate;break;}}
  if(planned is null)throw new InvalidOperationException($"Could not find deterministic seed for {outcome}.");
  planSeeds[outcome]=(node.Id,seed!);
  rows.Add(new{Name="plan-"+AdaptiveResearchOutcomeCatalog.OutcomeId(outcome),Input=new{node.Id,Seed=seed},BeforeFingerprint=Fingerprint(),AfterFingerprint=Fingerprint(),Result=Freeze(planned)});
 }
 var setNode=typeof(AdaptiveResearchCivilizationState).GetMethod("SetNodeState",BindingFlags.Instance|BindingFlags.NonPublic)??throw new MissingMethodException("SetNodeState");
 var setProject=typeof(AdaptiveResearchCivilizationState).GetMethod("SetProject",BindingFlags.Instance|BindingFlags.NonPublic)??throw new MissingMethodException("SetProject");
 void Invoke(MethodInfo method,object target,object value){try{method.Invoke(target,new[]{value});}catch(TargetInvocationException error)when(error.InnerException is not null){ExceptionDispatchInfo.Capture(error.InnerException).Throw();}}
 void InvokeArgs(MethodInfo method,object target,object?[] values){try{method.Invoke(target,values);}catch(TargetInvocationException error)when(error.InnerException is not null){ExceptionDispatchInfo.Capture(error.InnerException).Throw();}}
 object? InvokeResult(MethodInfo method,object target,object?[] values){try{return method.Invoke(target,values);}catch(TargetInvocationException error)when(error.InnerException is not null){ExceptionDispatchInfo.Capture(error.InnerException).Throw();throw;}}
 object StateProjection(AdaptiveResearchCivilizationState value)=>new{value.Revision,value.MaterializedViewRevision,Nodes=value.NodeStates.Values.ToArray(),Projects=value.ActiveProjects.Values.ToArray(),Pressures=value.Pressures.ToArray(),ExpertiseRevision=value.Expertise.Revision,Fields=value.Expertise.FieldCompetence.Values.ToArray()};
 object OutcomeProjection(AdaptiveResearchOutcomeState value)=>new{value.Revision,value.NextSequence,Summaries=value.Summaries.Values.ToArray(),RecentRecords=value.RecentRecords.ToArray()};
 void AddCall(string name,object? input,Func<object?> call){var callBefore=Fingerprint();object? value=null;Exception? error=null;try{value=call();}catch(Exception caught){error=caught;}var projected=value is null?(JsonElement?)null:Freeze(value);var callAfter=Fingerprint();rows.Add(new{Name=name,Input=Freeze(input),BeforeFingerprint=callBefore,AfterFingerprint=callAfter,Result=projected,Error=error is null?(JsonElement?)null:Freeze(new{Type=error.GetType().Name,error.Message})});}
 var applySeeds=new Dictionary<ResearchOutcomeKind,(string NodeId,string Seed)>();
 foreach(var outcome in Enum.GetValues<ResearchOutcomeKind>()){
  var profile=outcome switch{ResearchOutcomeKind.HypothesisSupported or ResearchOutcomeKind.HypothesisRefined or ResearchOutcomeKind.HypothesisDisproven or ResearchOutcomeKind.AnomalousResult=>ResearchUncertaintyProfile.ScientificHypothesis,ResearchOutcomeKind.HazardIncident=>ResearchUncertaintyProfile.HazardousForeignOrAnomalous,_=>catalog.Policy.BaseWeights.First(pair=>pair.Value.ContainsKey(outcome)&&pair.Key!=ResearchUncertaintyProfile.ScientificHypothesis).Key};
  var node=authority.Catalog.Nodes.Values.First(value=>catalog.GetProfile(value)==profile);var applicationState=authority.ComposeReferenceProfile("fixture:apply:"+outcome,"reference_humanlike_solar_2050","fixture:context",2050).State;var paused=node.IsHypothesis;var pauseReason=paused?"hypothesis_resolution_required":null;
  Invoke(setNode,applicationState,new ResearchNodeRuntimeState(node.Id,ResearchMaturity.Experimental,"fixture",12,25,0));
  Invoke(setProject,applicationState,new ResearchProjectRuntimeState(node.Id,ResearchMaturity.Experimental,null,Math.Max(node.ProjectRequirements.MinimumLabs,1),1,paused,pauseReason,12,25,0));
  string? selectedSeed=null;for(var index=0;index<300000;++index){var candidate="fixture:apply:"+outcome+":"+index;if(runtime.PlanOutcome(applicationState,node.Id,candidate,paused?"experimental_boundary":"fixture_checkpoint").Outcome==outcome){selectedSeed=candidate;break;}}
  if(selectedSeed is null)throw new InvalidOperationException($"Could not find application seed for {outcome}.");var input=Freeze(new{node.Id,Seed=selectedSeed,Outcome=outcome});var callBefore=Fingerprint();ResearchOutcomeApplicationResult? result=null;Exception? error=null;
  applySeeds[outcome]=(node.Id,selectedSeed);
  Func<ResearchOutcomeApplicationResult> call=()=>paused?runtime.ResolvePendingHypothesis(applicationState,node.Id,selectedSeed,2125.5):runtime.ResolveActiveCheckpoint(applicationState,node.Id,selectedSeed,"fixture_checkpoint",2125.5);
  try{result=call();}catch(Exception caught){error=caught;}var projected=result is null?(JsonElement?)null:Freeze(new{Result=result,State=StateProjection(applicationState),OutcomeState=OutcomeProjection(runtime.GetState(applicationState))});var callAfter=Fingerprint();
  rows.Add(new{Name="apply-"+AdaptiveResearchOutcomeCatalog.OutcomeId(outcome),Input=input,BeforeFingerprint=callBefore,AfterFingerprint=callAfter,Result=projected,Error=error is null?(JsonElement?)null:Freeze(new{Type=error.GetType().Name,error.Message})});
 }
 var sidePlan=planSeeds[ResearchOutcomeKind.SideDiscovery];var sideState=authority.ComposeReferenceProfile("fixture:outcome","reference_humanlike_solar_2050","fixture:context",2050).State;var originalSide=runtime.PlanOutcome(sideState,sidePlan.NodeId,sidePlan.Seed,"fixture_checkpoint").PlannedSideDiscoveryNodeId;if(originalSide is null)throw new InvalidOperationException("Side-discovery plan had no candidate.");Invoke(setNode,sideState,new ResearchNodeRuntimeState(originalSide,ResearchMaturity.Hypothesized,"occupied",0,0,0));AddCall("plan-side-discovery-wrap",new{sidePlan.NodeId,sidePlan.Seed,Occupied=originalSide},()=>runtime.PlanOutcome(sideState,sidePlan.NodeId,sidePlan.Seed,"fixture_checkpoint"));

 foreach(var year in new[]{double.NaN,double.PositiveInfinity,double.NegativeInfinity}){var label=double.IsNaN(year)?"NaN":year>0?"PositiveInfinity":"NegativeInfinity";var node=authority.Catalog.GetNode(applySeeds[ResearchOutcomeKind.Progress].NodeId);var yearState=authority.ComposeReferenceProfile("fixture:year:"+label,"reference_humanlike_solar_2050","fixture:context",2050).State;Invoke(setNode,yearState,new ResearchNodeRuntimeState(node.Id,ResearchMaturity.Experimental,"fixture",12,25,0));Invoke(setProject,yearState,new ResearchProjectRuntimeState(node.Id,ResearchMaturity.Experimental,null,Math.Max(node.ProjectRequirements.MinimumLabs,1),1,false,null,12,25,0));string? yearSeed=null;for(var index=0;index<300000;++index){var candidate="fixture:year:"+label+":"+index;if(runtime.PlanOutcome(yearState,node.Id,candidate,"fixture_checkpoint").Outcome==ResearchOutcomeKind.Progress){yearSeed=candidate;break;}}if(yearSeed is null)throw new InvalidOperationException("Could not find nonfinite-year Progress seed.");var yearBefore=Fingerprint();ResearchOutcomeApplicationResult? yearResult=null;Exception? yearError=null;Func<ResearchOutcomeApplicationResult> yearCall=()=>runtime.ResolveActiveCheckpoint(yearState,node.Id,yearSeed,"fixture_checkpoint",year);try{yearResult=yearCall();}catch(Exception caught){yearError=caught;}var yearProjected=yearResult is null?(JsonElement?)null:Freeze(new{Result=yearResult,State=StateProjection(yearState),OutcomeState=OutcomeProjection(runtime.GetState(yearState))});var yearAfter=Fingerprint();rows.Add(new{Name="apply-progress-year-"+label,Input=Freeze(new{node.Id,Seed=yearSeed,Year=year}),BeforeFingerprint=yearBefore,AfterFingerprint=yearAfter,Result=yearProjected,Error=yearError is null?(JsonElement?)null:Freeze(new{Type=yearError.GetType().Name,yearError.Message})});}

 var noPressureRuntime=new AdaptiveResearchOutcomeRuntime(authority,catalog);var anomalousNode=authority.Catalog.GetNode(applySeeds[ResearchOutcomeKind.AnomalousResult].NodeId);var noPressureState=authority.ComposeReferenceProfile("fixture:no-pressure","reference_humanlike_solar_2050","fixture:context",2050).State;Invoke(setNode,noPressureState,new ResearchNodeRuntimeState(anomalousNode.Id,ResearchMaturity.Experimental,"fixture",12,25,0));Invoke(setProject,noPressureState,new ResearchProjectRuntimeState(anomalousNode.Id,ResearchMaturity.Experimental,null,Math.Max(anomalousNode.ProjectRequirements.MinimumLabs,1),1,true,"hypothesis_resolution_required",12,25,0));string? anomalySeed=null;for(var index=0;index<300000;++index){var candidate="fixture:no-pressure:"+index;if(noPressureRuntime.PlanOutcome(noPressureState,anomalousNode.Id,candidate,"experimental_boundary").Outcome==ResearchOutcomeKind.AnomalousResult){anomalySeed=candidate;break;}}if(anomalySeed is null)throw new InvalidOperationException("Could not find no-pressure anomaly seed.");var noPressureBefore=Fingerprint();ResearchOutcomeApplicationResult? noPressureResult=null;Exception? noPressureError=null;Func<ResearchOutcomeApplicationResult> noPressureCall=()=>noPressureRuntime.ResolvePendingHypothesis(noPressureState,anomalousNode.Id,anomalySeed,2130);try{noPressureResult=noPressureCall();}catch(Exception caught){noPressureError=caught;}var noPressureProjected=noPressureResult is null?(JsonElement?)null:Freeze(new{Result=noPressureResult,State=StateProjection(noPressureState),OutcomeState=OutcomeProjection(noPressureRuntime.GetState(noPressureState))});var noPressureAfter=Fingerprint();rows.Add(new{Name="apply-anomalous-without-pressure-runtime",Input=Freeze(new{anomalousNode.Id,Seed=anomalySeed}),BeforeFingerprint=noPressureBefore,AfterFingerprint=noPressureAfter,Result=noPressureProjected,Error=noPressureError is null?(JsonElement?)null:Freeze(new{Type=noPressureError.GetType().Name,noPressureError.Message})});
 AddCall("outcome-id-invalid-enum",new{Outcome=999},()=>AdaptiveResearchOutcomeCatalog.OutcomeId((ResearchOutcomeKind)999));
 var applyMethod=typeof(AdaptiveResearchOutcomeRuntime).GetMethod("ApplyOutcome",BindingFlags.Instance|BindingFlags.NonPublic)??throw new MissingMethodException("ApplyOutcome");var invalidState=authority.ComposeReferenceProfile("fixture:invalid-outcome","reference_humanlike_solar_2050","fixture:context",2050).State;var invalidNode=authority.Catalog.GetNode("prototype_warp_drive");Invoke(setNode,invalidState,new ResearchNodeRuntimeState(invalidNode.Id,ResearchMaturity.Experimental,"fixture",12,25,0));Invoke(setProject,invalidState,new ResearchProjectRuntimeState(invalidNode.Id,ResearchMaturity.Experimental,null,Math.Max(invalidNode.ProjectRequirements.MinimumLabs,1),1,false,null,12,25,0));var invalidProject=invalidState.ActiveProjects[invalidNode.Id];var invalidResolution=new PlannedResearchOutcome(invalidNode.Id,"invalid",0,ResearchUncertaintyProfile.FrontierEngineering,(ResearchOutcomeKind)999,0,null,"invalid");var invalidArgs=new object?[]{invalidState,invalidProject,invalidResolution,2200d};var invalidBefore=Fingerprint();object? invalidResult=null;Exception? invalidError=null;try{invalidResult=InvokeResult(applyMethod,runtime,invalidArgs);}catch(Exception caught){invalidError=caught;}var invalidProjected=invalidResult is null?(JsonElement?)null:Freeze(invalidResult);var invalidAfter=Fingerprint();rows.Add(new{Name="apply-invalid-outcome-enum",Input=Freeze(new{invalidNode.Id,Outcome=999}),BeforeFingerprint=invalidBefore,AfterFingerprint=invalidAfter,Result=invalidProjected,State=Freeze(StateProjection(invalidState)),Error=invalidError is null?(JsonElement?)null:Freeze(new{Type=invalidError.GetType().Name,invalidError.Message})});
 var knownHypothesisId=authority.Catalog.Nodes.Values.First(value=>value.IsHypothesis).Id;
 AddCall("reject-pending-no-project",new{NodeId=knownHypothesisId},()=>runtime.ResolvePendingHypothesis(state,knownHypothesisId,"seed",2100));
 AddCall("reject-active-no-project",new{NodeId="prototype_warp_drive"},()=>runtime.ResolveActiveCheckpoint(state,"prototype_warp_drive","seed","checkpoint",2100));
 foreach(var whitespace in new[]{""," ","\t","\u000B","\u000C","\u00A0","\u2000","\u3000"})AddCall("plan-blank-seed-"+Convert.ToHexString(Encoding.UTF8.GetBytes(whitespace)),new{Seed=whitespace},()=>runtime.PlanOutcome(state,authority.Catalog.Nodes.Keys.First(),whitespace,"checkpoint"));
 foreach(var whitespace in new[]{""," ","\u00A0","\u3000"})AddCall("plan-blank-checkpoint-"+Convert.ToHexString(Encoding.UTF8.GetBytes(whitespace)),new{Checkpoint=whitespace},()=>runtime.PlanOutcome(state,authority.Catalog.Nodes.Keys.First(),"seed",whitespace));
 AddCall("plan-unknown-node",new{NodeId="unknown_node"},()=>runtime.PlanOutcome(state,"unknown_node","seed","checkpoint"));

 var historyState=new AdaptiveResearchOutcomeState();
 var recordMethod=typeof(AdaptiveResearchOutcomeState).GetMethod("Record",BindingFlags.Instance|BindingFlags.NonPublic)??throw new MissingMethodException("Record");
 void RecordOn(AdaptiveResearchOutcomeState target,string node,int attempt,int maxRecent,int maxPerNode){InvokeArgs(recordMethod,target,new object?[]{node,"checkpoint",attempt,ResearchOutcomeKind.Progress,null,2100.25,"history",maxRecent,maxPerNode});}
 void Record(string node,int attempt,int maxRecent,int maxPerNode)=>RecordOn(historyState,node,attempt,maxRecent,maxPerNode);
 var historyBefore=Fingerprint();Record("node-a",0,2,1);Record("node-b",0,2,1);Record("node-a",1,2,1);var historyResult=Freeze(OutcomeProjection(historyState));var historyAfter=Fingerprint();rows.Add(new{Name="state-bounded-history",BeforeFingerprint=historyBefore,AfterFingerprint=historyAfter,Result=historyResult});
 var capZeroState=new AdaptiveResearchOutcomeState();var capZeroBefore=Fingerprint();RecordOn(capZeroState,"node-a",0,10,10);RecordOn(capZeroState,"node-b",0,10,10);RecordOn(capZeroState,"node-a",1,10,0);var capZeroResult=Freeze(OutcomeProjection(capZeroState));var capZeroAfter=Fingerprint();rows.Add(new{Name="state-interleaved-per-node-zero",BeforeFingerprint=capZeroBefore,AfterFingerprint=capZeroAfter,Result=capZeroResult});
 var negativePerNodeState=new AdaptiveResearchOutcomeState();var negativePerNodeBefore=Fingerprint();RecordOn(negativePerNodeState,"node-a",0,10,-1);var negativePerNodeResult=Freeze(OutcomeProjection(negativePerNodeState));var negativePerNodeAfter=Fingerprint();rows.Add(new{Name="state-negative-per-node",BeforeFingerprint=negativePerNodeBefore,AfterFingerprint=negativePerNodeAfter,Result=negativePerNodeResult});
 var negativeRecentState=new AdaptiveResearchOutcomeState();var negativeRecentArgs=new object?[]{"node-a","checkpoint",0,ResearchOutcomeKind.Progress,null,2100.25,"history",-1,1};var negativeRecentBefore=Fingerprint();Exception? negativeRecentError=null;try{InvokeArgs(recordMethod,negativeRecentState,negativeRecentArgs);}catch(Exception caught){negativeRecentError=caught;}var negativeRecentResult=Freeze(OutcomeProjection(negativeRecentState));var negativeRecentAfter=Fingerprint();rows.Add(new{Name="state-negative-recent-partial",BeforeFingerprint=negativeRecentBefore,AfterFingerprint=negativeRecentAfter,Result=negativeRecentResult,Error=negativeRecentError is null?(JsonElement?)null:Freeze(new{Type=negativeRecentError.GetType().Name,negativeRecentError.Message})});
 string ChangeJson(string text,Action<JsonObject> change){var value=JsonNode.Parse(text)?.AsObject()??throw new InvalidDataException("Expected object fixture.");change(value);return value.ToJsonString();}
 var malformed=new(string Name,string File,Func<string,string?> Change)[]{
  ("load-missing-policy","research_outcome_runtime_policy.json",_=>null),
  ("load-malformed-policy","research_outcome_runtime_policy.json",_=>"{"),
  ("load-policy-catalog-mismatch","research_outcome_runtime_policy.json",text=>text.Replace(authority.Catalog.Metadata.CatalogId,"wrong.catalog",StringComparison.Ordinal)),
  ("load-unknown-profile","research_outcome_runtime_policy.json",text=>text.Replace("\"scientific_hypothesis\": {","\"unknown_profile\": {",StringComparison.Ordinal)),
  ("load-unknown-outcome","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"unknown_outcome\": 60",StringComparison.Ordinal)),
  ("load-zero-weight","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": 0",StringComparison.Ordinal)),
  ("load-gain-wrong-length","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": [0.4, 0.8, 0.4]","\"progress\": [0.4, 0.8]",StringComparison.Ordinal)),
  ("load-unknown-assignment-node","research_outcome_runtime_policy.json",text=>text.Replace("\"prototype_warp_drive\"","\"unknown_node\"",StringComparison.Ordinal)),
  ("load-fraction-over-one","research_outcome_runtime_policy.json",text=>text.Replace("\"setback_stage_progress_loss_fraction\": 0.18","\"setback_stage_progress_loss_fraction\": 1.5",StringComparison.Ordinal)),
  ("load-normal-outcomes-null","maturation_model.json",text=>ChangeJson(text,value=>value["uncertainty_profiles"]!["scientific_hypothesis"]!["normal_outcomes"]=null)),
  ("load-normal-outcomes-scalar","maturation_model.json",text=>ChangeJson(text,value=>value["uncertainty_profiles"]!["scientific_hypothesis"]!["normal_outcomes"]="progress")),
  ("load-normal-outcome-null-item","maturation_model.json",text=>ChangeJson(text,value=>value["uncertainty_profiles"]!["scientific_hypothesis"]!["normal_outcomes"]![0]=null)),
  ("load-profiles-array","maturation_model.json",text=>ChangeJson(text,value=>value["uncertainty_profiles"]=new JsonArray())),
  ("load-weights-array","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["public_seed_weights"]=new JsonArray())),
  ("load-profile-weights-null","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["public_seed_weights"]!["scientific_hypothesis"]=null)),
  ("load-competence-gains-array","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["effects"]!["outcome_competence_gain"]=new JsonArray())),
  ("load-competence-gain-object","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["effects"]!["outcome_competence_gain"]!["progress"]=new JsonObject())),
  ("load-frontier-scalar","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["profile_assignment"]!["frontier_engineering_node_ids"]="prototype_warp_drive")),
  ("load-alternative-sets-object","index.json",text=>ChangeJson(text,value=>value["alternative_solution_sets"]=new JsonObject())),
  ("load-null-catalog-id","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["catalog_id"]=null)),
  ("load-nonstring-catalog-id","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["catalog_id"]=1)),
  ("load-overflow-weight","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": 1e400",StringComparison.Ordinal)),
  ("load-duplicate-weight","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": 60, \"progress\": 61",StringComparison.Ordinal)),
  ("load-duplicate-competence-gain","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": [0.4, 0.8, 0.4]","\"progress\": [0.4, 0.8, 0.4], \"progress\": [0.1, 0.1, 0.1]",StringComparison.Ordinal)),
  ("load-duplicate-scalar-last-wins","research_outcome_runtime_policy.json",text=>text.Replace("\"catalog_id\": \""+authority.Catalog.Metadata.CatalogId+"\"","\"catalog_id\": \"wrong.catalog\", \"catalog_id\": \""+authority.Catalog.Metadata.CatalogId+"\"",StringComparison.Ordinal)),
  ("load-weight-negative-1e6","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": -1e6",StringComparison.Ordinal)),
  ("load-weight-negative-1e16","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": -1e16",StringComparison.Ordinal)),
  ("load-weight-negative-1e17","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": -1e17",StringComparison.Ordinal)),
  ("load-weight-negative-1e-4","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": -1e-4",StringComparison.Ordinal)),
  ("load-weight-negative-1e-5","research_outcome_runtime_policy.json",text=>text.Replace("\"progress\": 60","\"progress\": -1e-5",StringComparison.Ordinal)),
  ("load-history-int32-overflow","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["history"]!["max_recent_outcome_records"]=2147483648L)),
  ("load-history-floating","research_outcome_runtime_policy.json",text=>ChangeJson(text,value=>value["history"]!["max_recent_outcome_records"]=1.5)),
 };
 var relevant=new[]{"research_outcome_runtime_policy.json","maturation_model.json","index.json"};var scratchParent=Path.Combine(Path.GetTempPath(),"stellar-outcome-058-owned");Directory.CreateDirectory(scratchParent);
 foreach(var test in malformed){var scratch=Path.GetFullPath(Path.Combine(scratchParent,Guid.NewGuid().ToString("N")));if(!scratch.StartsWith(Path.GetFullPath(scratchParent).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)||Directory.Exists(scratch))throw new InvalidOperationException("Refused unsafe Outcome scratch path.");Directory.CreateDirectory(scratch);try{foreach(var file in relevant)File.Copy(Path.Combine(root,file),Path.Combine(scratch,file));var path=Path.Combine(scratch,test.File);var content=test.Change(File.ReadAllText(path));if(content is null)File.Delete(path);else File.WriteAllText(path,content,new UTF8Encoding(false));var changed=relevant.Where(file=>!File.Exists(Path.Combine(scratch,file))||!File.ReadAllBytes(Path.Combine(root,file)).SequenceEqual(File.ReadAllBytes(Path.Combine(scratch,file)))).Select(file=>new{RelativePath=file,Deleted=!File.Exists(Path.Combine(scratch,file)),ContentBase64=File.Exists(Path.Combine(scratch,file))?Convert.ToBase64String(File.ReadAllBytes(Path.Combine(scratch,file))):null}).ToArray();var loadBefore=Fingerprint(scratch);var loaded=false;Exception? error=null;Func<AdaptiveResearchOutcomeCatalog> call=()=>AdaptiveResearchOutcomeCatalog.LoadFromDirectory(scratch,authority.Catalog);try{_ = call();loaded=true;}catch(Exception caught){error=caught;}var projected=error is null?Freeze(new{Loaded=loaded}):(JsonElement?)null;var loadAfter=Fingerprint(scratch);rows.Add(new{Name=test.Name,Phase="Load",ChangedFiles=changed,BeforeFingerprint=loadBefore,AfterFingerprint=loadAfter,Result=projected,Error=error is null?(JsonElement?)null:Freeze(new{Type=error.GetType().Name,error.Message})});}finally{var resolved=Path.GetFullPath(scratch);if(Directory.Exists(resolved)&&string.Equals(Path.GetDirectoryName(resolved),Path.GetFullPath(scratchParent),StringComparison.OrdinalIgnoreCase))Directory.Delete(resolved,true);}}
 var fixture=new{Generator="actual C# AdaptiveResearchOutcomes",CanonicalFingerprint=before,Rows=rows};Directory.CreateDirectory(Path.GetDirectoryName(output)!);File.WriteAllText(output,JsonSerializer.Serialize(fixture,options)+"\n");Console.WriteLine($"generated {rows.Count} actual-source rows");Console.WriteLine($"canonical fingerprint {before}");return 0;
}catch(Exception error){Console.Error.WriteLine(error.ToString());Console.Error.WriteLine($"cwd={Directory.GetCurrentDirectory()}");Console.Error.WriteLine($"research-root={diagnosticRoot}");Console.Error.WriteLine($"fixture={diagnosticFixture}");return 1;}
