using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Game.Simulation.Construction;
using Game.Simulation.Economy;
using Game.Simulation.Generation;
using Game.Simulation.Models;
using Game.Simulation.Research;
using Game.Simulation.Shipbuilding;
using Game.Simulation.Species;

try {
    CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;
    if(args.Length!=1) throw new ArgumentException("Expected output fixture path");
    var options=new JsonSerializerOptions {NumberHandling=JsonNumberHandling.AllowNamedFloatingPointLiterals};
    object[] Compact(PlanetaryBodyState b)=>new object[]{b.Id,b.SystemId,b.ParentBodyId!,b.OrbitIndex,b.Name,(int)b.Kind,b.RadiusEarth,b.MassEarth,b.Environment.GravityG,b.Environment.TemperatureKelvin,b.Environment.PressureKPa,(int)b.Environment.Atmosphere,(int)b.Environment.AvailableSolvent,b.Environment.RadiationHazard,b.Environment.IsImmersedEnvironment,b.Environment.HasSolidSurface,b.LegacyColonizationCandidate,b.HasRareResource,b.HasAnomaly,b.HasPreWarpCivilization,b.OrbitalEccentricity,b.OrbitalInclinationDegrees};
    PlanetaryBodyState Body(JsonElement row) { var a=row.EnumerateArray().ToArray(); return new(a[0].GetInt32(),a[1].GetInt32(),a[2].ValueKind==JsonValueKind.Null?null:a[2].GetInt32(),a[3].GetInt32(),a[4].GetString()!,(PlanetaryBodyKind)a[5].GetInt32(),a[6].GetDouble(),a[7].GetDouble(),new(a[8].GetDouble(),a[9].GetDouble(),a[10].GetDouble(),(PlanetaryAtmosphereRegime)a[11].GetInt32(),(PlanetarySolventRegime)a[12].GetInt32(),a[13].GetDouble(),a[14].GetBoolean(),a[15].GetBoolean()),a[16].GetBoolean(),a[17].GetBoolean(),a[18].GetBoolean(),a[19].GetBoolean(),a[20].GetDouble(),a[21].GetDouble()); }
    SurfaceColonyOutput Surface(double f,double w,double h)=>new(0,0,0,0,0,0,new HashSet<int>(),0,f,w,h,0,0,new HashSet<int>(),0,0,0,0,0);
    var civilizationFixture=Path.Combine(Directory.GetCurrentDirectory(),"native-tests","fixtures","civilization-catalog.json");
    using var source=JsonDocument.Parse(File.ReadAllText(civilizationFixture));
    var founding=source.RootElement.GetProperty("Cases").EnumerateArray().First(c=>c.GetProperty("Kind").GetString()=="Founding");
    var civilizations=JsonSerializer.Deserialize<CivilizationState[]>(founding.GetProperty("ExpectedCivilizations").GetRawText(),options)!;
    var bodies=founding.GetProperty("ExpectedBodies").EnumerateArray().Select(Body).ToArray();
    var cases=new List<object>(); var seeder=new ColonySeeder();
    object Seed(string name,IList<CivilizationState> civs,IReadOnlyList<PlanetaryBodyState>? sourceBodies) { try { var colonies=sourceBodies is null?seeder.Seed(civs):seeder.Seed(civs,sourceBodies); return new {Name=name,Kind="Seed",Civilizations=civs,Bodies=sourceBodies?.Select(Compact),Legacy=sourceBodies is null,ExpectedColonies=colonies,ExpectedEconomies=seeder.SeedEconomies(civs)}; } catch(Exception x) { return new {Name=name,Kind="Seed",Civilizations=civs,Bodies=sourceBodies?.Select(Compact),Legacy=sourceBodies is null,ExpectedError=x.Message}; } }
    cases.Add(Seed("seed-canonical-founding",civilizations,bodies));
    cases.Add(Seed("seed-legacy-reversed",civilizations.Reverse().ToArray(),null));
    cases.Add(Seed("seed-sparse-identities",new[]{civilizations[0] with {Id=41},civilizations[^1] with {Id=900}},bodies));
    cases.Add(Seed("seed-missing-luna",civilizations,bodies.Where(b=>b.Id!=SolCatalogPreset.MoonBodyId).ToArray()));
    cases.Add(Seed("seed-missing-mars",civilizations,bodies.Where(b=>b.Id!=4).ToArray()));
    foreach(var extra in source.RootElement.GetProperty("Cases").EnumerateArray().Where(c=>c.GetProperty("Kind").GetString()=="Founding").Skip(1)) {
        var civs=JsonSerializer.Deserialize<CivilizationState[]>(extra.GetProperty("ExpectedCivilizations").GetRawText(),options)!;
        var worlds=extra.GetProperty("ExpectedBodies").EnumerateArray().Select(Body).ToArray();
        cases.Add(Seed("seed-"+extra.GetProperty("Name").GetString(),civs,worlds));
    }
    GalaxyState Galaxy(IReadOnlyList<PlanetaryBodyState> catalog)=>new(){Seed=0,Systems=Array.Empty<StarSystemState>(),PlanetaryBodies=catalog,Civilizations=new List<CivilizationState>(),Fleets=new List<FleetState>(),Colonies=new List<ColonyState>(),Economies=Array.Empty<CivilizationEconomyState>(),Technologies=new List<TechnologyState>(),ConstructionStates=new List<ConstructionState>(),ShipyardStates=new List<ShipyardState>(),PlayerCivilizationId=0,Knowledge=new Game.Simulation.Knowledge.CivilizationKnowledgeState()};
    ColonyState Colony(string species,double population=1000,double infrastructure=1,int? body=null,int system=7)=>new(){Id=31,CivilizationId=4,SystemId=system,PlanetaryBodyId=body,Name="Test",PopulationSpeciesId=species,PopulationMillions=population,Infrastructure=infrastructure,StoredFoodPopulationDaysMillions=0,StoredWaterPopulationDaysMillions=0};
    foreach(var (population,infrastructure,automation,jobs) in new[]{(-2d,.01,false,-3d),(0d,1d,false,0d),(100d,10d,false,0d),(100d,1d,true,40d),(100d,1d,false,1000d)}) { var colony=Colony(SpeciesCatalog.TerranBaselineId,population,infrastructure); cases.Add(new {Name=$"labor-{cases.Count}",Kind="Labor",Colony=colony,Automation=automation,AdditionalJobs=jobs,Expected=ColonyLaborEconomy.GetSnapshot(colony,automation,jobs)}); }
    PlanetaryBodyState Ideal(int id,string species) { var profile=SpeciesCatalog.Get(species); PlanetaryAtmosphereRegime a=profile.Environment.PreferredAtmosphere switch {AtmosphereClass.OxygenNitrogen=>PlanetaryAtmosphereRegime.OxygenNitrogen,AtmosphereClass.OxygenRich=>PlanetaryAtmosphereRegime.OxygenRich,AtmosphereClass.Reducing=>PlanetaryAtmosphereRegime.Reducing,_=>PlanetaryAtmosphereRegime.Other}; PlanetarySolventRegime s=profile.Environment.BiologicalSolvent switch {SolventClass.Water=>PlanetarySolventRegime.Water,SolventClass.Hydrocarbon=>PlanetarySolventRegime.Hydrocarbon,_=>PlanetarySolventRegime.Other}; return new(id,7,null,0,"Ideal",PlanetaryBodyKind.Planet,1,1,new(profile.Environment.GravityG.Preferred,profile.Environment.TemperatureKelvin.Preferred,profile.Environment.PressureKPa.Preferred,a,s,.01,profile.Environment.RequiresImmersion,true),false,false,false,false); }
    foreach(var species in SpeciesCatalog.All.Select(x=>x.Id)) { var body=Ideal(700+cases.Count,species); var colony=Colony(species,1000,1,body.Id); var surface=Surface(10,20,30); cases.Add(new {Name=$"capacity-{species}",Kind="Capacity",Colony=colony,Bodies=new[]{Compact(body)},Surface=new {FoodCapacityMillions=10d,WaterCapacityMillions=20d,HousingCapacityMillions=30d},Expected=ColonySustenanceCapacity.GetSnapshot(Galaxy(new List<PlanetaryBodyState>{body}),colony,surface)}); }
    var fallback=Colony(SpeciesCatalog.TerranBaselineId,900,1,999); cases.Add(new {Name="capacity-missing-body",Kind="Capacity",Colony=fallback,Bodies=Array.Empty<object[]>(),Surface=new {FoodCapacityMillions=0d,WaterCapacityMillions=0d,HousingCapacityMillions=0d},Expected=ColonySustenanceCapacity.GetSnapshot(Galaxy(Array.Empty<PlanetaryBodyState>()),fallback,Surface(0,0,0))});
    var wrongSystem=Ideal(999,SpeciesCatalog.TerranBaselineId) with {SystemId=8}; cases.Add(new {Name="capacity-wrong-system-body",Kind="Capacity",Colony=fallback,Bodies=new[]{Compact(wrongSystem)},Surface=new {FoodCapacityMillions=0d,WaterCapacityMillions=0d,HousingCapacityMillions=0d},Expected=ColonySustenanceCapacity.GetSnapshot(Galaxy(new[]{wrongSystem}),fallback,Surface(0,0,0))});
    foreach(var (name,radius,infrastructure,solvent) in new[]{("capacity-radius-low",.001d,.01d,PlanetarySolventRegime.Water),("capacity-radius-high",99d,9d,PlanetarySolventRegime.Water),("capacity-solvent-mismatch",1d,1d,PlanetarySolventRegime.None)}) { var body=Ideal(1100+cases.Count,SpeciesCatalog.TerranBaselineId) with {RadiusEarth=radius,Environment=Ideal(1100+cases.Count,SpeciesCatalog.TerranBaselineId).Environment with {AvailableSolvent=solvent}}; var colony=Colony(SpeciesCatalog.TerranBaselineId,1000,infrastructure,body.Id); cases.Add(new {Name=name,Kind="Capacity",Colony=colony,Bodies=new[]{Compact(body)},Surface=new {FoodCapacityMillions=0d,WaterCapacityMillions=0d,HousingCapacityMillions=0d},Expected=ColonySustenanceCapacity.GetSnapshot(Galaxy(new[]{body}),colony,Surface(0,0,0))}); }
    var reserveCapacity=new ColonySustenanceCapacitySnapshot(0,0,0,0,0,0,200,100,50,50,.5,"housing");
    foreach(var (food,water,days) in new[]{(0d,0d,5d),(10000d,10000d,10d),(20d,20d,0d),(999999d,999999d,1d),(-1d,-1d,2d),(30d,700d,-2d),(500d,0d,30d),(0d,0d,.001d)}) { var colony=Colony(SpeciesCatalog.TerranBaselineId,100,1); colony.StoredFoodPopulationDaysMillions=food; colony.StoredWaterPopulationDaysMillions=water; var before=(colony.StoredFoodPopulationDaysMillions,colony.StoredWaterPopulationDaysMillions); var preview=ColonySustenanceReserves.Preview(colony,reserveCapacity,days); if(before!=(colony.StoredFoodPopulationDaysMillions,colony.StoredWaterPopulationDaysMillions)) throw new InvalidOperationException("Reserve preview mutated colony state."); var advance=ColonySustenanceReserves.Advance(colony,reserveCapacity,days); cases.Add(new {Name=$"reserves-{cases.Count}",Kind="Reserves",Colony=new ColonyState {Id=31,CivilizationId=4,SystemId=7,Name="Test",PopulationSpeciesId=SpeciesCatalog.TerranBaselineId,PopulationMillions=100,Infrastructure=1,StoredFoodPopulationDaysMillions=food,StoredWaterPopulationDaysMillions=water},Capacity=reserveCapacity,Days=days,ExpectedPreview=preview,ExpectedAdvance=advance,ExpectedColony=colony}); }
    var deficitCapacity=new ColonySustenanceCapacitySnapshot(0,0,0,0,0,0,40,60,150,40,.4,"food");
    var decorated=Colony(SpeciesCatalog.TerranBaselineId,100,1); decorated.StoredFoodPopulationDaysMillions=20; decorated.StoredWaterPopulationDaysMillions=30; decorated.StoredExtractedMaterials=44; decorated.RemainingExtractableMaterials=55; decorated.SurfaceHubLevel=3; decorated.SurfaceHubUpgradeDaysRemaining=6; decorated.SurfaceBuildings.Add(new SurfaceBuildingState {Id=77,TypeId="hydroponics",X=1.5f,Z=-2.5f,RotationDegrees=18,IndustryProgress=.6,IsComplete=true,IsEnabled=false,PendingUpgradeTypeId="advanced_hydroponics",UpgradeDaysRemaining=4,OperatingPriority=8,Condition=.7,StoredPowerDays=9}); var decoratedPreview=ColonySustenanceReserves.Preview(decorated,deficitCapacity,1); var decoratedAdvance=ColonySustenanceReserves.Advance(decorated,deficitCapacity,1); cases.Add(new {Name="reserves-preserves-colony-data",Kind="Reserves",Colony=new ColonyState {Id=31,CivilizationId=4,SystemId=7,Name="Test",PopulationSpeciesId=SpeciesCatalog.TerranBaselineId,PopulationMillions=100,Infrastructure=1,StoredFoodPopulationDaysMillions=20,StoredWaterPopulationDaysMillions=30,StoredExtractedMaterials=44,RemainingExtractableMaterials=55,SurfaceHubLevel=3,SurfaceHubUpgradeDaysRemaining=6,SurfaceBuildings={new SurfaceBuildingState {Id=77,TypeId="hydroponics",X=1.5f,Z=-2.5f,RotationDegrees=18,IndustryProgress=.6,IsComplete=true,IsEnabled=false,PendingUpgradeTypeId="advanced_hydroponics",UpgradeDaysRemaining=4,OperatingPriority=8,Condition=.7,StoredPowerDays=9}}},Capacity=deficitCapacity,Days=1d,ExpectedPreview=decoratedPreview,ExpectedAdvance=decoratedAdvance,ExpectedColony=decorated});
    foreach(var (food,water,days) in new[]{(0d,0d,1d),(600d,400d,5d),(100d,50d,20d)}) { var colony=Colony(SpeciesCatalog.TerranBaselineId,100,1); colony.StoredFoodPopulationDaysMillions=food; colony.StoredWaterPopulationDaysMillions=water; var before=(food,water); var preview=ColonySustenanceReserves.Preview(colony,deficitCapacity,days); if((colony.StoredFoodPopulationDaysMillions,colony.StoredWaterPopulationDaysMillions)!=before) throw new InvalidOperationException("Deficit reserve preview mutated colony state."); var advance=ColonySustenanceReserves.Advance(colony,deficitCapacity,days); if(before.food>0 && colony.StoredFoodPopulationDaysMillions>=before.food) throw new InvalidOperationException("Deficit fixture did not withdraw food."); if(days==20 && (colony.StoredFoodPopulationDaysMillions!=0 || advance.EffectiveSupportRatio>=1)) throw new InvalidOperationException("Deficit fixture did not exhaust reserves."); cases.Add(new {Name=$"reserves-deficit-{days}",Kind="Reserves",Colony=new ColonyState {Id=31,CivilizationId=4,SystemId=7,Name="Test",PopulationSpeciesId=SpeciesCatalog.TerranBaselineId,PopulationMillions=100,Infrastructure=1,StoredFoodPopulationDaysMillions=food,StoredWaterPopulationDaysMillions=water},Capacity=deficitCapacity,Days=days,ExpectedPreview=preview,ExpectedAdvance=advance,ExpectedColony=colony}); }
    foreach(var (balance,net,arrears) in new[]{(10d,1d,0d),(10d,-2d,0d),(0.000001d,-1d,0d),(10d,-1d,.000001d),(10d,-1d,.0000011d),(double.PositiveInfinity,0d,0d),(1d,double.NaN,0d),(-1d,0d,0d),(1d,0d,-1d),(1d,0d,double.NaN)}) try { cases.Add(new {Name=$"treasury-{cases.Count}",Kind="Treasury",Balance=balance,NetPerDay=net,Arrears=arrears,Expected=TreasuryHealth.Assess(balance,net,arrears)}); } catch(Exception x) { cases.Add(new {Name=$"treasury-{cases.Count}",Kind="Treasury",Balance=balance,NetPerDay=net,Arrears=arrears,ExpectedError=x.Message}); }
    File.WriteAllText(args[0],JsonSerializer.Serialize(new {Format="stellar-colony-economy-parity-v1",Cases=cases},options)+Environment.NewLine); Console.WriteLine($"Exported {cases.Count} colony economy parity cases."); return 0;
} catch(Exception x) { Console.Error.WriteLine($"Colony parity fixture failed: {x}"); return 1; }
