using System.Globalization;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Game.Simulation.Combat;
using Game.Simulation.Combat.Massive;
using Game.Simulation.Knowledge;
using Game.Simulation.Models;

if(args.Length!=1)throw new ArgumentException("Expected fixture path.");
CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;CultureInfo.CurrentUICulture=CultureInfo.InvariantCulture;
var json=new JsonSerializerOptions{WriteIndented=true,IncludeFields=true,NumberHandling=JsonNumberHandling.AllowNamedFloatingPointLiterals};
JsonElement Freeze(object?o)=>JsonSerializer.SerializeToElement(o,json);
StarSystemState System(int id)=>new(id,"System "+id,new Vector2(id,0),StarArchetype.Standard,false,false,false,false);
FleetCombatState Combat(string profile="patrol_corvette_mk1")=>new(){ProfileId=profile,Shields=35,Armor=45,Hull=95,WeaponCooldownRemainingDays=0,Order=MilitaryOrderType.Hold};
FleetState Fleet(int id=1,int civ=1,string name="Alpha",FleetRole role=FleetRole.Military,int? system=10)=>new(){Id=id,CivilizationId=civ,Name=name,Role=role,DesignId="design",Position=new(1,2),CurrentSystemId=system,DestinationSystemId=20,TransitPhase=FleetTransitPhase.None,TransitOriginSystemId=9,TransitTargetSystemId=10,TransitProgress=.2,LocalTransitStart=new(.1f,.2f),LocalTransitPosition=new(.3f,.4f),LocalTransitTarget=new(.5f,.6f),PlannedRouteSystemIds=new(){20},HoldRequested=true,ReturnToBaseRequested=true,ReturnToBaseFailureReason="old",MissionOrderRevision=4,DestinationPlanetaryBodyId=77,PreventAutomaticSettlement=true,SettlementBodyId=78,SettlementDaysCompleted=2,ReconnaissanceSystemId=10,ReconnaissanceDaysCompleted=3,FreightTargetOutpostId=30,FreightHomeColonyId=20,CargoMaterialCapacity=100,CargoMaterials=5,StrategicSpeed=22,MaximumLegRangeLightYears=50,FuelCapacityLightYears=100,FuelRemainingLightYears=80,SensorRange=90,IsActive=true,EmbarkedPopulationMillions=4.125,EmbarkedPopulationSpeciesId="terran_baseline",Combat=Combat(),TacticalVessel=new MassiveVesselState{Id=id,Name=name+" vessel",DesignId="design",IsFlagship=true,HullFraction=.8f,EngineFraction=.7f,SensorFraction=.6f,WarpDriveFraction=.5f,ReactorFraction=.4f,InterdictorFraction=.3f,BattlesFought=3,ConfirmedKills=2}};
GalaxyState World()=>new(){Seed=30,Systems=new[]{System(10),System(20)},PlanetaryBodies=Array.Empty<PlanetaryBodyState>(),Civilizations=new List<CivilizationState>(),Fleets=new List<FleetState>{Fleet(),Fleet(2,2,"Beta")},Colonies=new List<ColonyState>(),Economies=Array.Empty<CivilizationEconomyState>(),Technologies=new List<Game.Simulation.Research.TechnologyState>(),ConstructionStates=new List<Game.Simulation.Construction.ConstructionState>(),ShipyardStates=new List<Game.Simulation.Shipbuilding.ShipyardState>(),PlayerCivilizationId=1,Knowledge=new CivilizationKnowledgeState()};
object Snapshot(GalaxyState w)=>new{w.Systems,w.Fleets};
var cases=new List<object>();
void Add(string name,Action<GalaxyState>?setup,Command[]commands,bool hostile=true,bool throwHostility=false){var w=World();setup?.Invoke(w);var stub=new StubHostility(hostile,throwHostility);var sim=new CombatSimulation(stub);var args0=Freeze(new{World=Snapshot(w),Commands=commands,Hostile=hostile,ThrowHostility=throwHostility});var before=Freeze(Snapshot(w));var results=new List<object>();foreach(var c in commands){object?raw=null;Exception?caught=null;try{raw=c.Kind switch{"Order"=>sim.IssueOrder(w,c.CivilizationId,c.FleetId,new MilitaryOrder(c.OrderType,c.TargetFleetId,c.DefendSystemId)),"Advance"=>sim.Advance(w,c.Days),"Summary"=>sim.GetOwnMilitaryForceSummary(w,c.CivilizationId),_=>throw new InvalidOperationException("Unknown oracle command")};}catch(Exception e){caught=e;}var result=Freeze(raw);var error=caught is null?(JsonElement?)null:Freeze(new{Type=caught.GetType().Name,caught.Message});results.Add(new{Command=Freeze(c),Result=result,Error=error,After=Freeze(Snapshot(w))});}cases.Add(new{Name=name,Arguments=args0,Before=before,Result=Freeze(results),After=Freeze(Snapshot(w)),HostilityCalls=Freeze(stub.Calls)});}
Command Order(MilitaryOrderType type,int fleet=1,int civ=1,int?target=null,int?defend=null)=>new("Order",civ,fleet,type,target,defend);
Command Advance(double days)=>new("Advance",Days:days);
Command Summary(int civ=1)=>new("Summary",CivilizationId:civ);

Add("order-hold",null,new[]{Order(MilitaryOrderType.Hold)});Add("order-defend-default",null,new[]{Order(MilitaryOrderType.Defend)});Add("order-defend-explicit",null,new[]{Order(MilitaryOrderType.Defend,defend:10)});Add("order-attack",null,new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-retreat",null,new[]{Order(MilitaryOrderType.Retreat)});
Add("order-missing",null,new[]{Order(MilitaryOrderType.Hold,fleet:99)});Add("order-inactive",w=>w.Fleets[0].IsActive=false,new[]{Order(MilitaryOrderType.Hold)});Add("order-wrong-owner",null,new[]{Order(MilitaryOrderType.Hold,civ:2)});Add("order-first-invalid-duplicate",w=>{w.Fleets[0].IsActive=false;w.Fleets.Add(Fleet());},new[]{Order(MilitaryOrderType.Hold)});Add("order-first-valid-duplicate",w=>w.Fleets.Add(Fleet(name:"Second")),new[]{Order(MilitaryOrderType.Hold)});
Add("order-lazy-null-state-rejected-defend",w=>w.Fleets[0]=Fleet(role:FleetRole.Scout),new[]{Order(MilitaryOrderType.Defend)});Add("order-lazy-unknown-state",w=>w.Fleets[0].Combat=Combat("unknown"),new[]{Order(MilitaryOrderType.Hold)});
Add("order-defend-unarmed",w=>w.Fleets[0].Combat=Combat("civilian_light_v1"),new[]{Order(MilitaryOrderType.Defend)});Add("order-defend-no-current",w=>w.Fleets[0].CurrentSystemId=null,new[]{Order(MilitaryOrderType.Defend)});Add("order-defend-other-system",null,new[]{Order(MilitaryOrderType.Defend,defend:20)});Add("order-defend-unknown-system",w=>w.Fleets[0].CurrentSystemId=99,new[]{Order(MilitaryOrderType.Defend)});
Add("order-attack-unarmed",w=>w.Fleets[0].Combat=Combat("civilian_light_v1"),new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-attack-no-target",null,new[]{Order(MilitaryOrderType.Attack)});Add("order-attack-missing-target",null,new[]{Order(MilitaryOrderType.Attack,target:99)});Add("order-attack-inactive-target",w=>w.Fleets[1].IsActive=false,new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-attack-friendly",w=>w.Fleets[1]=Fleet(2,1,"Beta"),new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-attack-other-system",w=>w.Fleets[1].CurrentSystemId=20,new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-attack-target-disengaged",w=>{w.Fleets[1].Combat!.IsDisengaged=true;w.Fleets[1].Combat!.DisengagedSystemId=10;},new[]{Order(MilitaryOrderType.Attack,target:2)});Add("order-attack-peaceful",null,new[]{Order(MilitaryOrderType.Attack,target:2)},false);Add("order-unknown",null,new[]{Order((MilitaryOrderType)99)});
Add("order-sequence-reset",w=>{var s=w.Fleets[0].Combat!;s.IsDisengaged=true;s.DisengagedSystemId=10;s.RetreatProgressDays=2;s.RetreatStarted=true;},new[]{Order(MilitaryOrderType.Hold),Order(MilitaryOrderType.Defend),Order(MilitaryOrderType.Retreat)});
Add("order-hostility-callback-failure",w=>{w.Fleets[0].Combat=null;w.Fleets[1].Combat=null;},new[]{Order(MilitaryOrderType.Attack,target:2)},throwHostility:true);

Add("summary-basic",null,new[]{Summary()});Add("summary-other-civ",null,new[]{Summary(2)});Add("summary-none",null,new[]{Summary(9)});Add("summary-unarmed",w=>w.Fleets[0].Combat=Combat("civilian_light_v1"),new[]{Summary()});Add("summary-inactive",w=>w.Fleets[0].IsActive=false,new[]{Summary()});Add("summary-null-state",w=>w.Fleets[0].Combat=null,new[]{Summary()});Add("summary-damaged",w=>{var s=w.Fleets[0].Combat!;s.Shields=3;s.Armor=4;s.Hull=20;},new[]{Summary()});Add("summary-overmax-normalized",w=>{var s=w.Fleets[0].Combat!;s.Shields=999;s.Armor=999;s.Hull=999;},new[]{Summary()});Add("summary-nan-hull",w=>w.Fleets[0].Combat!.Hull=double.NaN,new[]{Summary()});Add("summary-two-armed",w=>w.Fleets.Add(Fleet(3,1,"Gamma")),new[]{Summary()});

void AttackSetup(GalaxyState w){w.Fleets[0].Combat!.Order=MilitaryOrderType.Attack;w.Fleets[0].Combat!.TargetFleetId=2;}
foreach(var d in new[]{-1d,-0d,0d,.00000005,.0000001,.1,.75,1.5,3d})Add("advance-attack-delta-"+cases.Count,AttackSetup,new[]{Advance(d)});
Add("advance-idle",null,new[]{Advance(1)});Add("advance-lazy-all",w=>{w.Fleets[0].Combat=null;w.Fleets[1].Combat=null;},new[]{Advance(1)});Add("advance-stale-target",w=>{AttackSetup(w);w.Fleets[1].IsActive=false;},new[]{Advance(1)});Add("advance-friendly-clears",w=>{AttackSetup(w);w.Fleets[1]=Fleet(2,1,"Beta");},new[]{Advance(1)});Add("advance-other-system-clears",w=>{AttackSetup(w);w.Fleets[1].CurrentSystemId=20;},new[]{Advance(1)});Add("advance-peace-clears",AttackSetup,new[]{Advance(1)},false);Add("advance-target-disengaged-clears",w=>{AttackSetup(w);w.Fleets[1].Combat!.IsDisengaged=true;w.Fleets[1].Combat!.DisengagedSystemId=10;},new[]{Advance(1)});
Add("advance-return-fire",AttackSetup,new[]{Advance(.75)});Add("advance-defender-retreat",w=>{AttackSetup(w);w.Fleets[1].Combat!.Order=MilitaryOrderType.Retreat;},new[]{Advance(.5)});Add("advance-attacker-retreat",w=>{w.Fleets[0].Combat!.Order=MilitaryOrderType.Retreat;w.Fleets[1].Combat!.Order=MilitaryOrderType.Attack;w.Fleets[1].Combat!.TargetFleetId=1;},new[]{Advance(.5)});
Add("advance-unthreatened-retreat",w=>w.Fleets[0].Combat!.Order=MilitaryOrderType.Retreat,new[]{Advance(.1)});Add("advance-retreat-threshold-below",w=>{AttackSetup(w);w.Fleets[1].Combat!.Order=MilitaryOrderType.Retreat;w.Fleets[1].Combat!.RetreatProgressDays=.7499998;},new[]{Advance(.75)});Add("advance-retreat-threshold-epsilon",w=>{AttackSetup(w);w.Fleets[1].Combat!.Order=MilitaryOrderType.Retreat;w.Fleets[1].Combat!.RetreatProgressDays=.7499999;},new[]{Advance(.75)});
Add("advance-destroy-civilian-population",w=>{AttackSetup(w);var s=w.Fleets[1].Combat!;s.Shields=0;s.Armor=0;s.Hull=1;},new[]{Advance(.75)});Add("advance-shield-armor-hull",w=>{AttackSetup(w);var s=w.Fleets[1].Combat!;s.Shields=5;s.Armor=5;s.Hull=30;},new[]{Advance(.75)});Add("advance-simultaneous-destruction",w=>{AttackSetup(w);w.Fleets[1].Combat!.Order=MilitaryOrderType.Attack;w.Fleets[1].Combat!.TargetFleetId=1;foreach(var f in w.Fleets){f.Combat!.Shields=0;f.Combat!.Armor=0;f.Combat!.Hull=1;}},new[]{Advance(.75)});
Add("advance-cooldown-no-volley",w=>{AttackSetup(w);w.Fleets[0].Combat!.WeaponCooldownRemainingDays=2;},new[]{Advance(.5)});Add("advance-cooldown-exact",w=>{AttackSetup(w);w.Fleets[0].Combat!.WeaponCooldownRemainingDays=.75;},new[]{Advance(.75)});Add("advance-multiple-volleys",AttackSetup,new[]{Advance(2.25)});Add("advance-nan-cooldown",w=>{AttackSetup(w);w.Fleets[0].Combat!.WeaponCooldownRemainingDays=double.NaN;},new[]{Advance(.1)});
Add("advance-defend-joins",w=>{AttackSetup(w);w.Fleets.Add(Fleet(3,2,"Guard"));w.Fleets[2].Combat!.Order=MilitaryOrderType.Defend;w.Fleets[2].Combat!.DefendSystemId=10;},new[]{Advance(.75)});Add("advance-defend-lowest-threat",w=>{w.Fleets.Add(Fleet(3,1,"Low"));w.Fleets.Add(Fleet(4,1,"High"));foreach(var id in new[]{3,4}){w.Fleets[id-1].Combat!.Order=MilitaryOrderType.Attack;w.Fleets[id-1].Combat!.TargetFleetId=2;}w.Fleets[1].Combat!.Order=MilitaryOrderType.Defend;w.Fleets[1].Combat!.DefendSystemId=10;},new[]{Advance(.75)});
Add("advance-engagement-persistence",AttackSetup,new[]{Advance(.1),Advance(.1),Order(MilitaryOrderType.Hold),Advance(.1)});Add("advance-destroy-engagement-ended-next-state",w=>{AttackSetup(w);w.Fleets[1].Combat!.Shields=0;w.Fleets[1].Combat!.Armor=0;w.Fleets[1].Combat!.Hull=1;},new[]{Advance(.75),Advance(.1)});
Add("advance-duplicate-active",w=>w.Fleets.Add(Fleet()),new[]{Advance(.1)});Add("advance-duplicate-inactive",w=>{var f=Fleet();f.IsActive=false;w.Fleets.Add(f);},new[]{Advance(.1)});
Add("advance-duplicate-active-lowest-sorted",w=>{w.Fleets.Clear();w.Fleets.Add(Fleet(5));w.Fleets.Add(Fleet(5));w.Fleets.Add(Fleet(1));w.Fleets.Add(Fleet(1));},new[]{Advance(.1)});

File.WriteAllText(args[0],JsonSerializer.Serialize(new{Format="stellar-combat-simulation-oracle-v1",Cases=cases},json));
sealed record Command(string Kind,int CivilizationId=0,int FleetId=0,MilitaryOrderType OrderType=MilitaryOrderType.Hold,int?TargetFleetId=null,int?DefendSystemId=null,double Days=0);
sealed class StubHostility(bool hostile,bool throwHostility):ICombatHostilityView{public List<object>Calls{get;}=new();public bool AreHostile(int a,int b){Calls.Add(new{FirstCivilizationId=a,SecondCivilizationId=b});if(throwHostility)throw new InvalidOperationException("Hostility oracle failure.");return hostile;}}
