using System.Globalization;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Game.Simulation.Construction;
using Game.Simulation.Economy;
using Game.Simulation.Generation;
using Game.Simulation.Models;
using Game.Simulation.Species;

try {
    CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
    if (args.Length != 1) throw new ArgumentException("Expected output fixture path");
    var json = new JsonSerializerOptions { WriteIndented = true, PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate };
    T Clone<T>(T value) {
        var clone = JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value, json), json)!;
        if (value is GalaxyState source && clone is GalaxyState destination) {
            for (var index = 0; index < source.ConstructionStates.Count; ++index) {
                foreach (var projectId in source.ConstructionStates[index].CompletedProjectIds)
                    destination.ConstructionStates[index].CompletedProjectIds.Add(projectId);
                if (!destination.ConstructionStates[index].CompletedProjectIds.SetEquals(source.ConstructionStates[index].CompletedProjectIds))
                    throw new InvalidOperationException("Galaxy clone lost completed construction project IDs.");
            }
        }
        return clone;
    }
    PlanetaryBodyState Body(int id = 3) => new(id, 0, null, 0, "Earth", PlanetaryBodyKind.Planet, 1, 1,
        new(1, 288, 101, PlanetaryAtmosphereRegime.OxygenNitrogen, PlanetarySolventRegime.Water, .01, false, true), false, false, false, false);
    CivilizationState Civ(int id, bool ancient = false, string species = SpeciesCatalog.TerranBaselineId) => new(id, "Civ " + id, 0, CivilizationArchetype.Scientific, new(0,0,0,0,0,0,false), true,
        ancient ? CivilizationDevelopmentStage.AncientSpacefaring : CivilizationDevelopmentStage.WarpCapable, ancient, SpeciesId: species);
    GalaxyState World(double credits, double population = 1000, bool ancient = false, IEnumerable<string>? projects = null, double arrears = 0, bool hostile = false, bool outpost = false, string species = SpeciesCatalog.TerranBaselineId, PlanetaryBodyState? authoredBody = null) {
        var construction = new ConstructionState { CivilizationId = 1 }; foreach (var p in projects ?? Array.Empty<string>()) construction.CompletedProjectIds.Add(p);
        var body = authoredBody ?? (species != SpeciesCatalog.TerranBaselineId
            ? IdealBody(3, species) with { HasRareResource = outpost }
            : hostile ? Body() with { Environment = new(0.1, 100, 0, PlanetaryAtmosphereRegime.Vacuum, PlanetarySolventRegime.None, 1, false, true), HasRareResource = outpost } : Body() with { HasRareResource = outpost });
        return new() { Seed = 1, Systems = Array.Empty<StarSystemState>(), PlanetaryBodies = new[] { body }, Civilizations = new List<CivilizationState> { Civ(1, ancient, species) }, Fleets = new List<FleetState>(),
            Colonies = new List<ColonyState> { new() { Id = 1, CivilizationId = 1, SystemId = body.SystemId, PlanetaryBodyId = body.Id, Name = body.Name, Kind = outpost ? SettlementKind.ResourceOutpost : SettlementKind.Colony, PopulationSpeciesId = species, PopulationMillions = population, Infrastructure = 1, Stability = 1, StoredFoodPopulationDaysMillions = population * 30, StoredWaterPopulationDaysMillions = population * 7 } },
            Economies = new[] { new CivilizationEconomyState { CivilizationId = 1, Credits = credits, OperatingArrears = arrears } }, Technologies = new List<Game.Simulation.Research.TechnologyState>(), ConstructionStates = new List<ConstructionState> { construction }, ShipyardStates = new List<Game.Simulation.Shipbuilding.ShipyardState>(), PlayerCivilizationId = 1, Knowledge = new Game.Simulation.Knowledge.CivilizationKnowledgeState() };
    }
    PlanetaryBodyState IdealBody(int id, string species) {
        var profile = SpeciesCatalog.Get(species);
        var atmosphere = profile.Environment.PreferredAtmosphere switch {
            AtmosphereClass.OxygenNitrogen => PlanetaryAtmosphereRegime.OxygenNitrogen,
            AtmosphereClass.OxygenRich => PlanetaryAtmosphereRegime.OxygenRich,
            AtmosphereClass.Reducing => PlanetaryAtmosphereRegime.Reducing,
            _ => PlanetaryAtmosphereRegime.Other,
        };
        var solvent = profile.Environment.BiologicalSolvent switch {
            SolventClass.Water => PlanetarySolventRegime.Water,
            SolventClass.Hydrocarbon => PlanetarySolventRegime.Hydrocarbon,
            _ => PlanetarySolventRegime.Other,
        };
        return new(id, 0, null, 0, "Ideal " + species, PlanetaryBodyKind.Planet, 1, 1,
            new(profile.Environment.GravityG.Preferred, profile.Environment.TemperatureKelvin.Preferred,
                profile.Environment.PressureKPa.Preferred, atmosphere, solvent, .01,
                profile.Environment.RequiresImmersion, true), false, false, false, false);
    }
    var cases = new List<object>();
    void Flow(string name, GalaxyState world, bool research = true) { var before = Clone(world); var expected = EconomySimulation.GetCreditFlow(world, 1, research); cases.Add(new { Name = name, Kind = "CreditFlow", World = before, Arguments = new { CivilizationId = 1, IncludeResearch = research, PowerIntervalDays = 1d }, Before = before, Expected = expected, After = Clone(world) }); }
    void Building(GalaxyState world, int id, string type, double condition = 1, bool enabled = true, int priority = 0, double stored = 0) => world.Colonies[0].SurfaceBuildings.Add(new SurfaceBuildingState { Id = id, TypeId = type, IsComplete = true, IsEnabled = enabled, Condition = condition, OperatingPriority = priority, StoredPowerDays = stored });
    Flow("credit-flow-baseline", World(500));
    var fleetWorld = World(500, projects: ConstructionRegistry.All.Select(x => x.Id)); foreach (var role in Enum.GetValues<FleetRole>()) fleetWorld.Fleets.Add(new FleetState { Id = (int)role + 1, CivilizationId = 1, Name = role.ToString(), Role = role, Position = Vector2.Zero, IsActive = true }); fleetWorld.Fleets.Add(new FleetState { Id = 99, CivilizationId = 1, Name = "inactive", Role = FleetRole.Military, Position = Vector2.Zero, IsActive = false }); fleetWorld.Economies[0].LastResearchSpendingPerDay = .37; Flow("credit-flow-projects-fleets-research", fleetWorld); Flow("credit-flow-research-excluded", Clone(fleetWorld), false);
    var funded = World(5000); var fundedBefore = Clone(funded); new EconomySimulation().Advance(funded, 3); if (funded.Economies[0].LastBaseOperationsFundingFraction != 1 || funded.Economies[0].Industry <= 200) throw new InvalidOperationException("Funded case did not fund or produce industry."); cases.Add(new { Name="advance-funded-growth",Kind="Advance",World=fundedBefore,Arguments=new {Days=3d,AccrueLegacyScience=true},Before=fundedBefore,After=Clone(funded) });
    var partial = World(0); var partialBefore=Clone(partial); new EconomySimulation().Advance(partial, 1); if (partial.Economies[0].LastBaseOperationsFundingFraction is <= 0 or >= 1) throw new InvalidOperationException("Partial funding case did not activate partial funding."); cases.Add(new { Name="advance-part-funded",Kind="Advance",World=partialBefore,Arguments=new {Days=1d,AccrueLegacyScience=true},Before=partialBefore,After=Clone(partial) });
    var unfunded = World(0, 1000, false, null, 1000); var unfundedBefore=Clone(unfunded); new EconomySimulation().Advance(unfunded,1); if(unfunded.Economies[0].LastBaseOperationsFundingFraction != 0 || unfunded.Economies[0].OperatingArrears < unfundedBefore.Economies[0].OperatingArrears) throw new InvalidOperationException("Unfunded arrears case did not retain arrears at zero funding."); cases.Add(new {Name="advance-unfunded-arrears",Kind="Advance",World=unfundedBefore,Arguments=new {Days=1d,AccrueLegacyScience=true},Before=unfundedBefore,After=Clone(unfunded)});
    var recovery = World(10000, 1000, false, new[] { "industrial_automation", "research_network", "asteroid_resource_network" }, 10); var recoveryBefore=Clone(recovery); new EconomySimulation().Advance(recovery,4); if(recovery.Economies[0].OperatingArrears >= recoveryBefore.Economies[0].OperatingArrears || recovery.Economies[0].LastBaseOperationsFundingFraction < .999999) throw new InvalidOperationException("Arrears recovery case did not clear arrears at full funding."); cases.Add(new {Name="advance-arrears-recovery",Kind="Advance",World=recoveryBefore,Arguments=new {Days=4d,AccrueLegacyScience=true},Before=recoveryBefore,After=Clone(recovery)});
    var noRecordedResearch = World(5000); var recordedResearch = Clone(noRecordedResearch); recordedResearch.Economies[0].LastResearchSpendingPerDay=.73; var noRecordedResearchBefore=Clone(noRecordedResearch); var recordedResearchBefore=Clone(recordedResearch); new EconomySimulation().Advance(noRecordedResearch,2); new EconomySimulation().Advance(recordedResearch,2); if(recordedResearch.Economies[0].LastResearchSpendingPerDay!=.73) throw new InvalidOperationException("Advance did not preserve recorded research spending."); if(recordedResearch.Economies[0].Credits!=noRecordedResearch.Economies[0].Credits || recordedResearch.Economies[0].OperatingArrears!=noRecordedResearch.Economies[0].OperatingArrears || recordedResearch.Economies[0].LastBaseOperationsFundingFraction!=noRecordedResearch.Economies[0].LastBaseOperationsFundingFraction) throw new InvalidOperationException("Base Advance double-charged recorded research spending."); cases.Add(new {Name="advance-no-recorded-research-control",Kind="Advance",World=noRecordedResearchBefore,Arguments=new {Days=2d,AccrueLegacyScience=true},Before=noRecordedResearchBefore,After=Clone(noRecordedResearch)}); cases.Add(new {Name="advance-recorded-research-not-double-charged",Kind="Advance",World=recordedResearchBefore,Arguments=new {Days=2d,AccrueLegacyScience=true},Before=recordedResearchBefore,After=Clone(recordedResearch)});
    var noScience = World(5000); var noScienceBefore=Clone(noScience); new EconomySimulation().Advance(noScience,2,false); if(noScience.Economies[0].Science != noScienceBefore.Economies[0].Science || noScience.Economies[0].LastSciencePerSecond != 0) throw new InvalidOperationException("Legacy science off case accrued science."); cases.Add(new {Name="advance-legacy-science-off",Kind="Advance",World=noScienceBefore,Arguments=new {Days=2d,AccrueLegacyScience=false},Before=noScienceBefore,After=Clone(noScience)});
    var zero=World(5000); var zeroBefore=Clone(zero); new EconomySimulation().Advance(zero,0); if(JsonSerializer.Serialize(zero,json)!=JsonSerializer.Serialize(zeroBefore,json)) throw new InvalidOperationException("Zero-day advance mutated state."); cases.Add(new {Name="advance-zero-days-noop",Kind="Advance",World=zeroBefore,Arguments=new {Days=0d,AccrueLegacyScience=true},Before=zeroBefore,After=Clone(zero)});
    var declining = World(5000, 1000, hostile:true); var declineBefore=Clone(declining); new EconomySimulation().Advance(declining,20); if(declining.Colonies[0].PopulationMillions>=declineBefore.Colonies[0].PopulationMillions) throw new InvalidOperationException("Population decline case did not decline."); cases.Add(new { Name="advance-population-decline",Kind="Advance",World=declineBefore,Arguments=new {Days=20d,AccrueLegacyScience=true},Before=declineBefore,After=Clone(declining) });
    var ancient = World(50000, 12000, true, ConstructionRegistry.All.Select(x => x.Id)); var ancientBefore=Clone(ancient); new EconomySimulation().Advance(ancient,5); if(EconomySimulation.GetIndustryStorageCapacity(ancient,1)!=50000 || ancient.Economies[0].Industry<=ancientBefore.Economies[0].Industry) throw new InvalidOperationException("Ancient case did not use storage or project effects."); cases.Add(new {Name="advance-ancient-all-projects",Kind="Advance",World=ancientBefore,Arguments=new {Days=5d,AccrueLegacyScience=true},Before=ancientBefore,After=Clone(ancient)});
    var repeat = World(5000); var repeatStart=Clone(repeat); new EconomySimulation().Advance(repeat,1); var repeatFirst=Clone(repeat); new EconomySimulation().Advance(repeat,1); if(repeat.Economies[0].Industry<=repeatFirst.Economies[0].Industry || repeat.Colonies[0].PopulationMillions==repeatStart.Colonies[0].PopulationMillions) throw new InvalidOperationException("Repeated advance did not continue progression."); cases.Add(new {Name="advance-repeated-first",Kind="Advance",World=repeatStart,Arguments=new {Days=1d,AccrueLegacyScience=true},Before=repeatStart,After=repeatFirst}); cases.Add(new {Name="advance-repeated-second",Kind="Advance",World=repeatFirst,Arguments=new {Days=1d,AccrueLegacyScience=true},Before=repeatFirst,After=Clone(repeat)});
    var surface = World(0); Building(surface, 1, "power_generator"); Building(surface, 2, "science_lab", .5); Building(surface, 3, "fabricator", 1, false); Building(surface, 4, "grid_battery", 1, true, 2, 4); Building(surface, 5, "trade_hub", .14); Flow("credit-flow-damaged-unstaffed-unpowered-battery", surface); var surfaceBefore=Clone(surface); new EconomySimulation().Advance(surface,2); if(surface.Colonies[0].SurfaceBuildings[0].Condition>=surfaceBefore.Colonies[0].SurfaceBuildings[0].Condition || surface.Colonies[0].SurfaceBuildings[3].StoredPowerDays==surfaceBefore.Colonies[0].SurfaceBuildings[3].StoredPowerDays) throw new InvalidOperationException("Surface case did not wear buildings and mutate battery."); cases.Add(new {Name="advance-surface-condition-and-battery",Kind="Advance",World=surfaceBefore,Arguments=new {Days=2d,AccrueLegacyScience=true},Before=surfaceBefore,After=Clone(surface)});
    var healthyTrade = World(5000); Building(healthyTrade,1,"power_generator"); Building(healthyTrade,2,"trade_hub"); var healthyTradeFlow=EconomySimulation.GetCreditFlow(healthyTrade,1); if(healthyTradeFlow.TradeRevenuePerDay<=0) throw new InvalidOperationException("Healthy staffed powered trade fixture produced no trade revenue."); Flow("credit-flow-healthy-powered-trade",healthyTrade);
    var unknown = World(5000, projects: new[] { "unknown_project" }); unknown.Fleets.Add(new FleetState { Id = 1, CivilizationId = 1, Name = "unknown-role-fallback", Role = (FleetRole)99, Position = Vector2.Zero }); if(Math.Abs(EconomySimulation.GetCreditFlow(unknown,1).FleetOperationsPerDay-.12)>.0000001) throw new InvalidOperationException("Unknown fleet role did not use fallback cost."); Flow("credit-flow-unknown-project-and-role", unknown);
    var outpost = World(5000, 5, outpost:true); Building(outpost, 1, "power_generator"); Building(outpost, 2, "fabricator"); var outpostBefore=Clone(outpost); new EconomySimulation().Advance(outpost, 3); if(outpost.Colonies[0].StoredExtractedMaterials<=0) throw new InvalidOperationException("Outpost case did not extract materials."); cases.Add(new {Name="advance-funded-powered-resource-outpost",Kind="Advance",World=outpostBefore,Arguments=new {Days=3d,AccrueLegacyScience=true},Before=outpostBefore,After=Clone(outpost)});
    var fullOutpost = World(5000, 5, outpost:true); Building(fullOutpost, 1, "power_generator"); Building(fullOutpost, 2, "fabricator"); fullOutpost.Colonies[0].StoredExtractedMaterials = 125; fullOutpost.Colonies[0].RemainingExtractableMaterials = 4000; var fullOutpostBefore=Clone(fullOutpost); new EconomySimulation().Advance(fullOutpost, 2); if(fullOutpost.Colonies[0].StoredExtractedMaterials!=125 || fullOutpost.Colonies[0].RemainingExtractableMaterials!=4000) throw new InvalidOperationException("Full outpost fixture extracted despite full storage."); if(fullOutpost.Economies[0].Credits==fullOutpostBefore.Economies[0].Credits || fullOutpost.Economies[0].LastCreditsPerSecond==0) throw new InvalidOperationException("Full outpost fixture did not remain linked to economy advance."); cases.Add(new {Name="advance-full-storage-resource-outpost",Kind="Advance",World=fullOutpostBefore,Arguments=new {Days=2d,AccrueLegacyScience=true},Before=fullOutpostBefore,After=Clone(fullOutpost)});
    var depletedOutpost = World(5000, 5, outpost:true); Building(depletedOutpost, 1, "power_generator"); Building(depletedOutpost, 2, "fabricator"); depletedOutpost.Colonies[0].StoredExtractedMaterials = 12; depletedOutpost.Colonies[0].RemainingExtractableMaterials = 0; var depletedOutpostBefore=Clone(depletedOutpost); new EconomySimulation().Advance(depletedOutpost, 2); if(depletedOutpost.Colonies[0].StoredExtractedMaterials!=12 || depletedOutpost.Colonies[0].RemainingExtractableMaterials!=0) throw new InvalidOperationException("Depleted outpost fixture extracted material."); if(depletedOutpost.Economies[0].Credits==depletedOutpostBefore.Economies[0].Credits || depletedOutpost.Economies[0].LastCreditsPerSecond==0) throw new InvalidOperationException("Depleted outpost fixture did not remain linked to economy advance."); cases.Add(new {Name="advance-depleted-resource-outpost",Kind="Advance",World=depletedOutpostBefore,Arguments=new {Days=2d,AccrueLegacyScience=true},Before=depletedOutpostBefore,After=Clone(depletedOutpost)});

    var sol = new StarSystemState(0, "Sol", Vector2.Zero, StarArchetype.Standard, true, false, false, false, SolCatalogPreset.PresetId);
    var solBodies = SolCatalogPreset.Create(sol);
    var luna = solBodies.First(body=>body.Id==SolCatalogPreset.MoonBodyId);
    var lunaWithoutHabitat = World(5000,authoredBody:luna); var lunaBaseFlow=EconomySimulation.GetCreditFlow(lunaWithoutHabitat,1); if(lunaBaseFlow.HabitatSupportPerDay<=0) throw new InvalidOperationException("Luna fixture did not activate habitat support burden."); Flow("credit-flow-luna-habitat-burden",lunaWithoutHabitat);
    var lunaWithHabitat = World(5000,authoredBody:luna); Building(lunaWithHabitat,1,"power_generator"); Building(lunaWithHabitat,2,"habitat_complex"); var lunaReducedFlow=EconomySimulation.GetCreditFlow(lunaWithHabitat,1); if(lunaReducedFlow.HabitatSupportPerDay<=0 || lunaReducedFlow.HabitatSupportPerDay>=lunaBaseFlow.HabitatSupportPerDay) throw new InvalidOperationException("Powered Luna habitat complex did not reduce a positive support burden."); Flow("credit-flow-luna-powered-habitat-reduction",lunaWithHabitat);
    var solCivilizations = new List<CivilizationState> { Civ(1) };
    var colonySeeder = new ColonySeeder();
    var solColonies = colonySeeder.Seed(solCivilizations, solBodies);
    if(solColonies.Select(x=>x.Name).SequenceEqual(new[]{"Earth","Luna","Mars"})==false) throw new InvalidOperationException("ColonySeeder did not create canonical Earth/Luna/Mars settlements.");
    var solWorld = new GalaxyState { Seed=1, Systems=new[]{sol}, PlanetaryBodies=solBodies, Civilizations=solCivilizations, Fleets=new List<FleetState>(), Colonies=solColonies, Economies=colonySeeder.SeedEconomies(solCivilizations), Technologies=new List<Game.Simulation.Research.TechnologyState>(), ConstructionStates=new ConstructionSeeder().Seed(solCivilizations), ShipyardStates=new List<Game.Simulation.Shipbuilding.ShipyardState>(), PlayerCivilizationId=1, Knowledge=new Game.Simulation.Knowledge.CivilizationKnowledgeState() };
    var solBefore=Clone(solWorld); new EconomySimulation().Advance(solWorld,3); if(solWorld.Colonies.Count!=3 || solWorld.Colonies.Any(c=>c.PopulationMillions<=0) || solWorld.Economies[0].LastBaseOperationsFundingFraction<=0) throw new InvalidOperationException("Earth/Luna/Mars economy scenario did not advance all seeded settlements."); cases.Add(new {Name="advance-colony-seeder-earth-luna-mars",Kind="Advance",World=solBefore,Arguments=new {Days=3d,AccrueLegacyScience=true},Before=solBefore,After=Clone(solWorld)});

    foreach(var species in new[]{SpeciesCatalog.PelagicHighPressureId,SpeciesCatalog.CompactHighGravityId,SpeciesCatalog.CryogenicHydrocarbonId}) {
        var speciesWorld=World(5000,species:species); var speciesBefore=Clone(speciesWorld); new EconomySimulation().Advance(speciesWorld,10); if(speciesWorld.Colonies[0].PopulationMillions==speciesBefore.Colonies[0].PopulationMillions || speciesWorld.Economies[0].Industry<=speciesBefore.Economies[0].Industry) throw new InvalidOperationException($"Species economy fixture {species} did not activate growth and production."); cases.Add(new {Name="advance-species-"+species,Kind="Advance",World=speciesBefore,Arguments=new {Days=10d,AccrueLegacyScience=true},Before=speciesBefore,After=Clone(speciesWorld)});
    }

    var storage = World(500, projects: new[] { "industrial_automation", "orbital_launch_complex", "orbital_shipyard", "asteroid_resource_network" }); storage.Economies[0].Industry = 999999; var storageBefore = Clone(storage); EconomySimulation.ApplyIndustryStorageCaps(storage, new Dictionary<int, double> { [1] = 1000000 }); if(storage.Economies[0].Industry!=999999) throw new InvalidOperationException("Existing above-cap storage reserve was not preserved."); cases.Add(new { Name = "storage-preserves-above-cap-reserve", Kind = "Storage", World = storageBefore, Arguments = new { ExistingReserves = new Dictionary<int, double> { [1] = 1000000d } }, Before = storageBefore, After = Clone(storage), ExpectedCapacity = EconomySimulation.GetIndustryStorageCapacity(storage, 1) });
    var storageClamp = World(500); storageClamp.Economies[0].Industry=5000; var storageClampBefore=Clone(storageClamp); EconomySimulation.ApplyIndustryStorageCaps(storageClamp); if(storageClamp.Economies[0].Industry!=1000) throw new InvalidOperationException("Storage cap fixture did not clamp to calculated capacity."); cases.Add(new {Name="storage-clamps-to-real-capacity",Kind="Storage",World=storageClampBefore,Arguments=new {ExistingReserves=new Dictionary<int,double>()},Before=storageClampBefore,After=Clone(storageClamp),ExpectedCapacity=EconomySimulation.GetIndustryStorageCapacity(storageClamp,1)});
    var storageBelow = World(500); storageBelow.Economies[0].Industry=900; var storageBelowBefore=Clone(storageBelow); EconomySimulation.ApplyIndustryStorageCaps(storageBelow); if(storageBelow.Economies[0].Industry!=900) throw new InvalidOperationException("Below-cap storage fixture was changed."); cases.Add(new {Name="storage-preserves-below-cap-industry",Kind="Storage",World=storageBelowBefore,Arguments=new {ExistingReserves=new Dictionary<int,double>()},Before=storageBelowBefore,After=Clone(storageBelow),ExpectedCapacity=EconomySimulation.GetIndustryStorageCapacity(storageBelow,1)});
    var storageLowerReserve = World(500); storageLowerReserve.Economies[0].Industry=5000; var storageLowerReserveBefore=Clone(storageLowerReserve); EconomySimulation.ApplyIndustryStorageCaps(storageLowerReserve,new Dictionary<int,double>{{1,750}}); if(storageLowerReserve.Economies[0].Industry!=1000) throw new InvalidOperationException("Lower legacy reserve incorrectly reduced calculated storage capacity."); cases.Add(new {Name="storage-lower-reserve-uses-real-capacity",Kind="Storage",World=storageLowerReserveBefore,Arguments=new {ExistingReserves=new Dictionary<int,double>{{1,750}}},Before=storageLowerReserveBefore,After=Clone(storageLowerReserve),ExpectedCapacity=EconomySimulation.GetIndustryStorageCapacity(storageLowerReserve,1)});
    var ancientStorage = World(500,ancient:true); ancientStorage.Economies[0].Industry=90000; var ancientStorageBefore=Clone(ancientStorage); EconomySimulation.ApplyIndustryStorageCaps(ancientStorage); if(ancientStorage.Economies[0].Industry!=50000) throw new InvalidOperationException("Ancient storage fixture did not clamp to ancient capacity."); cases.Add(new {Name="storage-clamps-to-ancient-capacity",Kind="Storage",World=ancientStorageBefore,Arguments=new {ExistingReserves=new Dictionary<int,double>()},Before=ancientStorageBefore,After=Clone(ancientStorage),ExpectedCapacity=EconomySimulation.GetIndustryStorageCapacity(ancientStorage,1)});
    var seedCivilizations = new List<CivilizationState> { Civ(1), Civ(2, true) }; var seeded = new Game.Simulation.Generation.ConstructionSeeder().Seed(seedCivilizations); if(seeded[1].CompletedProjectIds.Count!=ConstructionRegistry.All.Count || seeded[0].CompletedProjectIds.Count!=0) throw new InvalidOperationException("Construction seeding did not preserve normal and ancient defaults."); cases.Add(new { Name = "construction-profile-and-ancient-seeding", Kind = "Profiles", Civilizations = seedCivilizations, ExpectedEconomicProfiles = ConstructionRegistry.All.Select(x => new { x.Id, x.IndustryPerDay, x.UpkeepCreditsPerDay }), ExpectedSeed = seeded });
    var errorWorld = World(500); try { EconomySimulation.GetCreditFlow(errorWorld, 1, powerIntervalDays: 0); throw new InvalidOperationException("Invalid power interval did not throw."); } catch (ArgumentOutOfRangeException e) { cases.Add(new { Name = "credit-flow-invalid-power-interval", Kind = "Error", World = Clone(errorWorld), Arguments = new { CivilizationId = 1, PowerIntervalDays = 0d }, ExpectedError = e.Message }); }
    File.WriteAllText(args[0], JsonSerializer.Serialize(new { Format = "stellar-funded-economy-oracle-v1", Cases = cases }, json) + Environment.NewLine);
    Console.WriteLine($"Exported {cases.Count} funded economy oracle cases.");
    return 0;
} catch (Exception exception) { Console.Error.WriteLine(exception); return 1; }
