using System.Globalization;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Game.Simulation.AI;
using Game.Simulation.Construction;
using Game.Simulation.Economy;
using Game.Simulation.Knowledge;
using Game.Simulation.Models;
using Game.Simulation.Research;

CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;CultureInfo.CurrentUICulture=CultureInfo.InvariantCulture;
if(args.Length!=1)throw new ArgumentException("Expected output path.");
var options=new JsonSerializerOptions{WriteIndented=true,NumberHandling=JsonNumberHandling.AllowNamedFloatingPointLiterals};
JsonElement Freeze(object? x)=>JsonSerializer.SerializeToElement(x,options);
CivilizationState Civ(int id,bool player=false,bool ancient=false)=>new(id,$"Civ {id}",0,CivilizationArchetype.Adaptive,CivilizationTraits.Balanced,player,CivilizationDevelopmentStage.WarpCapable,ancient);
GalaxyState World(long seed=10)=>new(){Seed=seed,Systems=Array.Empty<StarSystemState>(),PlanetaryBodies=Array.Empty<PlanetaryBodyState>(),Civilizations=new List<CivilizationState>{Civ(3),Civ(1,true),Civ(4,ancient:true),Civ(2)},Colonies=new List<ColonyState>(),Fleets=new List<FleetState>(),Economies=new List<CivilizationEconomyState>{new CivilizationEconomyState{CivilizationId=2,Industry=20,LastSciencePerSecond=3},new CivilizationEconomyState{CivilizationId=3,Industry=30,LastSciencePerSecond=4}},Technologies=new List<TechnologyState>{new(){CivilizationId=2},new(){CivilizationId=3}},ConstructionStates=new List<ConstructionState>{new(){CivilizationId=2},new(){CivilizationId=3}},ShipyardStates=new List<Game.Simulation.Shipbuilding.ShipyardState>(),PlayerCivilizationId=1,Knowledge=new CivilizationKnowledgeState()};
object WorldState(GalaxyState g)=>new{g.Seed,Civilizations=g.Civilizations.Select(c=>new{c.Id,c.IsPlayer,c.IsSeededAncient,c.Traits}).ToArray(),Economies=g.Economies.Select(e=>new{e.CivilizationId,e.Industry,e.LastSciencePerSecond}).ToArray(),Technologies=g.Technologies.Select(t=>new{t.CivilizationId,t.ActiveResearchId,Completed=t.CompletedTechnologyIds.Order().ToArray()}).ToArray(),Construction=g.ConstructionStates.Select(c=>new{c.CivilizationId,Completed=c.CompletedProjectIds.Order().ToArray()}).ToArray()};
object Review(CivilizationStrategicReview r)=>new{r.OwnState,Plan=new{r.Plan.CivilizationId,r.Plan.GeneratedAtTick,r.Plan.ReviewAfterTick,r.Plan.Priorities},Intent=new{r.Intent.CivilizationId,r.Intent.GeneratedAtTick,r.Intent.ReviewAfterTick,Weights=r.Intent.Weights.OrderBy(x=>(int)x.Key).Select(x=>new{Type=(int)x.Key,x.Value}),PreferredNewFleetRole=r.Intent.PreferredNewFleetRole is null?(int?)null:(int)r.Intent.PreferredNewFleetRole, r.Intent.DeferNewColonization,r.Intent.Summary}};
object Provider(CivilizationStrategicRuntimeCoordinator r)=>new{IntentCount=r.PublishedIntentCount,Weights=new[]{2,3,9}.Select(id=>new{Id=id,Value=r.GetIndustryWeights(id)}).ToArray(),Preferences=new[]{2,3,9}.Select(id=>new{Id=id,Value=r.GetShipbuildingPreference(id)}).ToArray()};
var cases=new List<object>();
void RuntimeCase(string name,IEnumerable<(long Seed,double Days,string Knowledge)> commands,bool defaultProvider=false){var calls=new List<string>();var mode="empty";var kp=new KnowledgeStub(calls,()=>mode);var director=new CivilizationStrategicDirector(new CivilizationStrategicInputBuilder(new LogisticsStub()));var rt=defaultProvider?new CivilizationStrategicRuntimeCoordinator(director):new CivilizationStrategicRuntimeCoordinator(director,knowledgeProvider:kp);var rows=new List<object>();foreach(var c in commands){mode=c.Knowledge;var g=World(c.Seed);if(name=="only-player-ancient"){var keep=g.Civilizations.Where(x=>x.IsPlayer||x.IsSeededAncient).ToArray();g.Civilizations.Clear();foreach(var x in keep)g.Civilizations.Add(x);}if(name=="duplicate-ai-id")((List<CivilizationState>)g.Civilizations).Add(Civ(2));var before=Freeze(WorldState(g));object? result=null;Exception? error=null;IReadOnlyList<CivilizationStrategicReview>? typed=null;var op=c.Knowledge=="reset"?"Reset":"Advance";try{if(op=="Reset")rt.Reset();else typed=rt.Advance(g,c.Days);}catch(Exception e){error=e;}result=typed?.Select(Review).ToArray();rows.Add(new{Command=new{Op=op,c.Seed,Days=double.IsFinite(c.Days)?c.Days.ToString("R",CultureInfo.InvariantCulture):c.Days.ToString(CultureInfo.InvariantCulture),c.Knowledge},Result=result,Error=error is null?null:new{Type=error.GetType().Name,error.Message},Provider=Provider(rt),KnowledgeCalls=calls.ToArray(),Before=before,After=Freeze(WorldState(g))});}cases.Add(new{Name=name,Commands=rows});}
RuntimeCase("schedule-seed-and-order",new[]{(10L,0d,"empty"),(10,.5,"empty"),(10,29.5,"empty"),(11,0d,"empty")});
RuntimeCase("future-after-one-publish-retry",new[]{(20L,0d,"future3"),(20,0d,"empty"),(20,30d,"empty")});
RuntimeCase("invalid-delta-state",new[]{(30L,0d,"empty"),(31,double.NaN,"empty"),(31,-1d,"empty"),(31,double.PositiveInfinity,"empty"),(31,double.NegativeInfinity,"empty"),(31,0d,"empty")});
RuntimeCase("default-empty-knowledge",new[]{(40L,0d,"empty")},defaultProvider:true);
RuntimeCase("knowledge-throws-after-one",new[]{(50L,0d,"throw3"),(50,0d,"empty")});RuntimeCase("only-player-ancient",new[]{(51L,0d,"empty")});RuntimeCase("duplicate-ai-id",new[]{(52L,0d,"empty")});RuntimeCase("explicit-reset-zero-retry",new[]{(53L,0d,"empty"),(53,0d,"reset"),(53,0d,"empty")});

var gdir=World(60);var directCalls=new List<object>();var direct=new CivilizationStrategicDirector(new CivilizationStrategicInputBuilder(new LogisticsStub()));
void Direct(string name,int id,long observed,long now,bool force=false){var before=Freeze(WorldState(gdir));object? result=null;Exception? error=null;var special=name=="foreign-knowledge-traits";var traits=special?new CivilizationTraits(.9,.8,.1,.2,.7,1.0):CivilizationTraits.Balanced;var known=special?new Dictionary<int,KnownCivilization>{{3,new(3,-.5,5,7,.8,now,true,.2,.1,true,false)}}:new Dictionary<int,KnownCivilization>();var knowledge=new KnowledgeSnapshot{ObservedAtTick=observed,Civilizations=known};CivilizationStrategicReview? typed=null;try{typed=direct.Review(gdir,id,traits,knowledge,now,force);}catch(Exception e){error=e;}result=typed is null?null:Review(typed);directCalls.Add(new{Name=name,Op="Review",Id=id,Observed=observed,Now=now,Force=force,Traits=traits,Knowledge=knowledge,Result=result,Error=error is null?null:new{Type=error.GetType().Name,error.Message},Before=before,After=Freeze(WorldState(gdir))});}
void Control(string name,string op,int id=0){var before=Freeze(WorldState(gdir));Exception? error=null;try{if(op=="Invalidate")direct.Invalidate(id);else if(op=="Remove")direct.RemoveCivilization(id);else if(op=="Clear")direct.Clear();else throw new InvalidOperationException("bad fixture op");}catch(Exception e){error=e;}directCalls.Add(new{Name=name,Op=op,Id=id,Observed=0L,Now=0L,Force=false,Traits=CivilizationTraits.Balanced,Knowledge=new KnowledgeSnapshot{ObservedAtTick=0,Civilizations=new Dictionary<int,KnownCivilization>()},Result=(object?)null,Error=error is null?null:new{Type=error.GetType().Name,error.Message},Before=before,After=Freeze(WorldState(gdir))});} Direct("valid",2,0,0);Direct("foreign-knowledge-traits",2,0,0,true);var economies=(List<CivilizationEconomyState>)gdir.Economies;var savedEconomy=economies[0];economies.RemoveAt(0);Direct("known-missing-economy",2,0,1,true);economies.Insert(0,savedEconomy);var technologies=(List<TechnologyState>)gdir.Technologies;var savedTechnology=technologies[0];technologies.RemoveAt(0);Direct("known-missing-technology",2,0,1,true);technologies.Insert(0,savedTechnology);Direct("cache-retry-after-builder-failures",2,0,1);((CivilizationEconomyState)gdir.Economies[0]).Industry=999;Direct("cached-own-fresh",2,0,1);Direct("forced",2,0,1,true);Direct("future-before-missing",99,2,1);Direct("missing",99,1,1);Control("invalidate","Invalidate",2);Direct("after-invalidate",2,1,1);Control("remove","Remove",2);Direct("after-remove",2,1,1);Control("clear","Clear");Direct("after-clear",2,1,1);cases.Add(new{Name="director-order-cache-controls",Commands=directCalls});

object Capture(Action a){try{a();return new{Type=(string?)null,Message=(string?)null};}catch(Exception e){return new{Type=e.GetType().Name,e.Message};}}
var sourceOnly=new[]{new{Name="null-galaxy",Observation=Capture(()=>new CivilizationStrategicRuntimeCoordinator().Advance(null!,0))},new{Name="extreme-double-max",Observation=Capture(()=>new CivilizationStrategicRuntimeCoordinator().Advance(World(70),double.MaxValue))}};
var commandCount=cases.Sum(x=>JsonSerializer.SerializeToElement(x).GetProperty("Commands").GetArrayLength());File.WriteAllText(args[0],JsonSerializer.Serialize(new{Format="stellar-strategic-runtime-oracle-v1",Culture="InvariantCulture",Cases=cases,CaseCount=cases.Count,SourceOnly=sourceOnly},options)+Environment.NewLine);Console.WriteLine($"strategic runtime oracle: {cases.Count} scenarios, {commandCount} commands, {sourceOnly.Length} source-only observations");

sealed class LogisticsStub:IEconomyLogisticsView{public CivilizationLogisticsSnapshot GetSnapshot(GalaxyState g,int id)=>new(id,0,0,0,0,.8,SupplyCondition.Healthy,Array.Empty<ColonyLogisticsSnapshot>());}
sealed class KnowledgeStub(List<string> calls,Func<string> mode):IStrategicKnowledgeProvider{public KnowledgeSnapshot Build(int id,long tick){calls.Add($"{id}:{tick}");if(mode()=="throw3"&&id==3)throw new InvalidOperationException("fixture knowledge failure");return new KnowledgeSnapshot{ObservedAtTick=mode()=="future3"&&id==3?tick+1:tick,Civilizations=new Dictionary<int,KnownCivilization>()};}}
