#include <stellar/core/adaptive_research_state.hpp>
#include <stellar/core/detail/adaptive_research_state_writer.hpp>
#include <nlohmann/json.hpp>
#include <cmath>
#include <fstream>
#include <functional>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <variant>

using Json=nlohmann::json;using namespace stellar::core;using Writer=detail::AdaptiveResearchStateWriter;
namespace {
void require(bool value,const std::string&message){if(!value)throw std::runtime_error(message);}
double number(const Json&v){if(v.is_number())return v.get<double>();auto s=v.get<std::string>();if(s=="NaN")return std::numeric_limits<double>::quiet_NaN();if(s=="Infinity")return std::numeric_limits<double>::infinity();if(s=="-Infinity")return -std::numeric_limits<double>::infinity();throw std::invalid_argument("bad number");}
Json encoded(double v){if(std::isnan(v))return "NaN";if(std::isinf(v))return v>0?Json("Infinity"):Json("-Infinity");return v;}
std::optional<std::string> optional_string(const Json&v){return v.is_null()?std::nullopt:std::optional(v.get<std::string>());}
ResearchNodeRuntimeState node(const Json&v){return{v.at("NodeId"),static_cast<ResearchMaturity>(v.at("Maturity").get<int>()),optional_string(v.at("Resolution")),number(v.at("StageResearchPoints")),number(v.at("TotalResearchPoints")),v.at("Revision")};}
ResearchEvidenceInstance evidence(const Json&v){return{v.at("EvidenceInstanceId"),v.at("EvidenceTypeId"),v.at("Provenance"),number(v.at("Quality")),number(v.at("Confidence")),optional_string(v.at("ContextId")),v.at("Revision")};}
ResearchCapabilityKey capability(const Json&v){return{v.at("CapabilityId"),optional_string(v.at("ContextId"))};}
ResearchProjectRuntimeState project(const Json&v){return{v.at("NodeId"),static_cast<ResearchMaturity>(v.at("Stage").get<int>()),optional_string(v.at("TargetApplicabilityContextId")),number(v.at("AssignedEffectiveLabs")),number(v.at("ReadinessEfficiency")),v.at("Paused"),optional_string(v.at("PauseReason")),number(v.at("StageResearchPoints")),number(v.at("TotalResearchPoints")),v.at("Revision")};}
Json node_json(const ResearchNodeRuntimeState&v){return{{"NodeId",v.node_id},{"Maturity",static_cast<int>(v.maturity)},{"Resolution",v.resolution},{"StageResearchPoints",encoded(v.stage_research_points)},{"TotalResearchPoints",encoded(v.total_research_points)},{"Revision",v.revision},{"CountsAsEstablishedKnowledge",v.counts_as_established_knowledge()}};}
Json evidence_json(const ResearchEvidenceInstance&v){return{{"EvidenceInstanceId",v.evidence_instance_id},{"EvidenceTypeId",v.evidence_type_id},{"Provenance",v.provenance},{"Quality",encoded(v.quality)},{"Confidence",encoded(v.confidence)},{"ContextId",v.context_id},{"Revision",v.revision}};}
Json capability_json(const ResearchCapabilityKey&v){return{{"CapabilityId",v.capability_id},{"ContextId",v.context_id}};}
Json project_json(const ResearchProjectRuntimeState&v){return{{"NodeId",v.node_id},{"Stage",static_cast<int>(v.stage)},{"TargetApplicabilityContextId",v.target_applicability_context_id},{"AssignedEffectiveLabs",encoded(v.assigned_effective_labs)},{"ReadinessEfficiency",encoded(v.readiness_efficiency)},{"Paused",v.paused},{"PauseReason",v.pause_reason},{"StageResearchPoints",encoded(v.stage_research_points)},{"TotalResearchPoints",encoded(v.total_research_points)},{"Revision",v.revision}};}
Json snapshot(const AdaptiveResearchCivilizationState&s){Json nodes=Json::array();for(auto&v:s.node_states())nodes.push_back(node_json(v));Json pressures=Json::array();for(auto&v:s.pressures())pressures.push_back({{"Id",v.pressure_id},{"Value",encoded(v.value)}});Json evidences=Json::array();for(auto&v:s.evidence_instances())evidences.push_back(evidence_json(v));Json traits=s.civilization_traits();Json capabilities=Json::array();for(auto&v:s.capabilities())capabilities.push_back(capability_json(v));Json facilities=s.facility_capabilities(),deployments=s.enabled_deployment_event_ids();Json contexts=Json::array();for(auto&v:s.applicability_contexts())contexts.push_back({{"ContextId",v.context_id},{"Traits",v.sorted_traits}});Json projects=Json::array();for(auto&v:s.active_projects())projects.push_back(project_json(v));return{{"CivilizationId",s.civilization_id()},{"Revision",s.revision()},{"MaterializedViewRevision",s.materialized_view_revision()},{"DirectedProgramStageId",s.directed_program_stage_id()},{"TotalEffectiveResearchLabs",encoded(s.total_effective_research_labs())},{"AssignedEffectiveLabs",encoded(s.assigned_effective_labs())},{"FreeEffectiveLabs",encoded(s.free_effective_labs())},{"NodeStates",nodes},{"Pressures",pressures},{"EvidenceInstances",evidences},{"CivilizationTraits",traits},{"Capabilities",capabilities},{"FacilityCapabilities",facilities},{"EnabledDeploymentEventIds",deployments},{"ApplicabilityContexts",contexts},{"ActiveProjects",projects}};}
void equal(const Json&a,const Json&b,const std::string&where){if(a.is_number()&&b.is_number()){if(a.is_number_integer()&&b.is_number_integer())require(a.get<std::int64_t>()==b.get<std::int64_t>(),where+" integer");else{const double x=a.get<double>(),y=b.get<double>(),scale=std::max({1.0,std::abs(x),std::abs(y)});require(std::abs(x-y)<=1e-12*scale,where+" number");}return;}if(a.type()!=b.type())throw std::runtime_error(where+" type");if(a.is_array()){require(a.size()==b.size(),where+" size");for(std::size_t i=0;i<a.size();++i)equal(a[i],b[i],where+"["+std::to_string(i)+"]");return;}if(a.is_object()){require(a.size()==b.size(),where+" keys");for(auto&[k,v]:b.items()){require(a.contains(k),where+" missing "+k);equal(a.at(k),v,where+"."+k);}return;}require(a==b,where+" value");}
struct Error{std::string type,message;};template<class F>std::optional<Error>capture(F&&f){try{f();return{};}catch(const std::out_of_range&e){return Error{"ArgumentOutOfRangeException",e.what()};}catch(const std::invalid_argument&e){return Error{"ArgumentException",e.what()};}catch(const std::overflow_error&e){return Error{"InvalidOperationException",e.what()};}catch(const std::exception&e){return Error{"Exception",e.what()};}}
void check_error(const std::optional<Error>&actual,const Json&expected,const std::string&where){require(actual.has_value()==!expected.is_null(),where+" error presence");if(actual){require(actual->type==expected.at("Type").get<std::string>()&&actual->message==expected.at("Message").get<std::string>(),where+" error differs");}}
void run(const Json&row,AdaptiveResearchCivilizationState&s){equal(snapshot(s),row.at("Before"),row.at("Op").get<std::string>()+" before");const auto op=row.at("Op").get<std::string>();const Json input=row.at("Input");using Result=std::variant<std::monostate,bool,double,std::span<const std::string>>;Result result;std::function<void()>invoke;
if(op=="SetLabs"){double v=number(input.at("Value"));invoke=[&s,v]{Writer::set_total_effective_research_labs(s,v);};}
else if(op=="SetPressure"){auto id=input.at("PressureId").get<std::string>();double v=number(input.at("Value"));invoke=[&s,id=std::move(id),v,&result]{result=Writer::set_pressure(s,id,v);};}
else if(op=="AddEvidence"){auto v=evidence(input);invoke=[&s,v=std::move(v),&result]{result=Writer::add_evidence(s,v);};}
else if(op=="RemoveEvidence"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=Writer::remove_evidence(s,id);};}
else if(op=="HasEvidence"){auto type=input.at("Type").get<std::string>();auto context=optional_string(input.at("Context"));invoke=[&s,type=std::move(type),context=std::move(context),&result]{result=s.has_evidence_type(type,context);};}
else if(op=="AddTrait"||op=="RemoveTrait"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),op,&result]{result=op=="AddTrait"?Writer::add_civilization_trait(s,id):Writer::remove_civilization_trait(s,id);};}
else if(op=="SetContext"){auto c=input.at("Context").get<std::string>();auto ids=input.at("Traits").get<std::vector<std::string>>();invoke=[&s,c=std::move(c),ids=std::move(ids),&result]{result=Writer::set_applicability_context_traits(s,c,ids);};}
else if(op=="AddContextTrait"||op=="RemoveContextTrait"){auto c=input.at("Context").get<std::string>(),t=input.at("Trait").get<std::string>();invoke=[&s,c=std::move(c),t=std::move(t),op,&result]{result=op=="AddContextTrait"?Writer::add_applicability_trait(s,c,t):Writer::remove_applicability_trait(s,c,t);};}
else if(op=="AddCapability"||op=="RemoveCapability"){auto v=capability(input);invoke=[&s,v=std::move(v),op,&result]{result=op=="AddCapability"?Writer::add_capability(s,v):Writer::remove_capability(s,v);};}
else if(op=="AddFacility"||op=="RemoveFacility"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),op,&result]{result=op=="AddFacility"?Writer::add_facility_capability(s,id):Writer::remove_facility_capability(s,id);};}
else if(op=="AddDeployment"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=Writer::add_enabled_deployment_event(s,id);};}
else if(op=="SetStage"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id)]{Writer::set_directed_program_stage(s,id);};}
else if(op=="SetNode"){auto v=node(input);invoke=[&s,v=std::move(v)]{Writer::set_node_state(s,v);};}
else if(op=="RemoveNode"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=Writer::remove_node_state(s,id);};}
else if(op=="Established"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=s.has_established_knowledge(id);};}
else if(op=="GetPressure"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=s.get_pressure(id);};}
else if(op=="HasTrait"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=s.has_trait(id);};}
else if(op=="HasApplicabilityTrait"){auto c=input.at("Context").get<std::string>(),t=input.at("Trait").get<std::string>();invoke=[&s,c=std::move(c),t=std::move(t),&result]{result=s.has_applicability_trait(c,t);};}
else if(op=="GetApplicabilityTraits"){auto c=input.at("Context").get<std::string>();invoke=[&s,c=std::move(c),&result]{result=s.get_applicability_traits(c);};}
else if(op=="HasFacility"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=s.has_facility_capability(id);};}
else if(op=="HasCapability"){auto id=input.at("Id").get<std::string>();auto context=optional_string(input.at("Context"));invoke=[&s,id=std::move(id),context=std::move(context),&result]{result=s.has_capability(id,context);};}
else if(op=="HasDeployment"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=s.is_deployment_event_enabled(id);};}
else if(op=="SetProject"){auto v=project(input);invoke=[&s,v=std::move(v)]{Writer::set_project(s,v);};}
else if(op=="RemoveProject"){auto id=input.at("Id").get<std::string>();invoke=[&s,id=std::move(id),&result]{result=Writer::remove_project(s,id);};}
else if(op=="MarkViewDirty")invoke=[&s]{Writer::mark_view_dirty(s);};else throw std::invalid_argument("bad fixture op");auto error=capture([&]{invoke();});Json actual=std::visit([](const auto&value)->Json{using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,std::monostate>)return nullptr;else if constexpr(std::is_same_v<T,double>)return encoded(value);else if constexpr(std::is_same_v<T,std::span<const std::string>>)return std::vector<std::string>(value.begin(),value.end());else return value;},result);equal(actual,row.at("Result"),op+" result");check_error(error,row.at("Error"),op);equal(snapshot(s),row.at("After"),op+" after");}
}
int main(int argc,char**argv){try{require(argc==2,"usage");std::ifstream stream(argv[1]);Json root;stream>>root;require(root.at("Schema")=="stellar-adaptive-research-state-v1","schema");AdaptiveResearchCivilizationState state("civ:alpha","directed:initial");for(const auto&row:root.at("Commands"))run(row,state);
for(const auto&row:root.at("ConstructorCases")){const auto civ=row.at("Input").at("CivilizationId").get<std::string>(),stage=row.at("Input").at("StageId").get<std::string>();std::optional<AdaptiveResearchCivilizationState>made;auto error=capture([&]{made.emplace(civ,stage);});check_error(error,row.at("Error"),"constructor");}
auto copy=state;auto original=snapshot(state);Writer::add_civilization_trait(copy,"copy-only");require(snapshot(state)==original&&!copy.has_civilization_trait("missing")&&copy.has_civilization_trait("copy-only"),"copy independence");auto moved=std::move(copy);Writer::add_facility_capability(moved,"move-only");require(moved.has_facility_capability("move-only"),"move ownership");
require(detail::checked_next_research_state_revision(std::numeric_limits<std::int64_t>::max()-1)==std::numeric_limits<std::int64_t>::max(),"revision final value");auto boundary=capture([]{(void)detail::checked_next_research_state_revision(std::numeric_limits<std::int64_t>::max());});require(boundary&&boundary->type=="InvalidOperationException"&&boundary->message=="Adaptive Research state revision space is exhausted.","revision boundary");
std::cout<<"research state parity: "<<root.at("Commands").size()<<" operations, "<<root.at("ConstructorCases").size()<<" constructor cases; copy/move ownership and native revision boundary passed\n";return 0;}catch(const std::exception&e){std::cerr<<"research state parity failure: "<<e.what()<<"\n";return 1;}}
