#include <stellar/core/logistics.hpp>
#include <nlohmann/json.hpp>
#include <cmath>
#include <fstream>
#include <iostream>
#include <stdexcept>
using Json=nlohmann::json; using namespace stellar::core;
namespace {
constexpr double tolerance=1e-12;
void check(bool ok,const std::string& text) { if(!ok) throw std::runtime_error(text); }
void equal(const Json& a,const Json& e,const std::string& path) {
 if(a.is_number()&&e.is_number()) { if(a.is_number_integer()&&e.is_number_integer()) {check(a==e,path);return;} auto x=a.get<double>(),y=e.get<double>(); check(std::abs(x-y)<=tolerance*std::max(1.,std::abs(y)),path+": expected "+e.dump()+", got "+a.dump());return; }
 if(a.is_array()&&e.is_array()) {check(a.size()==e.size(),path+": size");for(size_t i=0;i<a.size();++i)equal(a[i],e[i],path+"["+std::to_string(i)+"]");return;}
 if(a.is_object()&&e.is_object()) {check(a.size()==e.size(),path+": fields");for(const auto& [k,v]:e.items()){check(a.contains(k),path+": missing "+k);equal(a.at(k),v,path+"."+k);}return;}
 check(a==e,path+": expected "+e.dump()+", got "+a.dump());
}
struct Input {std::vector<Civilization> civs;std::vector<Colony> colonies;std::vector<CivilizationEconomy> economies;std::vector<EconomyConstructionState> construction;
 EconomyWorldView world() const{return {civs,{},construction,{}};}};
Input input(const Json& value) { Input out; auto& w=value.at("World"); for(auto& x:w.at("Civilizations")){ Civilization c;c.id=x.at("Id");c.name=x.at("Name");c.home_system_id=x.at("HomeSystemId");c.archetype=x.at("Archetype");auto&t=x.at("Traits");c.traits={t.at("Aggression"),t.at("Territoriality"),t.at("Greed"),t.at("ScientificCuriosity"),t.at("RiskTolerance"),t.at("SurvivalPriority"),t.at("HonorBound")};c.is_player=x.at("IsPlayer");c.development_stage=x.at("DevelopmentStage");c.is_seeded_ancient=x.at("IsSeededAncient");c.expansion_allowed=x.at("ExpansionAllowed");c.neutral_unless_provoked=x.at("NeutralUnlessProvoked");c.species_id=x.at("SpeciesId");out.civs.push_back(c);}
 for(auto&x:w.at("Colonies")){Colony c;c.id=x.at("Id");c.civilization_id=x.at("CivilizationId");c.system_id=x.at("SystemId");if(!x.at("PlanetaryBodyId").is_null())c.planetary_body_id=x.at("PlanetaryBodyId");c.name=x.at("Name");c.kind=x.at("Kind");c.population_species_id=x.at("PopulationSpeciesId");c.population_millions=x.at("PopulationMillions");c.infrastructure=x.at("Infrastructure");c.stability=x.at("Stability");out.colonies.push_back(c);}
 for(auto&x:w.at("Economies")){CivilizationEconomy e;e.civilization_id=x.at("CivilizationId");e.credits=x.at("Credits");e.industry=x.at("Industry");e.science=x.at("Science");e.last_credits_per_second=x.at("LastCreditsPerSecond");e.last_industry_per_second=x.at("LastIndustryPerSecond");e.last_science_per_second=x.at("LastSciencePerSecond");e.last_research_spending_per_day=x.at("LastResearchSpendingPerDay");e.last_research_funding_fraction=x.at("LastResearchFundingFraction");e.operating_arrears=x.at("OperatingArrears");e.last_base_operations_funding_fraction=x.at("LastBaseOperationsFundingFraction");out.economies.push_back(e);}
 for(auto&x:w.at("ConstructionStates")){EconomyConstructionState c;c.civilization_id=x.at("CivilizationId");c.completed_project_ids=x.at("CompletedProjectIds").get<std::vector<std::string>>();out.construction.push_back(c);}return out;}
void unchanged(const Input& before,const Input& after,const std::string& name) {
 check(before.civs.size()==after.civs.size()&&before.colonies.size()==after.colonies.size()&&before.economies.size()==after.economies.size()&&before.construction.size()==after.construction.size(),name+": native input collection mutated");
 for(size_t i=0;i<before.colonies.size();++i) { const auto&a=before.colonies[i],&b=after.colonies[i]; check(a.id==b.id&&a.civilization_id==b.civilization_id&&a.system_id==b.system_id&&a.planetary_body_id==b.planetary_body_id&&a.name==b.name&&a.kind==b.kind&&a.population_species_id==b.population_species_id&&a.population_millions==b.population_millions&&a.infrastructure==b.infrastructure&&a.stability==b.stability,a.name+": colony mutated"); }
 for(size_t i=0;i<before.economies.size();++i) { const auto&a=before.economies[i],&b=after.economies[i]; check(a.civilization_id==b.civilization_id&&a.credits==b.credits&&a.industry==b.industry&&a.science==b.science&&a.last_credits_per_second==b.last_credits_per_second&&a.last_industry_per_second==b.last_industry_per_second&&a.last_science_per_second==b.last_science_per_second&&a.last_research_spending_per_day==b.last_research_spending_per_day&&a.last_research_funding_fraction==b.last_research_funding_fraction&&a.operating_arrears==b.operating_arrears&&a.last_base_operations_funding_fraction==b.last_base_operations_funding_fraction&&a.industry_priority==b.industry_priority,name+": economy mutated"); }
 for(size_t i=0;i<before.construction.size();++i) check(before.construction[i].civilization_id==after.construction[i].civilization_id&&before.construction[i].completed_project_ids==after.construction[i].completed_project_ids,name+": construction mutated");
}
Json colony(const ColonyLogisticsSnapshot& x){return {{"ColonyId",x.colony_id},{"SystemId",x.system_id},{"SupportDemandPerDay",x.support_demand_per_day},{"LocalSupportCapacityPerDay",x.local_support_capacity_per_day},{"ImportedSupportRequiredPerDay",x.imported_support_required_per_day},{"CoverageRatio",x.coverage_ratio},{"Condition",x.condition}};}
Json logistics(const CivilizationLogisticsSnapshot& x){Json cs=Json::array();for(auto&i:x.colonies)cs.push_back(colony(i));return {{"CivilizationId",x.civilization_id},{"TotalSupportDemandPerDay",x.total_support_demand_per_day},{"TotalLocalSupportCapacityPerDay",x.total_local_support_capacity_per_day},{"ImportRequirementPerDay",x.import_requirement_per_day},{"CargoHandlingCapacityPerDay",x.cargo_handling_capacity_per_day},{"EffectiveCoverageRatio",x.effective_coverage_ratio},{"Condition",x.condition},{"Colonies",cs},{"CriticalColonyCount",x.critical_colony_count},{"StrainedColonyCount",x.strained_colony_count}};}
Json node(const LogisticsNode& x){return{{"Id",x.id},{"CivilizationId",x.civilization_id},{"SystemId",x.system_id},{"Name",x.name},{"Kind",x.kind}};} Json link(const LogisticsLink& x){return{{"Id",x.id},{"CivilizationId",x.civilization_id},{"FromNodeId",x.from_node_id},{"ToNodeId",x.to_node_id},{"CapacityPerDay",x.capacity_per_day},{"TransitDays",x.transit_days},{"Bidirectional",x.bidirectional},{"Enabled",x.enabled}};}
Json flow(const LogisticsFlowPlan& x){Json a=Json::array(),u=Json::object(),s=Json::object();for(auto&i:x.allocations)a.push_back({{"SourceNodeId",i.source_node_id},{"DestinationNodeId",i.destination_node_id},{"AllocatedPerDay",i.allocated_per_day},{"TransitDays",i.transit_days},{"RouteLinkIds",i.route_link_ids}});for(auto&i:x.unmet_demand_per_day)u[std::to_string(i.node_id)]=i.per_day;for(auto&i:x.unused_supply_per_day)s[std::to_string(i.node_id)]=i.per_day;return{{"Allocations",a},{"UnmetDemandPerDay",u},{"UnusedSupplyPerDay",s},{"TotalAllocatedPerDay",x.total_allocated_per_day},{"TotalUnmetDemandPerDay",x.total_unmet_demand_per_day}};}
Json home(const HomeSystemLogisticsNetwork& x){Json n=Json::array(),l=Json::array(),o=Json::array(),d=Json::array();for(auto&i:x.nodes)n.push_back(node(i));for(auto&i:x.links)l.push_back(link(i));for(auto&i:x.supply_offers)o.push_back({{"NodeId",i.node_id},{"AvailablePerDay",i.available_per_day}});for(auto&i:x.demands)d.push_back({{"NodeId",i.node_id},{"RequiredPerDay",i.required_per_day},{"Priority",i.priority}});return{{"CivilizationId",x.civilization_id},{"HomeSystemId",x.home_system_id},{"Nodes",n},{"Links",l},{"SupplyOffers",o},{"Demands",d},{"DailyFlow",flow(x.daily_flow)},{"TotalDemandPerDay",x.total_demand_per_day},{"TotalSupplyOfferedPerDay",x.total_supply_offered_per_day},{"TotalAllocatedPerDay",x.total_allocated_per_day},{"TotalUnmetDemandPerDay",x.total_unmet_demand_per_day}};}
Json coverage(const CivilizationLogisticsCoverage& x){Json e=Json::array();for(auto&i:x.external_systems)e.push_back({{"CivilizationId",i.civilization_id},{"SystemId",i.system_id},{"ColonyCount",i.colony_count},{"SupportDemandPerDay",i.support_demand_per_day},{"LocalSupportCapacityPerDay",i.local_support_capacity_per_day},{"ImportRequirementPerDay",i.import_requirement_per_day},{"LocalSurplusPerDay",i.local_surplus_per_day},{"Condition",i.condition},{"HasRepresentedInterstellarFreightCorridor",i.has_represented_interstellar_freight_corridor}});return{{"CivilizationId",x.civilization_id},{"HomeSystem",home(x.home_system)},{"ExternalSystems",e},{"OwnedSystemCount",x.owned_system_count},{"ExternalSystemCount",x.external_system_count},{"ExternalImportRequirementPerDay",x.external_import_requirement_per_day},{"ExternalLocalSurplusPerDay",x.external_local_surplus_per_day},{"UnrepresentedInterstellarSupportPerDay",x.unrepresented_interstellar_support_per_day},{"HasUnrepresentedInterstellarSupportGap",x.has_unrepresented_interstellar_support_gap}};}
}
int main(int argc,char**argv){try{
 check(argc==2,"Expected logistics views fixture"); std::ifstream f(argv[1]); Json fixture; f>>fixture; check(fixture.at("Format")=="stellar-logistics-views-oracle-v1","format");
 for(auto& test:fixture.at("Cases")) {
  const auto name=test.at("Name").get<std::string>(); auto state=input(test); const auto before=state; const auto id=test.at("Arguments").at("CivilizationId").get<int>();
  std::optional<CivilizationLogisticsSnapshot> l; std::optional<HomeSystemLogisticsNetwork> h; std::optional<CivilizationLogisticsCoverage> c; std::string error;
  try { auto world=state.world(); l=economy_logistics(world,state.colonies,state.economies,id); h=home_system_logistics(world,state.colonies,state.economies,id); c=civilization_logistics_coverage(world,state.colonies,state.economies,id); }
  catch(const std::exception& exception) { error=exception.what(); }
  unchanged(before,state,name);
  if(test.contains("ExpectedError")) { check(!error.empty(),name+": expected native error"); check(error==test.at("ExpectedError").get<std::string>(),name+": wrong native error: "+error); continue; }
  if(test.contains("ExpectedErrorCategory")) { check(!error.empty(),name+": expected native error"); const auto category=test.at("ExpectedErrorCategory").get<std::string>(); check(error.find(category)!=std::string::npos,name+": wrong native error category: "+error); continue; }
  check(error.empty(),name+": unexpected native error: "+error);
  equal(logistics(*l),test.at("ExpectedLogistics"),name+" logistics"); equal(home(*h),test.at("ExpectedHome"),name+" home"); equal(coverage(*c),test.at("ExpectedCoverage"),name+" coverage");
 }
 std::cout<<"logistics views parity passed\n";
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
