#include "native_planet_disc_assets.hpp"
#include "native_planet_surface_assets.hpp"

#include <stellar/engine/native_image_preparation.hpp>

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <numbers>
#include <source_location>
#include <stdexcept>
#include <string>
#include <thread>

namespace fs=std::filesystem;
using namespace stellar::native_system;
using namespace stellar::native_system_ui;

namespace {
void require(bool value,std::string message,const std::source_location where=std::source_location::current()){if(!value)throw std::runtime_error(std::move(message)+" at "+where.file_name()+":"+std::to_string(where.line()));}
template<class Predicate>void wait_for(Predicate &&predicate,std::string message){const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(15);while(!predicate()){if(std::chrono::steady_clock::now()>=deadline)throw std::runtime_error(std::move(message));std::this_thread::yield();}}
class WorkerGate final {
public:
  struct State {std::atomic<bool> started{},released{};};
  WorkerGate():state_(std::make_shared<State>()){}
  ~WorkerGate(){release();}
  [[nodiscard]]std::shared_ptr<State> state()const{return state_;}
  void release()const noexcept{state_->released=true;}
  void wait_started()const{wait_for([state=state_]{return state->started.load();},"background worker did not reach its test gate");}
private:std::shared_ptr<State> state_;
};
class FixtureDirectory final {
public:
  explicit FixtureDirectory(const fs::path &source){const auto seed=std::chrono::high_resolution_clock::now().time_since_epoch().count();for(int attempt=0;attempt<100;++attempt){path_=fs::temp_directory_path()/(L"stellar-planet-discs-"+std::to_wstring(seed)+L"-"+std::to_wstring(attempt));if(fs::create_directory(path_))break;}if(path_.empty()||!fs::exists(path_))throw std::runtime_error("Could not create isolated planet-disc fixtures.");for(const auto& asset:planet_surface_assets)fs::copy_file(source/asset.filename,path_/asset.filename);}
  ~FixtureDirectory(){std::error_code ignored;for(const auto& asset:planet_surface_assets)fs::remove(path_/asset.filename,ignored);fs::remove(path_,ignored);}
  [[nodiscard]]const fs::path&path()const noexcept{return path_;}
private:fs::path path_;
};
std::array<unsigned,4> pixel(const stellar::native_map::RgbaImage &image,int x,int y){const auto index=(static_cast<std::size_t>(y)*image.width()+static_cast<std::size_t>(x))*4u;const auto &p=image.pixels();return {p[index],p[index+1],p[index+2],p[index+3]};}
SystemBodyAppearance appearance(std::uint64_t generation,int body,NativeSystemBodyVisualClass visual,std::optional<std::string> key={},float light=0){return {generation,body,true,visual,std::move(key),static_cast<std::uint32_t>(body*7919),light};}
std::shared_ptr<const stellar::native_map::RgbaImage> await_prepared(NativePlanetDiscAssets &assets,const SystemBodyAppearance &value){const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(15);for(;;){if(auto image=assets.request_image(value))return image;if(std::chrono::steady_clock::now()>=deadline)throw std::runtime_error("background planet preparation did not complete");std::this_thread::yield();}}
void write_capture(const fs::path&directory,std::ofstream&profile,std::string_view name,const stellar::native_map::RgbaImage&image,std::size_t decoded,std::size_t generated,const std::chrono::steady_clock::duration elapsed){const auto raw=directory/(std::string(name)+".rgba");std::ofstream output(raw,std::ios::binary|std::ios::trunc);if(!output)throw std::runtime_error("Could not open planet capture "+raw.string());const auto&pixels=image.pixels();output.write(reinterpret_cast<const char*>(pixels.data()),static_cast<std::streamsize>(pixels.size()));if(!output)throw std::runtime_error("Could not write planet capture "+raw.string());const auto milliseconds=std::chrono::duration<double,std::milli>(elapsed).count();profile<<name<<" width="<<image.width()<<" height="<<image.height()<<" bytes="<<pixels.size()<<" source_decodes="<<decoded<<" generated_discs="<<generated<<" cold_ms="<<milliseconds<<'\n';std::cout<<"planet capture "<<name<<" "<<image.width()<<'x'<<image.height()<<" decodes="<<decoded<<" generated="<<generated<<" cold_ms="<<milliseconds<<'\n';}
}

int main(int argc,char **argv)try{
  const bool capture=argc==4&&std::string_view(argv[1])=="--capture";require(argc==2||capture,"Usage: native_planet_disc_assets_tests [--capture <directory>] <Sol asset root>");const auto source=fs::absolute(capture?argv[3]:argv[1]);FixtureDirectory fixtures(source);NativePlanetDiscAssets assets(fixtures.path());std::ofstream profile;if(capture){fs::create_directories(fs::absolute(argv[2]));profile.open(fs::absolute(argv[2])/"planet-profile.log",std::ios::trunc);if(!profile)throw std::runtime_error("Could not open planet capture profile");profile<<"native planet-disc cold resource capture\n";}
  auto mercury=appearance(1,101,NativeSystemBodyVisualClass::rocky,"mercury",0);const auto mercury_started=std::chrono::steady_clock::now();const auto mercury_disc=assets.image(mercury);if(capture)write_capture(fs::absolute(argv[2]),profile,"planet_mercury",*mercury_disc,assets.source_decode_count(),assets.generated_disc_count(),std::chrono::steady_clock::now()-mercury_started);require(mercury_disc&&mercury_disc->width()==source_planet_disc_resolution&&mercury_disc->height()==source_planet_disc_resolution&&mercury_disc->byte_size()==source_planet_disc_bytes,"Mercury did not use the approved high-resolution source disc");require(pixel(*mercury_disc,0,0)[3]==0,"planet disc corner was not transparent");bool antialiased{},matte{};for(std::size_t i=0;i<mercury_disc->pixels().size();i+=4){const auto alpha=mercury_disc->pixels()[i+3];if(alpha>0&&alpha<255){antialiased=true;if(static_cast<unsigned>(mercury_disc->pixels()[i])+mercury_disc->pixels()[i+1]+mercury_disc->pixels()[i+2]>20)matte=true;}}require(antialiased,"planet limb has no antialiased coverage");require(matte,"antialiased photo limb sampled only a dark matte");
  const auto decode_after_mercury=assets.source_decode_count(),generated_after_mercury=assets.generated_disc_count();for(int frame=0;frame<20;++frame)require(assets.image(mercury)==mercury_disc,"camera-only frame rebuilt the cached Mercury disc");require(assets.source_decode_count()==decode_after_mercury&&assets.generated_disc_count()==generated_after_mercury,"camera-only frames decoded or generated a disc");
  // The isolated fixture deliberately has no legacy mars.jpg/jupiter.jpg.
  // Both synchronous portraits and worker-generated system discs must resolve
  // the same full map consumed by the planetary screen.
  for(const auto key:{"mercury","venus","earth","moon","mars","jupiter","saturn","uranus","neptune"}){
    const auto index=*planet_surface_asset_index(key,0);const auto name=planet_surface_assets[index].filename;

    const auto original=stellar::native_map::decode_rgba_image(source/name);
    NativePlanetDiscAssets authored(fixtures.path()),worker(fixtures.path());
    worker.use_background_preparation(std::make_shared<stellar::native_map::ImagePreparationQueue>());
    auto body=appearance(1,901,NativeSystemBodyVisualClass::rocky,key,0.f);
    const auto disc=authored.image(body);const auto async=await_prepared(worker,body);
    require(disc->pixels()==async->pixels(),"Authored system/portrait worker pixels diverged");
    const auto center=pixel(*disc,256,256),texel=pixel(*original,original->width()/2,original->height()/2);
    if(std::string_view(key)!="earth")for(int c=0;c<3;++c)require(std::abs(static_cast<float>(center[c])-.6815f*texel[c])<26.f,"Disc centre did not preserve authored map colour/orientation");
    body.lighting_longitude=std::numbers::pi_v<float>;
    require(disc->pixels()!=authored.image(body)->pixels(),"Authored map ignored independent star lighting");
    if(capture)write_capture(fs::absolute(argv[2]),profile,std::string("planet_authored_")+key,*disc,authored.source_decode_count(),authored.generated_disc_count(),{});

  }
  auto mercury_other_light=mercury;mercury_other_light.lighting_longitude=2.2f;
  require(assets.image(mercury_other_light)->pixels()!=mercury_disc->pixels(),"Mercury's new surface ignored independent lighting");
  auto neptune=appearance(1,102,NativeSystemBodyVisualClass::ice_giant,"neptune",0);const auto neptune_started=std::chrono::steady_clock::now();const auto neptune_day=assets.image(neptune);if(capture)write_capture(fs::absolute(argv[2]),profile,"planet_neptune_day",*neptune_day,assets.source_decode_count(),assets.generated_disc_count(),std::chrono::steady_clock::now()-neptune_started);neptune.lighting_longitude=std::numbers::pi_v<float>;const auto neptune_night=assets.image(neptune);require(neptune_day->pixels()!=neptune_night->pixels(),"equirectangular Neptune map ignored star-directed lighting");require(neptune_day->pixels()!=mercury_disc->pixels(),"Neptune and Mercury asset mappings collapsed to one disc");
  auto unknown=appearance(1,103,NativeSystemBodyVisualClass::unknown_planet);require(!assets.image(unknown),"unknown body received a generated surface");unknown.texture_key="mercury";bool unknown_spoof_rejected{};try{(void)assets.image(unknown);}catch(const std::invalid_argument&){unknown_spoof_rejected=true;}require(unknown_spoof_rejected,"unknown body accepted a spoofed Sol texture key");auto partial=mercury;partial.body_id=104;partial.fully_surveyed=false;bool partial_spoof_rejected{};try{(void)assets.image(partial);}catch(const std::invalid_argument&){partial_spoof_rejected=true;}require(partial_spoof_rejected,"non-full survey accepted a Sol texture key");
  partial.texture_key.reset();bool known_recon_rejected{};try{(void)assets.image(partial);}catch(const std::invalid_argument&){known_recon_rejected=true;}require(known_recon_rejected,"non-full survey disclosed a known class fallback without a texture key");auto unapproved=mercury;unapproved.body_id=105;unapproved.texture_key="pluto";bool unapproved_rejected{};try{(void)assets.image(unapproved);}catch(const std::invalid_argument&){unapproved_rejected=true;}require(unapproved_rejected,"unapproved Sol key reached path resolution");
  auto preparation=std::make_shared<stellar::native_map::ImagePreparationQueue>();NativePlanetDiscAssets background(fixtures.path());background.use_background_preparation(preparation);require(!background.request_image(mercury)&&background.pending_count()==1,"background Mercury request was not deferred");require(!background.request_image(mercury)&&background.pending_count()==1,"duplicate background Mercury request admitted another job");const auto prepared_mercury=await_prepared(background,mercury);require(prepared_mercury->pixels()==mercury_disc->pixels(),"background Mercury pixels differ from synchronous generation");auto background_neptune=appearance(1,302,NativeSystemBodyVisualClass::ice_giant,"neptune",0);const auto prepared_neptune=await_prepared(background,background_neptune);require(prepared_neptune->pixels()==neptune_day->pixels(),"background Neptune pixels differ from synchronous generation");auto fallback=appearance(1,303,NativeSystemBodyVisualClass::oceanic);const auto synchronous_fallback=assets.image(fallback),prepared_fallback=await_prepared(background,fallback);require(synchronous_fallback->width()==procedural_planet_disc_resolution&&synchronous_fallback->height()==procedural_planet_disc_resolution&&synchronous_fallback->byte_size()==procedural_planet_disc_bytes,"procedural planet did not use the bounded native resolution");require(pixel(*synchronous_fallback,0,0)[3]==0,"procedural planet disc corner was not transparent");require(prepared_fallback->pixels()==synchronous_fallback->pixels(),"background fallback pixels differ from synchronous generation");
  const auto jobs_before_unknown=preparation->outstanding_jobs();auto background_unknown=appearance(1,304,NativeSystemBodyVisualClass::unknown_planet);require(!background.request_image(background_unknown)&&background.pending_count()==0&&preparation->outstanding_jobs()==jobs_before_unknown,"unknown body admitted background work");auto background_next=appearance(2,305,NativeSystemBodyVisualClass::rocky);require(!background.request_image(background_next),"new generation did not defer preparation");const auto jobs_before_stale=preparation->outstanding_jobs();bool background_stale_rejected{};try{(void)background.request_image(appearance(1,306,NativeSystemBodyVisualClass::rocky));}catch(const std::invalid_argument&){background_stale_rejected=true;}require(background_stale_rejected&&preparation->outstanding_jobs()==jobs_before_stale,"stale generation admitted background work");background.discard_campaign();require(background.pending_count()==0&&background.cache_entries()==0,"discard retained pending background discs");const auto fresh_background=appearance(3,307,NativeSystemBodyVisualClass::oceanic);require(await_prepared(background,fresh_background)&&background.cache_entries()==1,"cancelled generation repopulated or prevented fresh background resources");
  auto saturated=std::make_shared<stellar::native_map::ImagePreparationQueue>(1,source_planet_disc_bytes);WorkerGate blocker_gate;auto blocker_state=blocker_gate.state();auto blocker_request=saturated->submit(source_planet_disc_bytes,[blocker_state]{blocker_state->started=true;while(!blocker_state->released.load())std::this_thread::yield();return stellar::native_map::RgbaImage::create(1,1,{0,0,0,0});});require(blocker_request.has_value(),"preparation barrier was not admitted");auto blocker=std::move(*blocker_request);blocker_gate.wait_started();NativePlanetDiscAssets saturated_assets(fixtures.path());saturated_assets.use_background_preparation(saturated);require(!saturated_assets.request_image(mercury)&&saturated_assets.pending_count()==0,"source-disc queue reservation did not reflect the output size");blocker_gate.release();wait_for([&]{return blocker.ready();},"preparation barrier did not complete");blocker.cancel();require(!saturated_assets.request_image(mercury)&&saturated_assets.pending_count()==1&&saturated->reserved_bytes()==source_planet_disc_bytes,"planet request did not reserve its actual output size after capacity was released");require(static_cast<bool>(await_prepared(saturated_assets,mercury)),"retried saturated planet request did not complete");
  auto draining=std::make_shared<stellar::native_map::ImagePreparationQueue>(2,2u*procedural_planet_disc_bytes);WorkerGate first_gate,tail_gate;auto first_state=first_gate.state();auto first_request=draining->submit(procedural_planet_disc_bytes,[first_state]{first_state->started=true;while(!first_state->released.load())std::this_thread::yield();return stellar::native_map::RgbaImage::create(1,1,{0,0,0,0});});require(first_request.has_value(),"first drain barrier was not admitted");auto first=std::move(*first_request);first_gate.wait_started();NativePlanetDiscAssets draining_assets(fixtures.path());draining_assets.use_background_preparation(draining);const auto old_background=appearance(1,401,NativeSystemBodyVisualClass::oceanic);require(!draining_assets.request_image(old_background)&&draining_assets.pending_count()==1,"old background request was not queued");first_gate.release();wait_for([&]{return first.ready();},"first drain barrier did not complete");first.cancel();auto tail_state=tail_gate.state();auto tail_request=draining->submit(procedural_planet_disc_bytes,[tail_state]{tail_state->started=true;while(!tail_state->released.load())std::this_thread::yield();return stellar::native_map::RgbaImage::create(1,1,{0,0,0,0});});require(tail_request.has_value(),"tail drain barrier was not admitted");auto tail=std::move(*tail_request);tail_gate.wait_started();const auto new_background=appearance(1,402,NativeSystemBodyVisualClass::rocky);require(!draining_assets.request_image(new_background)&&draining_assets.pending_count()==1&&draining_assets.cache_entries()==1,"ready old background result did not drain before admitting the new request");tail_gate.release();wait_for([&]{return tail.ready();},"tail drain barrier did not complete");tail.cancel();require(await_prepared(draining_assets,new_background)&&draining_assets.cache_entries()==2,"new body did not complete after ready background results released queue capacity");
  NativePlanetDiscAssets source_pressure(fixtures.path());for(std::size_t index=0;index<maximum_planet_disc_bytes/source_planet_disc_bytes+8;++index)(void)source_pressure.image(appearance(1,500+static_cast<int>(index),NativeSystemBodyVisualClass::rocky,"mercury"));require(source_pressure.cache_entries()==maximum_planet_disc_bytes/source_planet_disc_bytes&&source_pressure.cache_bytes()==maximum_planet_disc_bytes,"source-backed planet discs exceeded the hard cache byte limit");
  require(fs::remove(fixtures.path()/L"mercury-map.png"),"decoded Mercury source remained locked or was missing");require(assets.image(mercury)==mercury_disc,"cached disc attempted to decode its released source again");
  NativePlanetDiscAssets missing_assets(fixtures.path());bool missing_path_reported{};try{(void)missing_assets.image(mercury);}catch(const std::exception &error){missing_path_reported=std::string(error.what()).find("mercury-map.png")!=std::string::npos;}require(missing_path_reported,"missing planet asset diagnostic omitted the requested path");require(missing_assets.cache_entries()==0,"failed source decode populated the disc cache");
  NativePlanetDiscAssets background_missing(fixtures.path());background_missing.use_background_preparation(preparation);require(!background_missing.request_image(mercury),"missing source background request was not deferred");bool background_missing_path{};try{(void)await_prepared(background_missing,mercury);}catch(const std::exception &error){background_missing_path=std::string(error.what()).find("mercury-map.png")!=std::string::npos;}require(background_missing_path&&background_missing.cache_entries()==0&&background_missing.pending_count()==0,"background decode diagnostic was not delivered on the owner");
  auto old_fallback=assets.image(appearance(1,200,NativeSystemBodyVisualClass::oceanic));std::weak_ptr<const stellar::native_map::RgbaImage> old_weak=old_fallback;old_fallback.reset();const auto next=assets.image(appearance(2,200,NativeSystemBodyVisualClass::oceanic));require(next&&old_weak.expired(),"campaign generation replacement retained old disc resources");bool stale_rejected{};try{(void)assets.image(appearance(1,201,NativeSystemBodyVisualClass::rocky));}catch(const std::invalid_argument&){stale_rejected=true;}require(stale_rejected,"stale campaign generation repopulated the disc cache");
  for(std::size_t index=0;index<maximum_planet_disc_entries+8;++index)(void)assets.image(appearance(2,1000+static_cast<int>(index),NativeSystemBodyVisualClass::rocky));require(assets.cache_entries()<=maximum_planet_disc_entries,"planet disc cache exceeded its entry cap");require(assets.cache_bytes()<=maximum_planet_disc_bytes,"planet disc cache exceeded its byte cap");assets.discard_campaign();require(assets.cache_entries()==0&&assets.cache_bytes()==0,"campaign discard retained generated discs");
  std::cout<<"native shared planet maps, observer gating, lighting and bounded cache passed\n";return 0;
}catch(const std::exception &error){std::cerr<<"native planet disc tests failed: "<<error.what()<<'\n';return 1;}
