#include "native_economy_workspace.hpp"

#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <variant>

namespace {
using namespace stellar::native_economy;
using namespace stellar::native_map;
void require(bool condition, std::string_view message) { if(!condition) throw std::runtime_error(std::string(message)); }
Point center(UiRect box) { return {box.x+box.width*.5f,box.y+box.height*.5f}; }
bool contains(UiRect outer,UiRect inner) { return inner.x>=outer.x&&inner.y>=outer.y&&inner.x+inner.width<=outer.x+outer.width&&inner.y+inner.height<=outer.y+outer.height; }
bool intersects(UiRect a,UiRect b) { return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y; }
TextExtent measure(const Text& value) { const auto columns=std::max(1,static_cast<int>(value.wrap_width/7.f)); const auto lines=std::max(1,(static_cast<int>(value.value.size())+columns-1)/columns); return {columns*7,lines*(value.font_pixel_size+4)}; }
NativeEconomyView view() {
  NativeEconomyView value; value.state=EconomyState::Ready; value.campaign_generation=7;value.revision=3;value.treasury_healthy=true;
  value.cards={{{"RESERVES","¤ 145,000"},{"NET / DAY","+230 / DAY"},{"INCOME / DAY","+700 / DAY"},{"COSTS / DAY","-470 / DAY",true},{"MATERIALS IN STORAGE","4,000 / 8,000"},{"MATERIALS / DAY","+20 / DAY"}}};
  value.treasury_status="SURPLUS · Current income covers operating commitments.";
  value.priority_status="Current choice: Balanced. A long UTF-8 explanation: 施設の優先順位 must wrap and remain reachable.";
  value.income_rows={{"COLONY ECONOMY","+500"},{"SURFACE TRADE","+200"}};
  value.cost_rows={{"COLONY ADMINISTRATION","-100"},{"POPULATION SERVICES","-50"},{"HABITAT SUPPORT","-50"},{"FLEET OPERATIONS","-90"},{"ORBITAL MAINTENANCE","-40"},{"SURFACE MAINTENANCE","-40"},{"RESEARCH PROGRAMS","-100"," · ¤ 20 RESERVED"}};
  return value;
}
void layout_is_responsive() { for(auto [w,h]:{std::pair{1280,720},std::pair{1920,1080},std::pair{3840,2160}}) { const auto l=EconomyLayout::for_viewport(w,h);const UiRect viewport{0,0,float(w),float(h)};require(contains(viewport,l.panel)&&contains(l.panel,l.body)&&contains(l.panel,l.close)&&contains(l.panel,l.refresh),"economy layout escaped viewport");for(auto b:l.priority_buttons)require(contains(l.panel,b),"priority control escaped panel"); } }
void every_flow_row_is_drawn() { NativeEconomyWorkspace workspace;workspace.open();const auto v=view();DrawList draw;workspace.render(draw,v,3840,2160);for(const auto& row:v.income_rows) { bool found{};for(const auto& item:draw.overlay)if(const auto*t=std::get_if<Text>(&item);t&&t->value==row.label)found=true;require(found,"income row was omitted from economy panel"); }for(const auto& row:v.cost_rows) { bool found{};for(const auto& item:draw.overlay)if(const auto*t=std::get_if<Text>(&item);t&&t->value==row.label)found=true;require(found,"cost row was omitted from economy panel"); } }
void rows_scroll_and_are_clipped() { NativeEconomyWorkspace workspace;workspace.set_text_measurer(measure);workspace.open();const auto v=view();const auto l=EconomyLayout::for_viewport(1280,720);for(int i=0;i<100;++i)(void)workspace.handle({InputEventType::Wheel,center(l.body),{},-10},v,1280,720);require(workspace.scroll_offset()>0,"economy rows did not scroll");DrawList draw;workspace.render(draw,v,1280,720);bool reserved{};for(const auto& item:draw.overlay)if(const auto* t=std::get_if<Text>(&item);t&&t->value.find("¤ 20 RESERVED")!=std::string::npos){reserved=true;require(t->clip&&intersects(*t->clip,l.body),"reserved research row escaped body clip");}require(reserved,"reserved research row was unreachable"); }
void controls_are_pinned_and_cache_is_bounded() { int calls{};NativeEconomyWorkspace workspace;workspace.set_text_measurer([&](const Text&t){++calls;return measure(t);});workspace.open();auto v=view();DrawList first;workspace.render(first,v,1280,720);const auto initial=calls;DrawList again;workspace.render(again,v,1280,720);require(calls==initial,"unchanged economy render remeasured geometry");const auto l=EconomyLayout::for_viewport(1280,720);for(int i=0;i<100;++i)(void)workspace.handle({InputEventType::Wheel,center(l.body),{},-10},v,1280,720);DrawList after;workspace.render(after,v,1280,720);bool refresh{};for(const auto& item:after.overlay)if(const auto*t=std::get_if<Text>(&item);t&&t->value=="REFRESH")refresh=t->clip&&contains(l.panel,*t->clip);require(refresh,"pinned refresh disappeared while body scrolled");v.priority_status+=" changed";DrawList changed;workspace.render(changed,v,1280,720);require(calls>initial,"changed snapshot did not invalidate cache"); }
void gestures_do_not_leak_or_activate_stale_buttons() { NativeEconomyWorkspace workspace;workspace.open();auto v=view();const auto l=EconomyLayout::for_viewport(1280,720);auto command=workspace.handle({InputEventType::LeftReleased,center(l.priority_buttons[2])},v,1280,720);require(command.kind==EconomyCommandKind::None,"release-only activated priority");command=workspace.handle({InputEventType::LeftPressed,center(l.priority_buttons[2])},v,1280,720);require(command.captured,"panel press leaked");++v.revision;command=workspace.handle({InputEventType::LeftReleased,center(l.priority_buttons[2])},v,1280,720);require(command.kind==EconomyCommandKind::None,"stale priority press activated");(void)workspace.handle({InputEventType::LeftPressed,center(l.priority_buttons[2])},v,1280,720);++v.player_civilization_id;command=workspace.handle({InputEventType::LeftReleased,center(l.priority_buttons[2])},v,1280,720);require(command.kind==EconomyCommandKind::None,"observer change activated a stale priority press");(void)workspace.handle({InputEventType::LeftPressed,center(l.body)},v,1280,720);require(workspace.handle({InputEventType::PointerCancelled},v,1280,720).captured,"cancel not captured");require(!workspace.handle({InputEventType::LeftReleased,{0,0}},v,1280,720).captured,"cancel retained pointer ownership");command=workspace.handle({InputEventType::LeftPressed,center(l.refresh)},v,1280,720);command=workspace.handle({InputEventType::LeftReleased,center(l.refresh)},v,1280,720);require(command.kind==EconomyCommandKind::Refresh,"refresh hit zone did not command refresh"); }
void failure_is_actionable_without_stale_data() { NativeEconomyWorkspace workspace;workspace.open();auto failed=view();failed.state=EconomyState::Failed;failed.message="Treasury snapshot failed.";failed.diagnostic="player={serialized campaign}";DrawList draw;workspace.render(draw,failed,1280,720);bool retry{}, stale{}, dump{};for(const auto& item:draw.overlay)if(const auto*t=std::get_if<Text>(&item)){retry=retry||t->value=="RETRY";stale=stale||t->value=="¤ 145,000";dump=dump||t->value.find("serialized campaign")!=std::string::npos;}require(retry&&!stale&&!dump,"failed economy state did not expose retry safely");auto unavailable=failed;unavailable.state=EconomyState::Unavailable;DrawList unavailable_draw;workspace.render(unavailable_draw,unavailable,1280,720);bool unavailable_retry{};for(const auto& item:unavailable_draw.overlay)if(const auto*t=std::get_if<Text>(&item))unavailable_retry=unavailable_retry||t->value=="RETRY";require(unavailable_retry,"unavailable economy state omitted retry"); }
}
int main() { try { layout_is_responsive();every_flow_row_is_drawn();rows_scroll_and_are_clipped();controls_are_pinned_and_cache_is_bounded();gestures_do_not_leak_or_activate_stale_buttons();failure_is_actionable_without_stale_data(); } catch(const std::exception& error) { std::cerr<<error.what()<<'\n';return 1;} }
