#include "native_startup_artwork.hpp"
#include "native_startup_workspace.hpp"
#include <filesystem>
#include <iostream>
#include <stdexcept>
using namespace stellar::native_map;using namespace stellar::native_setup;using namespace stellar::native_startup;using namespace stellar::native_startup_ui;namespace fs=std::filesystem;
void req(bool x,const char*m){if(!x)throw std::runtime_error(m);} Point ctr(UiRect r){return {r.x+r.width/2,r.y+r.height/2};}
TextExtent measure(const Text&t){return {static_cast<int>(t.value.size())*8,t.font_pixel_size+2};}
NativeNewCampaignSetupView setup(){NativeNewCampaignSetupView v;NativeSpeciesSetupOption s;s.id="terran_baseline";s.display_name="Terran Baseline";s.biochemistry_label="Carbon";s.preferred_atmosphere_label="Oxygen";s.biological_solvent_label="Water";s.gravity_g={1,.1,.5};s.temperature_kelvin={288,20,60};s.pressure_kpa={101,30,80};v.species.push_back(s);v.size_presets={{250,"Small - 250 systems",false},{500,"Medium - 500 systems",true},{1000,"Large - 1,000 systems",false},{2500,"Huge - 2,500 systems",false}};v.default_species_id=s.id;v.default_system_count=500;return v;}
void assets(const fs::path&root){NativeStartupArtworkAssets a(root);std::size_t bytes{};for(auto k:{StartupArtworkKind::ApplicationStartup,StartupArtworkKind::MainMenu,StartupArtworkKind::NewGalaxyGeneration,StartupArtworkKind::SaveRestoration}){auto p=a.image(k);req(p&&p->width()>0&&p->height()>0,"asset decode");req(a.image(k)==p,"cache miss");bytes+=p->byte_size();}req(a.decoded_count()==4,"cache count");req(bytes<=maximum_image_cache_resident_bytes/2,"asset budget");auto p=a.image(StartupArtworkKind::MainMenu);for(auto [w,h]:{std::pair{1280,720},std::pair{1920,1080},std::pair{3840,2160}}){auto d=startup_artwork_destination(p->width(),p->height(),w,h);req(d.x<=0&&d.y<=0&&d.x+d.width>=w&&d.y+d.height>=h,"cover");}bool bad{};try{(void)startup_artwork_destination(0,1,1,1);}catch(const std::invalid_argument&){bad=true;}req(bad,"bad dimensions");req(startup_boot_progress(4,4,std::chrono::seconds(1),std::chrono::seconds(7))<1.,"boot reached 100 percent before minimum display");req(startup_boot_progress(3,4,std::chrono::seconds(7),std::chrono::seconds(7))==.75,"boot outran asset readiness");req(startup_boot_progress(4,4,std::chrono::milliseconds::zero(),std::chrono::milliseconds::zero())==1.,"zero-minimum automation did not finish at readiness");NativeStartupArtworkAssets missing(root/"missing");bool useful{};try{(void)missing.image(StartupArtworkKind::MainMenu);}catch(const std::exception&e){useful=std::string(e.what()).find("stellar-continuum-splash.png")!=std::string::npos;}req(useful,"missing path diagnostic");}
void workspace(){NativeStartupWorkspace ui;ui.set_setup(setup());std::vector<StartupArtworkKind> seen;auto image=RgbaImage::create(16,9,std::vector<std::uint8_t>(16*9*4,255));StartupArtworkProvider art=[&](auto k){seen.push_back(k);return image;};NativeStartupWorkspace::PortraitProvider portraits=[](std::string_view){return std::shared_ptr<const RgbaImage>{};};auto check=[&](StartupArtworkKind k){DrawList d;ui.render(d,1280,720,measure,&portraits,&art);req(seen.back()==k,"phase mapping");req(!d.overlay.empty()&&std::holds_alternative<Image>(d.overlay.front()),"backdrop order");return d;};auto entry=check(StartupArtworkKind::MainMenu);auto l=StartupLayout::for_viewport(1280,720);bool veil{};for(auto&i:entry.overlay)if(auto*f=std::get_if<FilledRectangle>(&i);f&&f->bounds.x==l.panel.x&&f->bounds.y==l.panel.y)veil=f->bounds.width<1280&&f->bounds.height<720&&f->color.a<240;req(veil,"opaque full veil");(void)ui.handle({InputEventType::LeftPressed,ctr(l.new_campaign)},1280,720,measure);(void)check(StartupArtworkKind::MainMenu);ui.begin_operation({7,1,NativeStartupPhase::Generating,"Seeding",std::nullopt,true,false},StartupOperationOrigin::NewCampaign);(void)check(StartupArtworkKind::NewGalaxyGeneration);ui.set_operation({7,2,NativeStartupPhase::AwaitingOwnerActivation,"Activating",std::nullopt,false,false});(void)check(StartupArtworkKind::NewGalaxyGeneration);ui.show_entry();ui.begin_operation({8,1,NativeStartupPhase::LoadingSave,"Reading selected save",.4,true,false},StartupOperationOrigin::SavedCampaign);auto load=check(StartupArtworkKind::SaveRestoration);bool progress{},status{},cancel{},tip{};for(auto&i:load.overlay){if(auto*f=std::get_if<FilledRectangle>(&i);f&&f->color.r==100&&f->color.g==214)progress=true;if(auto*t=std::get_if<Text>(&i)){status|=t->value=="Reading selected save";cancel|=t->value=="CANCEL";tip|=t->value.starts_with("Tip: ");}}req(progress&&status&&cancel&&tip,"live loading UI");ui.show_entry();ui.begin_operation({9,1,NativeStartupPhase::AwaitingOwnerActivation,"Awaiting activation",std::nullopt,false,false},StartupOperationOrigin::SavedCampaign);(void)check(StartupArtworkKind::SaveRestoration);ui.set_operation({9,2,NativeStartupPhase::Activating,"Activating saved campaign",std::nullopt,false,false});(void)check(StartupArtworkKind::SaveRestoration);}
void responsive(){for(auto[w,h]:{std::pair{1280,720},std::pair{1920,1080},std::pair{3840,2160}}){auto l=StartupLayout::for_viewport(w,h);req(l.panel.contains(ctr(l.new_campaign))&&l.panel.contains(ctr(l.load_campaign))&&l.panel.contains(ctr(l.exit))&&l.panel.contains(ctr(l.back))&&l.panel.contains(ctr(l.primary)),"responsive controls");}}
int main(int n,char**v){try{if(n!=2)throw std::runtime_error("usage: test <asset-root>");assets(fs::path(v[1]));workspace();responsive();std::cout<<"3/3 native startup artwork cases passed\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}catch(...){return 1;}}
