#include "native_surface_relief.hpp"

#include <atomic>
#include <chrono>
#include <cstdio>
#include <memory>
#include <stdexcept>
#include <thread>

using namespace stellar::native_surface;
namespace {
void require(bool value,const char *message){if(!value)throw std::runtime_error(message);}
template<class Predicate>void wait_for(Predicate predicate,const char *message){const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(20);while(!predicate()){if(std::chrono::steady_clock::now()>=deadline)throw std::runtime_error(message);std::this_thread::yield();}}
std::shared_ptr<const stellar::native_map::RgbaImage> await_image(NativeSurfaceRelief &relief,NativeSurfaceReliefIdentity identity){std::shared_ptr<const stellar::native_map::RgbaImage> result;wait_for([&]{return static_cast<bool>(result=relief.request(identity));},"surface relief preparation did not complete");return result;}
class WorkerGate final {public:struct State{std::atomic<bool> started{},released{};};WorkerGate():state_(std::make_shared<State>()){}~WorkerGate(){release();}[[nodiscard]]std::shared_ptr<State> state()const{return state_;}void release()const noexcept{state_->released=true;}void wait_started()const{wait_for([state=state_]{return state->started.load();},"relief gate did not start");}private:std::shared_ptr<State> state_;};
}

int main()try{
  NativeSurfaceRelief inactive;require(!inactive.request({1,2,3})&&inactive.pending_count()==0,"relief generated synchronously without a preparation queue");
  auto queue=std::make_shared<stellar::native_map::ImagePreparationQueue>(1,NativeSurfaceRelief::image_bytes);NativeSurfaceRelief relief;relief.use_background_preparation(queue);const NativeSurfaceReliefIdentity first{1,2,3};require(!relief.request(first)&&relief.pending_count()==1&&queue->reserved_bytes()==NativeSurfaceRelief::image_bytes,"relief did not reserve its fixed 4 MiB output");require(!relief.request(first)&&relief.pending_count()==1,"duplicate relief request admitted another job");const auto image=await_image(relief,first);require(image->width()==NativeSurfaceRelief::image_resolution&&image->height()==NativeSurfaceRelief::image_resolution&&image->byte_size()==NativeSurfaceRelief::image_bytes,"relief image did not retain its fixed world-space size");const auto stats=relief.stats();require(stats.ready&&!stats.pending&&!stats.failed&&stats.cache_bytes==NativeSurfaceRelief::image_bytes&&stats.reserved_bytes==0&&stats.generated==1,"relief retained more than one live output or reported an invalid result");const auto center=(static_cast<std::size_t>(NativeSurfaceRelief::image_resolution/2)*NativeSurfaceRelief::image_resolution+NativeSurfaceRelief::image_resolution/2)*4u;require(image->pixels()[center+3]==0,"flat hub apron was not transparent in the relief mask");bool shaded{},bright{},dark{};for(std::size_t index=0;index<image->pixels().size();index+=4u){const auto alpha=image->pixels()[index+3];require(alpha<=54,"relief alpha exceeded its bounded modulation limit");shaded|=alpha>0;bright|=alpha>0&&image->pixels()[index]==255;dark|=alpha>0&&image->pixels()[index]==0;}require(shaded&&bright&&dark,"relief did not contain bounded neutral slope variation");require(relief.request(first)==image,"camera-independent relief request did not reuse the ready image");
  auto saturated=std::make_shared<stellar::native_map::ImagePreparationQueue>(1,NativeSurfaceRelief::image_bytes);WorkerGate saturated_gate;auto saturated_state=saturated_gate.state();auto barrier=saturated->submit(NativeSurfaceRelief::image_bytes,[saturated_state]{saturated_state->started=true;while(!saturated_state->released.load())std::this_thread::yield();return stellar::native_map::RgbaImage::create(1,1,{0,0,0,0});});require(barrier.has_value(),"relief saturation barrier was not admitted");saturated_gate.wait_started();NativeSurfaceRelief delayed;delayed.use_background_preparation(saturated);require(!delayed.request({2,4,5})&&delayed.pending_count()==0&&delayed.stats().deferred,"saturated relief queue admitted a job");saturated_gate.release();wait_for([&]{return barrier->ready();},"relief barrier did not finish");barrier->cancel();require(!delayed.request({2,4,5})&&delayed.pending_count()==1&&delayed.stats().reserved_bytes==NativeSurfaceRelief::image_bytes,"relief did not retry after saturated capacity was released");const auto replacement=await_image(delayed,{2,4,5});require(replacement&&delayed.cache_bytes()==NativeSurfaceRelief::image_bytes,"retried relief did not publish its bounded image");
  auto replacement_queue=std::make_shared<stellar::native_map::ImagePreparationQueue>(2,2u*NativeSurfaceRelief::image_bytes);WorkerGate replacement_gate;auto replacement_state=replacement_gate.state();auto held=replacement_queue->submit(NativeSurfaceRelief::image_bytes,[replacement_state]{replacement_state->started=true;while(!replacement_state->released.load())std::this_thread::yield();return stellar::native_map::RgbaImage::create(1,1,{0,0,0,0});});require(held.has_value(),"replacement gate was not admitted");replacement_gate.wait_started();NativeSurfaceRelief rebound;rebound.use_background_preparation(replacement_queue);require(!rebound.request({4,6,7})&&rebound.pending_count()==1,"old relief request was not queued");require(!rebound.request({5,6,7})&&rebound.pending_count()==0&&rebound.stats().deferred,"replacement retained an old pending relief");replacement_gate.release();wait_for([&]{return held->ready();},"replacement gate did not finish");held->cancel();const auto fresh=await_image(rebound,{5,6,7});require(fresh&&rebound.stats().generated==1,"replacement identity published a stale pending relief result");require(!rebound.request({6,6,7})&&rebound.pending_count()==1,"clear-pending relief was not admitted");rebound.clear();require(rebound.pending_count()==0&&rebound.cache_bytes()==0,"relief clear retained a pending or ready generation");return 0;
}catch(const std::exception &error){std::fprintf(stderr,"native surface relief tests failed: %s\n",error.what());return 1;}
