#include <stellar/core/settlement_planning.hpp>
#include <nlohmann/json.hpp>

#include <algorithm>
#include <cmath>
#include <exception>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

using Json=nlohmann::json;
using namespace stellar::core;
namespace {
[[noreturn]] void fail(const std::string&m){throw std::runtime_error(m);}
void check(bool c,const std::string&m){if(!c)fail(m);}
double number(const Json&v){if(v.is_number())return v.get<double>();auto s=v.get<std::string>();if(s=="NaN")return std::numeric_limits<double>::quiet_NaN();if(s=="Infinity")return std::numeric_limits<double>::infinity();if(s=="-Infinity")return -std::numeric_limits<double>::infinity();fail("bad number");}
template<class T>std::optional<T> optional(const Json&v){return v.is_null()?std::nullopt:std::optional<T>(v.get<T>());}
Json jnum(double v){if(std::isnan(v))return "NaN";if(std::isinf(v))return v>0?Json("Infinity"):Json("-Infinity");return v;}
void equal_json(const Json&a,const Json&e,const std::string&f){
  if(a.is_number()&&e.is_number()){auto x=a.get<double>(),y=e.get<double>();if((std::isnan(x)&&std::isnan(y))||x==y)return;auto scale=std::max({1.,std::abs(x),std::abs(y)});check(std::abs(x-y)<=1e-7*scale,f+": number "+a.dump()+" != "+e.dump());return;}
  if(a.is_array()&&e.is_array()){check(a.size()==e.size(),f+": array size");for(size_t i=0;i<a.size();++i)equal_json(a[i],e[i],f+"["+std::to_string(i)+"]");return;}
  if(a.is_object()&&e.is_object()){check(a.size()==e.size(),f+": object size");for(auto&[k,v]:e.items()){check(a.contains(k),f+": missing "+k);equal_json(a.at(k),v,f+"."+k);}return;}
  check(a==e,f+": "+a.dump()+" != "+e.dump());
}
StellarSystem parse_system(const Json&v){StellarSystem r;r.id=v.at("Id");r.name=v.at("Name");r.position={static_cast<float>(number(v.at("Position").at("X"))),static_cast<float>(number(v.at("Position").at("Y"))),optional<double>(v.at("GalacticDepthLightYears"))};return r;}
PlanetaryBody parse_body(const Json&v){PlanetaryBody r;r.id=v.at("Id");r.system_id=v.at("SystemId");r.parent_body_id=optional<int>(v.at("ParentBodyId"));r.orbit_index=v.at("OrbitIndex");r.name=v.at("Name");r.kind=static_cast<PlanetaryBodyKind>(v.at("Kind").get<int>());r.radius_earth=number(v.at("RadiusEarth"));r.mass_earth=number(v.at("MassEarth"));auto&e=v.at("Environment");r.environment={number(e.at("GravityG")),number(e.at("TemperatureKelvin")),number(e.at("PressureKPa")),static_cast<PlanetaryAtmosphereRegime>(e.at("Atmosphere").get<int>()),static_cast<PlanetarySolventRegime>(e.at("AvailableSolvent").get<int>()),number(e.at("RadiationHazard")),e.at("IsImmersedEnvironment"),e.at("HasSolidSurface")};r.legacy_colonization_candidate=v.at("LegacyColonizationCandidate");r.has_rare_resource=v.at("HasRareResource");r.has_anomaly=v.at("HasAnomaly");r.has_pre_warp_civilization=v.at("HasPreWarpCivilization");return r;}
Civilization parse_civ(const Json&v){Civilization r;r.id=v.at("Id");r.name=v.at("Name");r.home_system_id=v.at("HomeSystemId");r.species_id=v.at("SpeciesId");return r;}
Colony parse_colony(const Json&v){Colony r;r.id=v.at("Id");r.civilization_id=v.at("CivilizationId");r.system_id=v.at("SystemId");r.planetary_body_id=optional<int>(v.at("PlanetaryBodyId"));r.name=v.at("Name");r.kind=static_cast<SettlementKind>(v.at("Kind").get<int>());r.population_species_id=v.at("PopulationSpeciesId");r.population_millions=number(v.at("PopulationMillions"));return r;}
FleetState parse_fleet(const Json&v){FleetState r;r.id=v.at("Id");r.civilization_id=v.at("CivilizationId");r.name=v.at("Name");r.role=static_cast<FleetRole>(v.at("Role").get<int>());r.design_id=optional<std::string>(v.at("DesignId"));r.position={static_cast<float>(number(v.at("Position").at("X"))),static_cast<float>(number(v.at("Position").at("Y")))};r.current_system_id=optional<int>(v.at("CurrentSystemId"));r.destination_system_id=optional<int>(v.at("DestinationSystemId"));r.transit_phase=static_cast<FleetTransitPhase>(v.at("TransitPhase").get<int>());r.transit_origin_system_id=optional<int>(v.at("TransitOriginSystemId"));r.transit_target_system_id=optional<int>(v.at("TransitTargetSystemId"));r.transit_progress=number(v.at("TransitProgress"));r.planned_route_system_ids=v.at("PlannedRouteSystemIds").get<std::vector<int>>();r.destination_planetary_body_id=optional<int>(v.at("DestinationPlanetaryBodyId"));r.maximum_leg_range_light_years=number(v.at("MaximumLegRangeLightYears"));r.fuel_capacity_light_years=number(v.at("FuelCapacityLightYears"));r.fuel_remaining_light_years=number(v.at("FuelRemainingLightYears"));r.is_active=v.at("IsActive");r.embarked_population_millions=number(v.at("EmbarkedPopulationMillions"));r.embarked_population_species_id=optional<std::string>(v.at("EmbarkedPopulationSpeciesId"));return r;}
struct World{std::vector<StellarSystem>systems;std::vector<PlanetaryBody>bodies;std::vector<Civilization>civs;std::vector<Colony>colonies;std::vector<FleetState>fleets;std::vector<CivilizationEconomy>economies;CivilizationKnowledgeState knowledge;std::unique_ptr<InterstellarLaneNetwork>lanes;SettlementPlanningWorldView view(){return{systems,bodies,civs,colonies,fleets,economies,knowledge,*lanes};}};
World parse_world(const Json&v){World r;for(auto&e:v.at("Systems"))r.systems.push_back(parse_system(e));for(auto&e:v.at("Bodies"))r.bodies.push_back(parse_body(e));for(auto&e:v.at("Civilizations"))r.civs.push_back(parse_civ(e));for(auto&e:v.at("Colonies"))r.colonies.push_back(parse_colony(e));for(auto&e:v.at("Fleets"))r.fleets.push_back(parse_fleet(e));for(auto&e:v.at("Economies")){CivilizationEconomy x;x.civilization_id=e.at("CivilizationId");x.credits=number(e.at("Credits"));r.economies.push_back(x);}for(auto&o:v.at("Knowledge")){auto cid=o.at("CivilizationId").get<int>();for(auto&s:o.at("Surveys")){auto sid=s.at("SystemId").get<int>(),level=s.at("Level").get<int>();auto p=number(s.at("Progress"));if(level==1)r.knowledge.reveal_system(cid,sid);else if(level==2)r.knowledge.advance_system_survey(cid,sid,p);else if(level==3)r.knowledge.mark_system_fully_surveyed(cid,sid);}}r.lanes=std::make_unique<InterstellarLaneNetwork>(std::span<const StellarSystem>(r.systems));return r;}
Json enc_reach(const MissionReachAssessment&r){return{{"IsSupported",r.is_supported},{"IsAuthoritative",r.is_authoritative},{"Reason",r.reason},{"RouteSystemIds",r.route_system_ids?Json(*r.route_system_ids):Json(nullptr)},{"RouteDistanceLightYears",jnum(r.route_distance_light_years)}};}
Json enc_colony_candidate(const ColonizationOpportunityCandidate&x){return{{"SystemId",x.system_id},{"SystemName",x.system_name},{"PlanetaryBodyId",x.planetary_body_id},{"PlanetaryBodyName",x.planetary_body_name},{"PlanetaryBodyKind",x.planetary_body_kind},{"FleetId",x.fleet_id},{"PassengerSpeciesId",x.passenger_species_id},{"ColonizationViability",x.colonization_viability},{"NaturalHabitability",jnum(x.natural_habitability)},{"UnprotectedOperationalCapacity",jnum(x.unprotected_operational_capacity)},{"LimitingFactor",x.limiting_factor},{"RequiresGravityMitigation",x.requires_gravity_mitigation},{"RequiresThermalControl",x.requires_thermal_control},{"RequiresPressureControl",x.requires_pressure_control},{"RequiresSealedHabitat",x.requires_sealed_habitat},{"RequiresArtificialBiosphere",x.requires_artificial_biosphere},{"RequiresRadiationShielding",x.requires_radiation_shielding},{"HasSolidSurface",x.has_solid_surface},{"HasNativePreWarpCivilization",x.has_native_pre_warp_civilization},{"HasRareResource",x.has_rare_resource},{"SystemOccupied",x.system_occupied},{"DistanceFromFleet",jnum(x.distance_from_fleet)},{"Reach",enc_reach(x.reach)},{"CanOrder",x.can_order},{"Reason",x.reason},{"SystemReservedByFriendlyColonyMission",x.system_reserved_by_friendly_colony_mission},{"ReservedByFleetId",x.reserved_by_fleet_id?Json(*x.reserved_by_fleet_id):Json(nullptr)}};}
Json enc_colony_plan(const ColonizationOpportunityPlan&p){Json c=Json::array();for(auto&x:p.candidates)c.push_back(enc_colony_candidate(x));return{{"FleetId",p.fleet_id},{"FleetName",p.fleet_name},{"CivilizationId",p.civilization_id},{"PassengerSpeciesId",p.passenger_species_id},{"PassengerSpeciesName",p.passenger_species_name},{"EmbarkedPopulationMillions",p.embarked_population_millions},{"CanReceiveOrders",p.can_receive_orders},{"Status",p.status},{"Candidates",c}};}
Json enc_colony_assessment(const ColonizationOrderAssessment&a){return{{"Accepted",a.accepted},{"Message",a.message},{"Candidate",a.candidate?enc_colony_candidate(*a.candidate):Json(nullptr)}};}
Json enc_outpost_candidate(const ResourceOutpostOpportunityCandidate&x){return{{"SystemId",x.system_id},{"SystemName",x.system_name},{"PlanetaryBodyId",x.planetary_body_id},{"PlanetaryBodyName",x.planetary_body_name},{"FleetId",x.fleet_id},{"PersonnelSpeciesId",x.personnel_species_id},{"NaturalHabitability",jnum(x.natural_habitability)},{"UnprotectedOperationalCapacity",jnum(x.unprotected_operational_capacity)},{"LimitingFactor",x.limiting_factor},{"HasRareResource",x.has_rare_resource},{"DepositMaterialName",x.deposit_material_name},{"DepositGrade",x.deposit_grade},{"DepositAccessibility",jnum(x.deposit_accessibility)},{"ExtractionYieldMultiplier",jnum(x.extraction_yield_multiplier)},{"InitialDepositMaterials",jnum(x.initial_deposit_materials)},{"SystemOccupied",x.system_occupied},{"IsTooHarshForColony",x.is_too_harsh_for_colony},{"DistanceFromFleet",jnum(x.distance_from_fleet)},{"Reach",enc_reach(x.reach)},{"CanOrder",x.can_order},{"Reason",x.reason}};}
Json enc_outpost_plan(const ResourceOutpostOpportunityPlan&p){Json c=Json::array();for(auto&x:p.candidates)c.push_back(enc_outpost_candidate(x));return{{"FleetId",p.fleet_id},{"FleetName",p.fleet_name},{"CivilizationId",p.civilization_id},{"PersonnelSpeciesId",p.personnel_species_id},{"PersonnelSpeciesName",p.personnel_species_name},{"PersonnelMillions",p.personnel_millions},{"CanReceiveOrders",p.can_receive_orders},{"Status",p.status},{"Candidates",c}};}
Json enc_outpost_assessment(const ResourceOutpostOrderAssessment&a){return{{"Accepted",a.accepted},{"Message",a.message},{"Candidate",a.candidate?enc_outpost_candidate(*a.candidate):Json(nullptr)}};}
struct Error{std::string type,message;};
struct ReachCall{int civilization_id,fleet_id,target_system_id;InterstellarMissionKind mission_kind;};
Json enc_calls(const std::vector<ReachCall>&calls){Json a=Json::array();for(auto&x:calls)a.push_back({{"CivilizationId",x.civilization_id},{"FleetId",x.fleet_id},{"TargetSystemId",x.target_system_id},{"MissionKind",x.mission_kind}});return a;}
Json fingerprint(const World&w){Json j;j["systems"]=Json::array();for(auto&s:w.systems)j["systems"].push_back({s.id,s.name,s.position.x,s.position.y,s.position.depth_light_years});j["bodies"]=Json::array();for(auto&b:w.bodies)j["bodies"].push_back({b.id,b.system_id,b.name,b.kind,b.environment.gravity_g,b.environment.temperature_kelvin,b.environment.pressure_kpa,b.environment.has_solid_surface,b.has_rare_resource,b.has_pre_warp_civilization});j["civs"]=Json::array();for(auto&c:w.civs)j["civs"].push_back({c.id,c.name,c.species_id});j["colonies"]=Json::array();for(auto&c:w.colonies)j["colonies"].push_back({c.id,c.civilization_id,c.system_id,c.planetary_body_id,c.name,c.kind,c.population_species_id,c.population_millions});j["fleets"]=Json::array();for(auto&f:w.fleets)j["fleets"].push_back({f.id,f.civilization_id,f.name,f.role,f.design_id,f.position.x,f.position.y,f.current_system_id,f.destination_system_id,f.transit_phase,f.transit_origin_system_id,f.transit_progress,f.planned_route_system_ids,f.destination_planetary_body_id,f.maximum_leg_range_light_years,f.fuel_capacity_light_years,f.fuel_remaining_light_years,f.is_active,f.embarked_population_millions,f.embarked_population_species_id});j["economies"]=Json::array();for(auto&e:w.economies)j["economies"].push_back({e.civilization_id,e.credits});j["knowledge"]=Json::array();for(auto&c:w.civs)for(auto&s:w.systems)j["knowledge"].push_back({c.id,s.id,w.knowledge.system_survey_level(c.id,s.id)});return j;}
enum class CaseKind{ColonyBuild,ColonyAssess,ColonyReach,OutpostBuild,OutpostAssess,IsOutpost};
CaseKind parse_kind(const std::string&value){if(value=="ColonyBuild")return CaseKind::ColonyBuild;if(value=="ColonyAssess")return CaseKind::ColonyAssess;if(value=="ColonyReach")return CaseKind::ColonyReach;if(value=="OutpostBuild")return CaseKind::OutpostBuild;if(value=="OutpostAssess")return CaseKind::OutpostAssess;if(value=="IsOutpost")return CaseKind::IsOutpost;fail("unknown case kind "+value);}
void run_case(const Json&t){
  const auto name=t.at("Name").get<std::string>();
  const auto kind=parse_kind(t.at("Kind").get<std::string>());
  const auto&args=t.at("Arguments");const auto&input=args.at("World");
  const int fleet_id=args.at("FleetId").get<int>(),system_id=args.at("SystemId").get<int>(),body_id=args.at("BodyId").get<int>(),maximum=args.at("MaximumCandidates").get<int>();
  const bool injected=args.at("InjectedReach").get<bool>(),supported=args.at("ReachSupported").get<bool>(),reach_throws=args.at("ReachThrows").get<bool>();
  const auto reason=args.at("ReachReason").get<std::string>();const auto distance=number(args.at("ReachDistance"));
  const auto expected=t.at("Result"),expected_error=t.at("Error"),expected_calls=t.at("ReachCalls");
  check(input==t.at("Before"),name+": input/before");check(t.at("Before")==t.at("After"),name+": source mutated world");
  auto world=parse_world(input);const auto before=fingerprint(world);const FleetState*outpost_input=nullptr;
  if(kind==CaseKind::IsOutpost){check(!world.fleets.empty(),name+": missing IsOutpost fleet input");outpost_input=&world.fleets.front();}
  std::vector<ReachCall>calls;SettlementReachAssessment cb;
  if(injected)cb=[&,supported,reason,distance,reach_throws](OperationalReachWorldView,int civ,const FleetState&f,int target,InterstellarMissionKind mission){calls.push_back({civ,f.id,target,mission});if(reach_throws)throw std::runtime_error("fixture reach failure");return MissionReachAssessment{supported,false,reason,std::vector<int>{f.current_system_id.value_or(-1),target},distance};};
  std::optional<ColonizationOpportunityPlan>colony_plan;std::optional<ColonizationOrderAssessment>colony_assessment;std::optional<MissionReachAssessment>colony_reach;std::optional<ResourceOutpostOpportunityPlan>outpost_plan;std::optional<ResourceOutpostOrderAssessment>outpost_assessment;std::optional<bool>is_outpost;std::optional<Error>error;
  try{switch(kind){case CaseKind::ColonyBuild:colony_plan=ColonizationOpportunityPlanner(cb).build_plan(world.view(),fleet_id,maximum);break;case CaseKind::ColonyAssess:colony_assessment=ColonizationOpportunityPlanner(cb).assess_order(world.view(),fleet_id,system_id,body_id);break;case CaseKind::ColonyReach:colony_reach=ColonizationOpportunityPlanner(cb).assess_operational_reach(world.view(),fleet_id,system_id);break;case CaseKind::OutpostBuild:outpost_plan=ResourceOutpostOpportunityPlanner(cb).build_plan(world.view(),fleet_id,maximum);break;case CaseKind::OutpostAssess:outpost_assessment=ResourceOutpostOpportunityPlanner(cb).assess_order(world.view(),fleet_id,system_id,body_id);break;case CaseKind::IsOutpost:is_outpost=ResourceOutpostOpportunityPlanner::is_outpost_fleet(*outpost_input);break;}}
  catch(const std::invalid_argument&e){error=Error{"ArgumentException",e.what()};}
  catch(const std::out_of_range&e){error=Error{"ArgumentOutOfRangeException",e.what()};}
  catch(const std::overflow_error&e){error=Error{"OverflowException",e.what()};}
  catch(const std::system_error&e){error=Error{"UnexpectedNativeException",e.what()};}
  catch(const std::runtime_error&e){error=Error{"InvalidOperationException",e.what()};}
  catch(const std::exception&e){error=Error{"UnexpectedNativeException",e.what()};}
  std::optional<Json>result;if(colony_plan)result=enc_colony_plan(*colony_plan);else if(colony_assessment)result=enc_colony_assessment(*colony_assessment);else if(colony_reach)result=enc_reach(*colony_reach);else if(outpost_plan)result=enc_outpost_plan(*outpost_plan);else if(outpost_assessment)result=enc_outpost_assessment(*outpost_assessment);else if(is_outpost)result=*is_outpost;
  if(expected_error.is_null()){check(!error,name+": unexpected "+(error?error->type+" "+error->message:""));check(result.has_value(),name+": missing result");equal_json(*result,expected,name+".Result");}else{check(error.has_value(),name+": expected error");check(error->type==expected_error.at("Type").get<std::string>(),name+": error type "+error->type);check(error->message==expected_error.at("Message").get<std::string>(),name+": error message actual="+error->message+" expected="+expected_error.at("Message").get<std::string>());check(!result,name+": result on error");}
  equal_json(enc_calls(calls),expected_calls,name+".ReachCalls");equal_json(fingerprint(world),before,name+".NativeInput");
}
}
int main(int argc,char**argv){try{if(argc!=2)fail("usage: settlement_planning_tests <fixture>");std::ifstream in(argv[1]);check(in.good(),"fixture open");Json root;in>>root;check(root.at("Format").get<std::string>()=="stellar-settlement-planning-oracle-v1","format");check(root.at("CaseCount").get<std::size_t>()==root.at("Cases").size(),"case count");check(root.at("NativeBoundary").get<std::string>()=="Typed native references cannot represent a null world or fleet.","boundary");check(root.at("SourceOnlyNullWorld").size()==5,"null world count");check(root.at("SourceOnlyNullFleet").size()==1,"null fleet count");for(auto*group:{&root.at("SourceOnlyNullWorld"),&root.at("SourceOnlyNullFleet")})for(auto&entry:*group){check(entry.at("Error").is_object(),"source null error");check(!entry.at("Error").at("Type").get<std::string>().empty(),"source null type");check(!entry.at("Error").at("Message").get<std::string>().empty(),"source null message");}for(auto&t:root.at("Cases"))run_case(t);std::cout<<"settlement planning parity: "<<root.at("Cases").size()<<" cases, "<<root.at("SourceOnlyNullWorld").size()+root.at("SourceOnlyNullFleet").size()<<" source-only null observations\n";return 0;}catch(const std::exception&e){std::cerr<<"settlement planning parity failure: "<<e.what()<<"\n";return 1;}}
