#include <stellar/core/strategic_input_builder.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cmath>
#include <exception>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

using Json = nlohmann::json;
using namespace stellar::core;

namespace {
[[noreturn]] void fail(const std::string &message) { throw std::runtime_error(message); }
void check(bool condition, const std::string &message) { if (!condition) fail(message); }
double number(const Json &value) { if (value.is_number()) return value.get<double>(); const auto text=value.get<std::string>(); if(text=="NaN")return std::numeric_limits<double>::quiet_NaN();if(text=="Infinity")return std::numeric_limits<double>::infinity();if(text=="-Infinity")return-std::numeric_limits<double>::infinity();fail("invalid number"); }
template<class T>std::optional<T> optional(const Json&v){return v.is_null()?std::nullopt:std::optional<T>(v.get<T>());}
Json jnum(double value){if(std::isnan(value))return"NaN";if(std::isinf(value))return value>0?Json("Infinity"):Json("-Infinity");return value;}
void equal(const Json&a,const Json&e,const std::string&field){if(a.is_number_integer()&&e.is_number_integer()){check(a==e,field+": integer");return;}if(a.is_number()&&e.is_number()){const auto x=a.get<double>(),y=e.get<double>();if((std::isnan(x)&&std::isnan(y))||x==y)return;const auto scale=std::max({1.,std::abs(x),std::abs(y)});check(std::abs(x-y)<=1e-10*scale,field+": number "+a.dump()+" != "+e.dump());return;}if(a.is_array()&&e.is_array()){check(a.size()==e.size(),field+": size");for(std::size_t i=0;i<a.size();++i)equal(a[i],e[i],field+"["+std::to_string(i)+"]");return;}if(a.is_object()&&e.is_object()){check(a.size()==e.size(),field+": object size");for(const auto&[key,value]:e.items()){check(a.contains(key),field+": missing "+key);equal(a.at(key),value,field+"."+key);}return;}check(a==e,field+": "+a.dump()+" != "+e.dump());}

StellarSystem system(const Json&v){StellarSystem x;x.id=v.at("Id");x.name=v.at("Name");x.position={static_cast<float>(number(v.at("Position").at("X"))),static_cast<float>(number(v.at("Position").at("Y"))),optional<double>(v.at("GalacticDepthLightYears"))};return x;}
PlanetaryBody body(const Json&v){PlanetaryBody x;x.id=v.at("Id");x.system_id=v.at("SystemId");x.parent_body_id=optional<int>(v.at("ParentBodyId"));x.orbit_index=v.at("OrbitIndex");x.name=v.at("Name");x.kind=static_cast<PlanetaryBodyKind>(v.at("Kind").get<int>());x.radius_earth=number(v.at("RadiusEarth"));x.mass_earth=number(v.at("MassEarth"));const auto&e=v.at("Environment");x.environment={number(e.at("GravityG")),number(e.at("TemperatureKelvin")),number(e.at("PressureKPa")),static_cast<PlanetaryAtmosphereRegime>(e.at("Atmosphere").get<int>()),static_cast<PlanetarySolventRegime>(e.at("AvailableSolvent").get<int>()),number(e.at("RadiationHazard")),e.at("IsImmersedEnvironment"),e.at("HasSolidSurface")};x.legacy_colonization_candidate=v.at("LegacyColonizationCandidate");x.has_rare_resource=v.at("HasRareResource");x.has_anomaly=v.at("HasAnomaly");x.has_pre_warp_civilization=v.at("HasPreWarpCivilization");return x;}
Civilization civilization(const Json&v){Civilization x;x.id=v.at("Id");x.name=v.at("Name");x.home_system_id=v.at("HomeSystemId");x.species_id=v.at("SpeciesId");return x;}
Colony colony(const Json&v){Colony x;x.id=v.at("Id");x.civilization_id=v.at("CivilizationId");x.system_id=v.at("SystemId");x.planetary_body_id=optional<int>(v.at("PlanetaryBodyId"));x.name=v.at("Name");x.kind=static_cast<SettlementKind>(v.at("Kind").get<int>());x.population_species_id=v.at("PopulationSpeciesId");x.population_millions=number(v.at("PopulationMillions"));x.infrastructure=number(v.at("Infrastructure"));x.stability=number(v.at("Stability"));return x;}
FleetState fleet(const Json&v){FleetState x;x.id=v.at("Id");x.civilization_id=v.at("CivilizationId");x.name=v.at("Name");x.role=static_cast<FleetRole>(v.at("Role").get<int>());x.position={static_cast<float>(number(v.at("Position").at("X"))),static_cast<float>(number(v.at("Position").at("Y")))};x.current_system_id=optional<int>(v.at("CurrentSystemId"));x.destination_system_id=optional<int>(v.at("DestinationSystemId"));x.maximum_leg_range_light_years=number(v.at("MaximumLegRangeLightYears"));x.fuel_capacity_light_years=number(v.at("FuelCapacityLightYears"));x.fuel_remaining_light_years=number(v.at("FuelRemainingLightYears"));x.is_active=v.at("IsActive");if(!v.at("Combat").is_null()){const auto&c=v.at("Combat");FleetCombatState state;state.profile_id=c.at("ProfileId");state.shields=number(c.at("Shields"));state.armor=number(c.at("Armor"));state.hull=number(c.at("Hull"));state.weapon_cooldown_remaining_days=number(c.at("WeaponCooldownRemainingDays"));state.order=static_cast<MilitaryOrderType>(c.at("Order").get<int>());state.target_fleet_id=optional<int>(c.at("TargetFleetId"));state.defend_system_id=optional<int>(c.at("DefendSystemId"));state.retreat_progress_days=number(c.at("RetreatProgressDays"));state.retreat_started=c.at("RetreatStarted");state.is_disengaged=c.at("IsDisengaged");state.disengaged_system_id=optional<int>(c.at("DisengagedSystemId"));x.combat=std::move(state);}return x;}

struct World{std::vector<StellarSystem>systems;std::vector<PlanetaryBody>bodies;std::vector<Civilization>civilizations;std::vector<Colony>colonies;std::vector<FleetState>fleets;std::vector<CivilizationEconomy>economies;std::vector<TechnologyState>technologies;std::vector<ConstructionState>construction;CivilizationKnowledgeState knowledge;std::unique_ptr<InterstellarLaneNetwork>lanes;StrategicInputWorldView view(){return{systems,bodies,civilizations,colonies,fleets,economies,technologies,construction,knowledge,*lanes};}};
World world(const Json&v){World x;for(const auto&e:v.at("Systems"))x.systems.push_back(system(e));for(const auto&e:v.at("Bodies"))x.bodies.push_back(body(e));for(const auto&e:v.at("Civilizations"))x.civilizations.push_back(civilization(e));for(const auto&e:v.at("Colonies"))x.colonies.push_back(colony(e));for(const auto&e:v.at("Fleets"))x.fleets.push_back(fleet(e));for(const auto&e:v.at("Economies")){CivilizationEconomy value;value.civilization_id=e.at("CivilizationId");value.industry=number(e.at("Industry"));value.last_industry_per_second=number(e.at("LastIndustryPerSecond"));value.last_science_per_second=number(e.at("LastSciencePerSecond"));x.economies.push_back(value);}for(const auto&e:v.at("Technologies")){TechnologyState value;value.civilization_id=e.at("CivilizationId");for(const auto&id:e.at("CompletedTechnologyIds"))value.completed_technology_ids.insert(id.get<std::string>());value.active_research_id=optional<std::string>(e.at("ActiveResearchId"));value.active_research_progress=number(e.at("ActiveResearchProgress"));x.technologies.push_back(std::move(value));}for(const auto&e:v.at("Construction")){ConstructionState value;value.civilization_id=e.at("CivilizationId");value.completed_project_ids=e.at("CompletedProjectIds").get<std::vector<std::string>>();x.construction.push_back(std::move(value));}for(const auto&o:v.at("Surveys")){const auto id=o.at("CivilizationId").get<int>();for(const auto&s:o.at("Values")){const auto system_id=s.at("SystemId").get<int>(),level=s.at("Level").get<int>();const auto progress=number(s.at("Progress"));if(level==1)x.knowledge.reveal_system(id,system_id);else if(level==2)x.knowledge.advance_system_survey(id,system_id,progress);else if(level==3)x.knowledge.mark_system_fully_surveyed(id,system_id);}}x.lanes=std::make_unique<InterstellarLaneNetwork>(std::span<const StellarSystem>(x.systems));return x;}
Json fingerprint(const World&w){Json x;x["civ"]=Json::array();for(const auto&v:w.civilizations)x["civ"].push_back({v.id,v.species_id});x["colony"]=Json::array();for(const auto&v:w.colonies)x["colony"].push_back({v.id,v.civilization_id,v.system_id,v.population_species_id,jnum(v.population_millions),jnum(v.infrastructure),jnum(v.stability)});x["fleet"]=Json::array();for(const auto&v:w.fleets)x["fleet"].push_back({v.id,v.civilization_id,v.role,v.is_active,v.current_system_id,v.destination_system_id,v.combat?Json::array({v.combat->profile_id,jnum(v.combat->shields),jnum(v.combat->armor),jnum(v.combat->hull),jnum(v.combat->weapon_cooldown_remaining_days),v.combat->order,v.combat->target_fleet_id,v.combat->defend_system_id,jnum(v.combat->retreat_progress_days),v.combat->retreat_started,v.combat->is_disengaged,v.combat->disengaged_system_id}):Json(nullptr)});x["economy"]=Json::array();for(const auto&v:w.economies)x["economy"].push_back({v.civilization_id,jnum(v.industry),jnum(v.last_industry_per_second),jnum(v.last_science_per_second)});x["technology"]=Json::array();for(const auto&v:w.technologies)x["technology"].push_back({v.civilization_id,v.completed_technology_ids.values(),v.active_research_id,jnum(v.active_research_progress)});x["construction"]=Json::array();for(const auto&v:w.construction)x["construction"].push_back({v.civilization_id,v.completed_project_ids});for(const auto&v:w.civilizations)for(const auto&s:w.systems)x["survey"].push_back({v.id,s.id,w.knowledge.system_survey_level(v.id,s.id),jnum(w.knowledge.system_survey_progress(v.id,s.id))});return x;}
Json encode(const CivilizationOwnState&v){return{{"MilitaryStrength",jnum(v.military_strength)},{"SupplyCoverageRatio",jnum(v.supply_coverage_ratio)},{"IndustryReserve",jnum(v.industry_reserve)},{"ResearchCapacity",jnum(v.research_capacity)},{"HasAvailableResearch",v.has_available_research},{"HasUnexploredReachableSystems",v.has_unexplored_reachable_systems},{"HasKnownColonizationOpportunity",v.has_known_colonization_opportunity},{"CanBuildInterstellarShips",v.can_build_interstellar_ships},{"HasFleetCapacityShortfall",v.has_fleet_capacity_shortfall}};}
struct Error{std::string type,message;};template<class F>std::optional<Error>capture(F&&f){try{f();return{};}catch(const std::invalid_argument&e){return Error{"InvalidOperationException",e.what()};}catch(const std::out_of_range&e){return Error{"ArgumentOutOfRangeException",e.what()};}catch(const std::runtime_error&e){return Error{"InvalidOperationException",e.what()};}catch(const std::exception&e){return Error{"UnexpectedNativeException",e.what()};}}
std::string mission(InterstellarMissionKind value){switch(value){case InterstellarMissionKind::ScoutReconnaissance:return"ScoutReconnaissance";case InterstellarMissionKind::ScienceSurvey:return"ScienceSurvey";case InterstellarMissionKind::Colony:return"Colony";case InterstellarMissionKind::MilitaryDeployment:return"MilitaryDeployment";case InterstellarMissionKind::Logistics:return"Logistics";}fail("mission");}

void run(const Json&t){const auto name=t.at("Name").get<std::string>();const auto&a=t.at("Arguments");check(t.at("Before")==t.at("After"),name+": source mutation");auto input=world(a.at("World"));const auto before=fingerprint(input);const auto civilization_id=a.at("CivilizationId").get<int>();const auto injected=a.at("Injected").get<bool>();const auto coverage=number(a.at("Coverage"));const auto spacecraft=a.at("Spacecraft").get<bool>(),transit=a.at("Transit").get<bool>(),logistics_throws=a.at("LogisticsThrows").get<bool>(),reach_supported=a.at("ReachSupported").get<bool>(),reach_throws=a.at("ReachThrows").get<bool>();const auto capability_throw=optional<std::string>(a.at("CapabilityThrow"));std::vector<std::string>calls;
 StrategicLogisticsQuery logistics;StrategicShipbuildingCapabilityQuery capabilities;StrategicExplorationPlanQuery exploration;std::optional<ExplorationMissionPlanner>planner;
 if(injected){logistics=[&](const StrategicInputWorldView&,int id){calls.push_back("logistics:"+std::to_string(id));if(logistics_throws)throw std::runtime_error("fixture logistics failure");CivilizationLogisticsSnapshot result;result.civilization_id=id;result.effective_coverage_ratio=coverage;return result;};capabilities=[&](const StrategicInputWorldView&,int id,std::string_view capability){const auto text=std::string(capability);calls.push_back("capability:"+std::to_string(id)+":"+text);if(capability_throw&&*capability_throw==text)throw std::runtime_error("fixture capability failure "+text);return text=="spacecraft_construction"?spacecraft:text=="experimental_interstellar_transit"?transit:false;};planner.emplace([&](OperationalReachWorldView,int,const FleetState&fleet_value,int target,InterstellarMissionKind kind){calls.push_back("reach:"+std::to_string(fleet_value.id)+":"+std::to_string(target)+":"+mission(kind));if(reach_throws)throw std::runtime_error("fixture exploration failure");return MissionReachAssessment{reach_supported,false,reach_supported?"fixture supported":"fixture blocked",std::vector<int>{fleet_value.current_system_id.value_or(-1),target},static_cast<double>(target)};});exploration=[&](ExplorationPlanningWorldView view,int fleet_id,int maximum){return planner->build_plan(view,fleet_id,maximum);};}
 CivilizationStrategicInputBuilder builder(logistics,capabilities,exploration);std::optional<CivilizationOwnState>typed;const auto error=capture([&]{typed=builder.build(input.view(),civilization_id);});std::optional<Json>result;if(typed)result=encode(*typed);Json encoded_error=nullptr;if(error)encoded_error={{"Type",error->type},{"Message",error->message}};equal(result?*result:Json(nullptr),t.at("Result"),name+".Result");equal(encoded_error,t.at("Error"),name+".Error");equal(calls,t.at("Calls"),name+".Calls");equal(fingerprint(input),before,name+".native mutation");}
}
int main(int argc,char**argv){try{check(argc==2,"usage");std::ifstream stream(argv[1]);check(stream.good(),"fixture open");Json root;stream>>root;check(root.at("Format")=="stellar-strategic-input-builder-oracle-v1","format");check(root.at("CaseCount").get<std::size_t>()==root.at("Cases").size(),"count");check(root.at("SourceOnlyNullWorld").at("Error").at("Type")=="ArgumentNullException","null type");for(const auto&t:root.at("Cases"))run(t);std::cout<<"strategic input builder parity: "<<root.at("Cases").size()<<" cases, 1 source-only null observation\n";return 0;}catch(const std::exception&e){std::cerr<<"strategic input builder parity failure: "<<e.what()<<"\n";return 1;}}
