#include <stellar/core/strategic_planning.hpp>
#include <stellar/core/knowledge.hpp>
#include <nlohmann/json.hpp>
#include <cmath>
#include <exception>
#include <fstream>
#include <iostream>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string>
using Json=nlohmann::json;using namespace stellar::core;
namespace{
[[noreturn]]void fail(const std::string&m){throw std::runtime_error(m);}void check(bool c,const std::string&m){if(!c)fail(m);}double num(const Json&v){if(v.is_number())return v.get<double>();auto s=v.get<std::string>();if(s=="NaN")return std::numeric_limits<double>::quiet_NaN();if(s=="Infinity")return std::numeric_limits<double>::infinity();if(s=="-Infinity")return-std::numeric_limits<double>::infinity();fail("bad number");}Json jnum(double v){if(std::isnan(v))return"NaN";if(std::isinf(v))return v>0?Json("Infinity"):Json("-Infinity");return v;}
void eq(const Json&a,const Json&e,const std::string&f){if(a.is_number_integer()&&e.is_number_integer()){check(a==e,f+": integer "+a.dump()+" != "+e.dump());return;}if(a.is_number()&&e.is_number()){auto x=a.get<double>(),y=e.get<double>();if((std::isnan(x)&&std::isnan(y))||x==y)return;auto s=std::max({1.,std::abs(x),std::abs(y)});check(std::abs(x-y)<=1e-10*s,f+": number "+a.dump()+" != "+e.dump());return;}if(a.is_array()&&e.is_array()){check(a.size()==e.size(),f+": size");for(size_t i=0;i<a.size();++i)eq(a[i],e[i],f+"["+std::to_string(i)+"]");return;}if(a.is_object()&&e.is_object()){check(a.size()==e.size(),f+": object size");for(auto&[k,v]:e.items()){check(a.contains(k),f+": missing "+k);eq(a.at(k),v,f+"."+k);}return;}check(a==e,f+": "+a.dump()+" != "+e.dump());}
CivilizationTraits traits(const Json&v){return{num(v.at("Aggression")),num(v.at("Territoriality")),num(v.at("Greed")),num(v.at("ScientificCuriosity")),num(v.at("RiskTolerance")),num(v.at("SurvivalPriority")),v.at("HonorBound")};}
KnownCivilization known(const Json&v){return{v.at("CivilizationId"),num(v.at("Trust")),num(v.at("EstimatedMilitaryLow")),num(v.at("EstimatedMilitaryHigh")),num(v.at("EstimateConfidence")),v.at("LastMilitaryObservationTick"),v.at("HasSharedBorder"),num(v.at("KnownTradeDependence")),num(v.at("KnownWarExhaustion")),v.at("KnownToBeAtWar"),v.at("HasDefenseTreatyWithObserver"),v.at("HasMilitaryEstimate")};}
CivilizationOwnState own(const Json&v){return{num(v.at("MilitaryStrength")),num(v.at("SupplyCoverageRatio")),num(v.at("IndustryReserve")),num(v.at("ResearchCapacity")),v.at("HasAvailableResearch"),v.at("HasUnexploredReachableSystems"),v.at("HasKnownColonizationOpportunity"),v.at("CanBuildInterstellarShips"),v.at("HasFleetCapacityShortfall")};}
StrategicKnowledgeSnapshot knowledge(const Json&v){StrategicKnowledgeSnapshot r;r.observed_at_tick=v.at("ObservedAtTick");for(auto&e:v.at("Civilizations"))r.civilizations.push_back({e.at("Key"),known(e.at("Value"))});return r;}
Json war(const WarAssessment&w){return{{"Score",jnum(w.score)},{"PerceivedStrengthRatio",jnum(w.perceived_strength_ratio)},{"IntelligenceConfidence",jnum(w.intelligence_confidence)},{"SurvivalGateTriggered",w.survival_gate_triggered},{"RecommendWar",w.recommend_war}};}
Json plan(const CivilizationStrategicPlan&p){Json ps=Json::array();for(auto&x:p.priorities)ps.push_back({{"Type",x.type},{"Score",jnum(x.score)},{"Reason",x.reason}});return{{"CivilizationId",p.civilization_id},{"GeneratedAtTick",p.generated_at_tick},{"ReviewAfterTick",p.review_after_tick},{"Priorities",ps},{"PrimaryPriority",p.priorities.empty()?Json(nullptr):ps.front()}};}
struct Err{std::string type,message;};
template<class F>std::optional<Err>capture(F&&f){try{f();return{};}catch(const std::invalid_argument&e){return Err{"ArgumentException",e.what()};}catch(const std::out_of_range&e){return Err{"ArgumentOutOfRangeException",e.what()};}catch(const std::overflow_error&e){return Err{"OverflowException",e.what()};}catch(const std::runtime_error&e){return Err{"InvalidOperationException",e.what()};}catch(const std::exception&e){return Err{"UnexpectedNativeException",e.what()};}}
void check_outcome(const std::optional<Json>&r,const std::optional<Err>&error,const Json&er,const Json&ee,const std::string&name){if(ee.is_null()){check(!error,name+": unexpected error"+(error?" "+error->type+" "+error->message:""));check(r.has_value(),name+": missing result");eq(*r,er,name+".Result");}else{check(error.has_value(),name+": expected error");check(error->type==ee.at("Type").get<std::string>(),name+": error type");check(error->message==ee.at("Message").get<std::string>(),name+": error message "+error->message);check(!r,name+": result on error");}}
void run(const Json&t){const auto name=t.at("Name").get<std::string>(),kind=t.at("Kind").get<std::string>();check(kind=="Freshness"||kind=="War"||kind=="Planner",name+": kind");check(t.at("Before")==t.at("After"),name+": source input mutation");const auto&a=t.at("Arguments");
 if(kind=="Freshness"){auto k=known(a.at("Known"));auto now=a.at("NowTick").get<std::int64_t>(),stale=a.at("StaleAfterTicks").get<std::int64_t>();struct Result{double midpoint,freshness;};std::optional<Result>typed;auto e=capture([&]{typed=Result{k.estimated_military_midpoint(),k.freshness(now,stale)};});std::optional<Json>r;if(typed)r=Json{{"Midpoint",jnum(typed->midpoint)},{"Freshness",jnum(typed->freshness)}};check_outcome(r,e,t.at("Result"),t.at("Error"),name);return;}
 if(kind=="War"){auto tr=traits(a.at("Traits"));auto k=known(a.at("Known"));auto own_m=num(a.at("OwnMilitary"));auto now=a.at("NowTick").get<std::int64_t>();auto compel=a.at("HonorCompels").get<bool>();std::optional<WarAssessment>typed;auto e=capture([&]{typed=StrategicDecisionEvaluator{}.evaluate_war(tr,own_m,k,now,compel);});std::optional<Json>r;if(typed)r=war(*typed);check_outcome(r,e,t.at("Result"),t.at("Error"),name);return;}
 auto interval=a.at("ReviewIntervalTicks").get<std::int64_t>();const auto&source_refs=t.at("SourceReferenceObservations");check(source_refs.size()==a.at("Commands").size(),name+": reference observation count");for(size_t i=0;i<source_refs.size();++i){check(source_refs.at(i).at("CommandIndex").get<size_t>()==i,name+": reference observation index");(void)source_refs.at(i).at("SameReferenceAsPrevious").get<bool>();}CivilizationStrategicPlanner planner({},interval);Json results=Json::array();for(size_t i=0;i<a.at("Commands").size();++i){const auto&c=a.at("Commands")[i];auto op=c.at("Op").get<std::string>();check(op=="Get"||op=="Invalidate"||op=="Remove"||op=="Clear",name+": command op");auto id=c.at("CivilizationId").get<int>();std::optional<CivilizationTraits>tr;std::optional<CivilizationOwnState>o;std::optional<StrategicKnowledgeSnapshot>k;auto now=c.at("NowTick").get<std::int64_t>();auto force=c.at("Force").get<bool>();if(op=="Get"){tr=traits(c.at("Traits"));o=own(c.at("Own"));k=knowledge(c.at("Knowledge"));}std::optional<CivilizationStrategicPlan>typed;auto error=capture([&]{if(op=="Get")typed=planner.get_plan(id,*tr,*o,*k,now,force);else if(op=="Invalidate")planner.invalidate(id);else if(op=="Remove")planner.remove_civilization(id);else planner.clear();});std::optional<Json>encoded;if(typed)encoded=plan(*typed);Json ej=nullptr;if(error)ej={{"Type",error->type},{"Message",error->message}};results.push_back({{"Command",c},{"Result",encoded?*encoded:Json(nullptr)},{"Error",ej}});}
 eq(results,t.at("Result"),name+".Result");if(name=="cache-force-same-tick-same-value"){check(!source_refs.at(1).at("SameReferenceAsPrevious").get<bool>(),name+": forced review must return a new source object");eq(t.at("Result").at(0).at("Result"),t.at("Result").at(1).at("Result"),name+": forced plans should have equal values");}if(name=="planner-long-max-exact-ticks"){const auto&probe=t.at("Result").at(0).at("Result");check(probe.at("GeneratedAtTick").get<std::int64_t>()==std::numeric_limits<std::int64_t>::max()-31,name+": exact generated tick");check(probe.at("ReviewAfterTick").get<std::int64_t>()==std::numeric_limits<std::int64_t>::max()-1,name+": exact review tick");}check(t.at("Error").is_null(),name+": outer error");}
}
int main(int argc,char**argv){try{KnowledgeSnapshot survey_knowledge;StrategicKnowledgeSnapshot strategic_knowledge;(void)survey_knowledge;(void)strategic_knowledge;check(argc==2,"usage");std::ifstream f(argv[1]);check(f.good(),"fixture open");Json root;f>>root;check(root.at("Format").get<std::string>()=="stellar-strategic-planning-oracle-v1","format");check(root.at("CaseCount").get<size_t>()==root.at("Cases").size(),"count");const auto&nulls=root.at("SourceOnlyNulls");check(nulls.size()==5,"null count");const std::vector<std::pair<std::string,std::string>>expected_nulls={{"war-traits","NullReferenceException"},{"war-target","NullReferenceException"},{"plan-traits","ArgumentNullException"},{"plan-own","ArgumentNullException"},{"plan-knowledge","ArgumentNullException"}};for(size_t i=0;i<expected_nulls.size();++i){check(nulls.at(i).at("Label")==expected_nulls[i].first,"null label");check(nulls.at(i).at("Error").at("Type")==expected_nulls[i].second,"null error type");check(!nulls.at(i).at("Error").at("Message").get<std::string>().empty(),"null error message");}for(auto&t:root.at("Cases"))run(t);std::cout<<"strategic planning parity: "<<root.at("Cases").size()<<" cases, 5 source-only null observations\n";return 0;}catch(const std::exception&e){std::cerr<<"strategic planning parity failure: "<<e.what()<<"\n";return 1;}}
