#include <stellar/core/strategic_runtime.hpp>
#include <nlohmann/json.hpp>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <stdexcept>
using Json=nlohmann::json;using namespace stellar::core;
namespace{
[[noreturn]]void fail(const std::string&m){throw std::runtime_error(m);}void check(bool c,const std::string&m){if(!c)fail(m);}void eq(const Json&a,const Json&e,const std::string&f){if(a.is_number_integer()&&e.is_number_integer()){check(a==e,f+": integer");return;}if(a.is_number()&&e.is_number()){double x=a,y=e;if(x==y)return;check(std::abs(x-y)<=1e-10*std::max({1.,std::abs(x),std::abs(y)}),f+": number "+a.dump()+" != "+e.dump());return;}if(a.is_array()&&e.is_array()){check(a.size()==e.size(),f+": size");for(size_t i=0;i<a.size();++i)eq(a[i],e[i],f+"["+std::to_string(i)+"]");return;}if(a.is_object()&&e.is_object()){check(a.size()==e.size(),f+": object size "+a.dump()+" != "+e.dump());for(auto&[k,v]:e.items()){check(a.contains(k),f+": missing "+k);eq(a.at(k),v,f+"."+k);}return;}check(a==e,f+": "+a.dump()+" != "+e.dump());}
Json own(const CivilizationOwnState&v){return{{"MilitaryStrength",v.military_strength},{"SupplyCoverageRatio",v.supply_coverage_ratio},{"IndustryReserve",v.industry_reserve},{"ResearchCapacity",v.research_capacity},{"HasAvailableResearch",v.has_available_research},{"HasUnexploredReachableSystems",v.has_unexplored_reachable_systems},{"HasKnownColonizationOpportunity",v.has_known_colonization_opportunity},{"CanBuildInterstellarShips",v.can_build_interstellar_ships},{"HasFleetCapacityShortfall",v.has_fleet_capacity_shortfall}};}
Json plan(const CivilizationStrategicPlan&v){Json p=Json::array();for(auto&x:v.priorities)p.push_back({{"Type",x.type},{"Score",x.score},{"Reason",x.reason}});return{{"CivilizationId",v.civilization_id},{"GeneratedAtTick",v.generated_at_tick},{"ReviewAfterTick",v.review_after_tick},{"Priorities",p}};}
Json intent(const CivilizationStrategicIntent&v){Json w=Json::array();for(int i=0;i<8;++i)w.push_back({{"Type",i},{"Value",v.get_weight(static_cast<StrategicPriorityType>(i))}});return{{"CivilizationId",v.civilization_id},{"GeneratedAtTick",v.generated_at_tick},{"ReviewAfterTick",v.review_after_tick},{"Weights",w},{"PreferredNewFleetRole",v.preferred_new_fleet_role?Json(static_cast<int>(*v.preferred_new_fleet_role)):Json(nullptr)},{"DeferNewColonization",v.defer_new_colonization},{"Summary",v.summary}};}
Json review(const CivilizationStrategicReview&v){return{{"OwnState",own(v.own_state)},{"Plan",plan(v.plan)},{"Intent",intent(v.intent)}};}
CivilizationTraits balanced(){return{.45,.35,.35,.55,.45,1.,false};}Civilization civ(int id,bool player=false,bool ancient=false){Civilization c;c.id=id;c.name="Civ "+std::to_string(id);c.traits=balanced();c.is_player=player;c.is_seeded_ancient=ancient;c.development_stage=CivilizationDevelopmentStage::WarpCapable;return c;}
struct World{std::vector<StellarSystem>s;std::vector<PlanetaryBody>b;std::vector<Civilization>c;std::vector<Colony>co;std::vector<FleetState>f;std::vector<CivilizationEconomy>e;std::vector<TechnologyState>t;std::vector<ConstructionState>q;CivilizationKnowledgeState k;std::unique_ptr<InterstellarLaneNetwork>l;explicit World(const Json&v){for(auto&j:v.at("Civilizations")){auto x=civ(j.at("Id"),j.at("IsPlayer"),j.at("IsSeededAncient"));auto&z=j.at("Traits");x.traits={z.at("Aggression"),z.at("Territoriality"),z.at("Greed"),z.at("ScientificCuriosity"),z.at("RiskTolerance"),z.at("SurvivalPriority"),z.at("HonorBound")};c.push_back(x);}for(auto&j:v.at("Economies")){CivilizationEconomy x;x.civilization_id=j.at("CivilizationId");x.industry=j.at("Industry");x.last_science_per_second=j.at("LastSciencePerSecond");e.push_back(x);}for(auto&j:v.at("Technologies")){TechnologyState x;x.civilization_id=j.at("CivilizationId");x.active_research_id=j.at("ActiveResearchId").is_null()?std::nullopt:std::optional<std::string>(j.at("ActiveResearchId"));for(auto&id:j.at("Completed"))x.completed_technology_ids.insert(id);t.push_back(std::move(x));}for(auto&j:v.at("Construction")){ConstructionState x;x.civilization_id=j.at("CivilizationId");x.completed_project_ids=j.at("Completed").get<std::vector<std::string>>();q.push_back(std::move(x));}l=std::make_unique<InterstellarLaneNetwork>(std::span<const StellarSystem>(s));}StrategicInputWorldView view(){return{s,b,c,co,f,e,t,q,k,*l};}};Json fingerprint(const World&w){Json c=Json::array(),e=Json::array(),t=Json::array(),q=Json::array();for(auto&x:w.c)c.push_back({x.id,x.is_player,x.is_seeded_ancient,x.traits.aggression,x.traits.territoriality,x.traits.greed,x.traits.scientific_curiosity,x.traits.risk_tolerance,x.traits.survival_priority,x.traits.honor_bound});for(auto&x:w.e)e.push_back({x.civilization_id,x.industry,x.last_science_per_second});for(auto&x:w.t)t.push_back({x.civilization_id,x.active_research_id,x.completed_technology_ids.values()});for(auto&x:w.q)q.push_back({x.civilization_id,x.completed_project_ids});return{{"Civilizations",c},{"Economies",e},{"Technologies",t},{"Construction",q}};}
Json sourcefp(const Json&v){Json c=Json::array(),e=Json::array(),t=Json::array(),q=Json::array();for(auto&x:v.at("Civilizations")){auto&z=x.at("Traits");c.push_back({x.at("Id"),x.at("IsPlayer"),x.at("IsSeededAncient"),z.at("Aggression"),z.at("Territoriality"),z.at("Greed"),z.at("ScientificCuriosity"),z.at("RiskTolerance"),z.at("SurvivalPriority"),z.at("HonorBound")});}for(auto&x:v.at("Economies"))e.push_back({x.at("CivilizationId"),x.at("Industry"),x.at("LastSciencePerSecond")});for(auto&x:v.at("Technologies"))t.push_back({x.at("CivilizationId"),x.at("ActiveResearchId"),x.at("Completed")});for(auto&x:v.at("Construction"))q.push_back({x.at("CivilizationId"),x.at("Completed")});return{{"Civilizations",c},{"Economies",e},{"Technologies",t},{"Construction",q}};}
CivilizationStrategicDirector director(){return CivilizationStrategicDirector(CivilizationStrategicInputBuilder([](const StrategicInputWorldView&,int id){CivilizationLogisticsSnapshot x;x.civilization_id=id;x.effective_coverage_ratio=.8;return x;}));}
struct Err{std::string type,message;};template<class F>std::optional<Err>capture(F&&f){try{f();return{};}catch(const std::invalid_argument&e){return Err{"InvalidOperationException",e.what()};}catch(const std::out_of_range&e){return Err{"ArgumentOutOfRangeException",e.what()};}catch(const std::overflow_error&e){return Err{"OverflowException",e.what()};}catch(const std::runtime_error&e){return Err{"InvalidOperationException",e.what()};}}
Json error(const std::optional<Err>&e){return e?Json{{"Type",e->type},{"Message",e->message}}:Json(nullptr);}
Json provider(const CivilizationStrategicRuntimeCoordinator&r){Json ws=Json::array(),ps=Json::array();for(int id:{2,3,9}){auto w=r.get_industry_weights(id);ws.push_back({{"Id",id},{"Value",{{"ConstructionWeight",w.construction_weight},{"ShipbuildingWeight",w.shipbuilding_weight}}}});auto p=r.get_shipbuilding_preference(id);ps.push_back({{"Id",id},{"Value",{{"PreferredNewFleetRole",p.preferred_new_fleet_role?Json(static_cast<int>(*p.preferred_new_fleet_role)):Json(nullptr)},{"DeferNewColonization",p.defer_new_colonization}}}});}return{{"IntentCount",r.published_intent_count()},{"Weights",ws},{"Preferences",ps}};}
void runtime_case(const Json&tc){std::vector<std::string>calls;std::string mode;auto query=[&](int id,std::int64_t tick){calls.push_back(std::to_string(id)+":"+std::to_string(tick));if(mode=="throw3"&&id==3)throw std::runtime_error("fixture knowledge failure");return StrategicKnowledgeSnapshot{mode=="future3"&&id==3?tick+1:tick,{}};};std::unique_ptr<CivilizationStrategicRuntimeCoordinator> r;if(tc.at("Name")=="default-empty-knowledge")r=std::make_unique<CivilizationStrategicRuntimeCoordinator>(director());else r=std::make_unique<CivilizationStrategicRuntimeCoordinator>(director(),query);for(size_t i=0;i<tc.at("Commands").size();++i){const auto&row=tc.at("Commands")[i];World w(row.at("Before"));const auto native_before=fingerprint(w);eq(native_before,sourcefp(row.at("Before")),"native decoded source input");const auto&cmd=row.at("Command");const auto op=cmd.at("Op").get<std::string>();check(op=="Advance"||op=="Reset","runtime op");mode=cmd.at("Knowledge");const auto seed=cmd.at("Seed").get<std::int64_t>();const auto text=cmd.at("Days").get<std::string>();double days=text=="NaN"?std::numeric_limits<double>::quiet_NaN():text=="-Infinity"?-std::numeric_limits<double>::infinity():std::stod(text);std::vector<CivilizationStrategicReview> rr;auto er=capture([&]{if(op=="Reset")r->reset();else rr=r->advance({seed,w.view()},days);});Json out=(er||op=="Reset")?Json(nullptr):Json::array();if(!er&&op=="Advance")for(auto&x:rr)out.push_back(review(x));eq(out,row.at("Result"),tc.at("Name").get<std::string>()+" result "+std::to_string(i));eq(error(er),row.at("Error"),"error");eq(provider(*r),row.at("Provider"),"provider");eq(calls,row.at("KnowledgeCalls"),"calls");check(row.at("Before")==row.at("After"),"source world immutable");eq(fingerprint(w),native_before,"native world immutable");}}
CivilizationTraits decode_traits(const Json&z){return{z.at("Aggression"),z.at("Territoriality"),z.at("Greed"),z.at("ScientificCuriosity"),z.at("RiskTolerance"),z.at("SurvivalPriority"),z.at("HonorBound")};} StrategicKnowledgeSnapshot decode_knowledge(const Json&v){StrategicKnowledgeSnapshot k;k.observed_at_tick=v.at("ObservedAtTick");for(auto&[key,z]:v.at("Civilizations").items()){KnownCivilization x{z.at("CivilizationId"),z.at("Trust"),z.at("EstimatedMilitaryLow"),z.at("EstimatedMilitaryHigh"),z.at("EstimateConfidence"),z.at("LastMilitaryObservationTick"),z.at("HasSharedBorder"),z.at("KnownTradeDependence"),z.at("KnownWarExhaustion"),z.at("KnownToBeAtWar"),z.at("HasDefenseTreatyWithObserver"),z.at("HasMilitaryEstimate")};k.civilizations.push_back({std::stoi(key),x});}return k;} void director_case(const Json&tc){auto d=director();for(size_t i=0;i<tc.at("Commands").size();++i){const auto&row=tc.at("Commands")[i];World w(row.at("Before"));const auto native_before=fingerprint(w);eq(native_before,sourcefp(row.at("Before")),"director decoded source input");const auto name=row.at("Name").get<std::string>(),op=row.at("Op").get<std::string>();check(op=="Review"||op=="Invalidate"||op=="Remove"||op=="Clear","director op");const int id=row.at("Id").get<int>();const auto now=row.at("Now").get<std::int64_t>();const bool force=row.at("Force").get<bool>();const auto tr=decode_traits(row.at("Traits"));const auto k=decode_knowledge(row.at("Knowledge"));std::optional<CivilizationStrategicReview> result;auto er=capture([&]{if(op=="Review")result=d.review(w.view(),id,tr,k,now,force);else if(op=="Invalidate")d.invalidate(id);else if(op=="Remove")d.remove_civilization(id);else d.clear();});eq(result?review(*result):Json(nullptr),row.at("Result"),name+" result");eq(error(er),row.at("Error"),name+" error");check(row.at("Before")==row.at("After"),name+" source immutable");eq(fingerprint(w),native_before,name+" native immutable");}}
}
int main(int argc,char**argv){try{check(argc==2,"usage");std::ifstream f(argv[1]);Json root;f>>root;check(root.at("Format")=="stellar-strategic-runtime-oracle-v1","format");check(root.at("Culture")=="InvariantCulture","culture");check(root.at("CaseCount")==root.at("Cases").size(),"count");for(auto&tc:root.at("Cases")){if(tc.at("Name")=="director-order-cache-controls")director_case(tc);else runtime_case(tc);}check(root.at("SourceOnly").size()==2,"source only count");for(auto&s:root.at("SourceOnly"))check(!s.at("Name").get<std::string>().empty(),"source metadata");Json seed_before=root.at("Cases")[0].at("Commands")[0].at("Before");World w(seed_before);std::vector<std::string>calls;CivilizationStrategicRuntimeCoordinator r(director(),[&](int id,std::int64_t tick){calls.push_back(std::to_string(id)+":"+std::to_string(tick));return StrategicKnowledgeSnapshot{tick,{}};});(void)r.advance({80,w.view()},0);const auto before_count=r.published_intent_count();auto exact=capture([&]{(void)r.advance({81,w.view()},0x1p63);});check(exact&&exact->type=="OverflowException"&&exact->message=="Accumulated strategic time cannot be represented as a native tick.","exact 2^63 rejected");check(r.campaign_seed()==81&&r.strategic_days()==0&&r.published_intent_count()==0&&r.published_preference_count()==0&&r.cached_plan_count()==0&&calls.size()==2,"seed reset before rejection");const double below=std::nextafter(0x1p63,0.);auto below_error=capture([&]{(void)r.advance({81,w.view()},below);});check(!below_error&&r.strategic_days()==below,"nextafter accepted");const auto calls_before_cross=calls.size(),intent_before_cross=r.published_intent_count(),preference_before_cross=r.published_preference_count(),cache_before_cross=r.cached_plan_count();auto cross=capture([&]{(void)r.advance({81,w.view()},1024.);});check(cross&&cross->type=="OverflowException"&&cross->message=="Accumulated strategic time cannot be represented as a native tick."&&r.strategic_days()==below&&r.campaign_seed()==81&&calls.size()==calls_before_cross&&r.published_intent_count()==intent_before_cross&&r.published_preference_count()==preference_before_cross&&r.cached_plan_count()==cache_before_cross,"cumulative crossing rejected without state change");auto retry=capture([&]{(void)r.advance({82,w.view()},.25);});check(!retry&&r.campaign_seed()==82&&r.strategic_days()==.25&&r.published_intent_count()==2&&r.published_preference_count()==2&&r.cached_plan_count()==2&&calls.size()==calls_before_cross+2,"safe retry");check(before_count==2,"initial publish");std::cout<<"strategic runtime parity: "<<root.at("Cases").size()<<" scenarios, 36 source commands, 2 source-only observations, 4 native tick-boundary probes\n";return 0;}catch(const std::exception&e){std::cerr<<"strategic runtime parity failure: "<<e.what()<<"\n";return 1;}}
