#include "native_system_workspace.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <iomanip>
#include <map>
#include <ranges>
#include <sstream>
#include <utility>

namespace stellar::native_system_ui {
namespace {
using namespace stellar::native_map;using namespace stellar::native_system;using namespace stellar::core;
constexpr Color orbit{53,91,126,125},text{220,234,248,245},muted{143,173,203,230},border{74,128,176,235};
void overlay_fill(DrawList&o,UiRect b,Color c){o.overlay.emplace_back(FilledRectangle{b,c});}
void overlay_stroke(DrawList&o,UiRect b,Color c){o.overlay.emplace_back(StrokedRectangle{b,c});}
void overlay_text(DrawList&o,float x,float y,std::string value,Color c,int size=15,float wrap=0,std::optional<UiRect> clip=std::nullopt){o.overlay.emplace_back(Text{{x,y},std::move(value),c,size,wrap,clip});}
std::string number(double value,int precision=2){std::ostringstream out;out<<std::fixed<<std::setprecision(precision)<<value;return out.str();}
Color visual_color(NativeSystemBodyVisualClass value){switch(value){case NativeSystemBodyVisualClass::rocky:return {178,143,115,255};case NativeSystemBodyVisualClass::oceanic:return {70,152,213,255};case NativeSystemBodyVisualClass::frozen:return {171,217,235,255};case NativeSystemBodyVisualClass::hot_rocky:return {222,116,66,255};case NativeSystemBodyVisualClass::gas_giant:return {211,167,114,255};case NativeSystemBodyVisualClass::ice_giant:return {111,190,215,255};case NativeSystemBodyVisualClass::moon:return {180,184,190,255};case NativeSystemBodyVisualClass::unknown_moon:return {112,137,160,255};default:return {94,132,166,255};}}
Color star_color(std::optional<StellarClass> value){if(!value)return {135,150,174,235};switch(*value){case StellarClass::MRedDwarf:return {255,119,76,230};case StellarClass::KOrangeDwarf:return {255,167,92,235};case StellarClass::GYellowDwarf:return {255,230,150,245};case StellarClass::FYellowWhiteDwarf:return {255,247,215,245};case StellarClass::AWhiteStar:return {225,236,255,245};case StellarClass::HotBlueStar:return {126,174,255,245};case StellarClass::Giant:return {255,142,88,245};case StellarClass::WhiteDwarf:return {221,236,255,235};case StellarClass::NeutronStar:return {133,218,255,250};case StellarClass::BlackHole:return {126,92,178,230};case StellarClass::Protostar:return {255,112,160,230};case StellarClass::Pulsar:return {91,229,255,250};}return {135,150,174,235};}
std::string kind_name(PlanetaryBodyKind value){switch(value){case PlanetaryBodyKind::Moon:return "Moon";case PlanetaryBodyKind::DwarfPlanet:return "Dwarf planet";default:return "Planet";}}
std::string signature_name(NativePositiveSignature value){switch(value){case NativePositiveSignature::rare_resource:return "Rare-resource signature";case NativePositiveSignature::anomaly:return "Anomalous signature";case NativePositiveSignature::activity:return "Activity signature";}return {};}
std::uint32_t mix(std::uint32_t value){value^=value>>16;value*=0x7feb352du;value^=value>>15;value*=0x846ca68bu;return value^(value>>16);}
std::optional<std::pair<Point,Point>> clipped(Point a,Point b,UiRect r){float t0=0,t1=1;const float dx=b.x-a.x,dy=b.y-a.y;const std::array p{-dx,dx,-dy,dy};const std::array q{a.x-r.x,r.x+r.width-a.x,a.y-r.y,r.y+r.height-a.y};for(std::size_t i=0;i<p.size();++i){if(p[i]==0){if(q[i]<0)return std::nullopt;continue;}const auto t=q[i]/p[i];if(p[i]<0)t0=std::max(t0,t);else t1=std::min(t1,t);if(t0>t1)return std::nullopt;}return std::pair{Point{a.x+t0*dx,a.y+t0*dy},Point{a.x+t1*dx,a.y+t1*dy}};}
bool intersects(UiRect r,float x,float y,float radius){return x+radius>=r.x&&x-radius<=r.x+r.width&&y+radius>=r.y&&y-radius<=r.y+r.height;}
} // namespace

SystemWorkspaceLayout SystemWorkspaceLayout::for_viewport(int width,int height) noexcept {
  const auto w=static_cast<float>(std::max(width,1));
  const auto h=static_cast<float>(std::max(height,1));
  const auto panel_width=std::clamp(w*.255f,248.f,380.f);
  const UiRect controls{0,130,w,42};
  const UiRect panel{w-panel_width-18.f,180.f,panel_width,std::max(1.f,h-198.f)};
  return {controls,{18,134,118,34},{146,134,124,34},panel,
          {0,172,std::max(1.f,panel.x-8.f),std::max(1.f,h-172.f)}};
}

NativeSystemWorkspace::NativeSystemWorkspace(SystemImageProvider provider):image_provider_(std::move(provider)){}
void NativeSystemWorkspace::open(NativeSystemSnapshot snapshot,int width,int height){snapshot_=std::move(snapshot);spatial_=project_system(*snapshot_);selected_body_id_.reset();dragging_=false;width_=width;height_=height;viewport_=SystemSpatialViewport::fit(*spatial_,static_cast<float>(width),static_cast<float>(height));}
void NativeSystemWorkspace::refresh(NativeSystemSnapshot snapshot){if(!snapshot_||snapshot.campaign_generation!=snapshot_->campaign_generation||snapshot.system_id!=snapshot_->system_id)throw std::invalid_argument("A system workspace can refresh only its current campaign and system.");snapshot_=std::move(snapshot);spatial_=project_system(*snapshot_);if(selected_body_id_&&std::ranges::find(snapshot_->bodies,*selected_body_id_,&NativeSystemBody::id)==snapshot_->bodies.end())selected_body_id_.reset();}
void NativeSystemWorkspace::close()noexcept{snapshot_.reset();spatial_.reset();viewport_.reset();selected_body_id_.reset();dragging_=false;width_=height_=0;}
void NativeSystemWorkspace::discard_campaign()noexcept{close();}
std::optional<int> NativeSystemWorkspace::system_id()const noexcept{return snapshot_?std::optional<int>{snapshot_->system_id}:std::nullopt;}
std::optional<std::uint64_t> NativeSystemWorkspace::campaign_generation()const noexcept{return snapshot_?std::optional<std::uint64_t>{snapshot_->campaign_generation}:std::nullopt;}
std::optional<SystemSurveyLevel> NativeSystemWorkspace::survey_level()const noexcept{return snapshot_?std::optional<SystemSurveyLevel>{snapshot_->survey_level}:std::nullopt;}
const SystemSpatialViewport *NativeSystemWorkspace::viewport()const noexcept{return viewport_?&*viewport_:nullptr;}
std::size_t NativeSystemWorkspace::visible_body_count()const noexcept{if(!spatial_||!viewport_)return 0;return static_cast<std::size_t>(std::ranges::count_if(spatial_->bodies,[&](const auto&body){return viewport_->is_body_visible(*spatial_,body);}));}
void NativeSystemWorkspace::resize(int width,int height){if(!snapshot_||!spatial_||!viewport_||width<=0||height<=0||width==width_&&height==height_)return;const auto old_fit=SystemSpatialViewport::fit(*spatial_,static_cast<float>(width_),static_cast<float>(height_));const auto next_fit=SystemSpatialViewport::fit(*spatial_,static_cast<float>(width),static_cast<float>(height));viewport_->center_x+=next_fit.center_x-old_fit.center_x;viewport_->center_y+=next_fit.center_y-old_fit.center_y;width_=width;height_=height;}
void NativeSystemWorkspace::reset_fit(int width,int height){if(!spatial_)return;width_=width;height_=height;viewport_=SystemSpatialViewport::fit(*spatial_,static_cast<float>(width),static_cast<float>(height));}
SystemWorkspaceCommand NativeSystemWorkspace::handle(const InputEvent&e,int width,int height){if(!visible())return {};resize(width,height);const auto layout=SystemWorkspaceLayout::for_viewport(width,height);if(e.type==InputEventType::EscapePressed)return {SystemWorkspaceCommandKind::close,true};if(e.type==InputEventType::PointerCancelled){dragging_=false;return {SystemWorkspaceCommandKind::none,true};}if(e.type==InputEventType::LeftPressed&&layout.back.contains(e.position))return {SystemWorkspaceCommandKind::close,true};if(e.type==InputEventType::LeftPressed&&layout.reset.contains(e.position)){dragging_=false;reset_fit(width,height);return {SystemWorkspaceCommandKind::none,true};}if(layout.inspector.contains(e.position)||layout.controls_row.contains(e.position)||!layout.world_field.contains(e.position)){if(e.type==InputEventType::LeftPressed||e.type==InputEventType::LeftReleased||e.type==InputEventType::PointerMove)dragging_=false;return {SystemWorkspaceCommandKind::none,true};}if(e.type==InputEventType::Wheel){viewport_=viewport_->zoomed_at(std::pow(1.16f,e.wheel_y),e.position.x,e.position.y,.01f,5.f);viewport_->center_x=std::clamp(viewport_->center_x,-32000.f,32000.f);viewport_->center_y=std::clamp(viewport_->center_y,-32000.f,32000.f);return {SystemWorkspaceCommandKind::none,true};}if(e.type==InputEventType::LeftPressed){if(const auto hit=viewport_->hit_body(*spatial_,e.position.x,e.position.y);hit){selected_body_id_=hit;dragging_=false;}else dragging_=true;return {SystemWorkspaceCommandKind::none,true};}if(e.type==InputEventType::PointerMove&&dragging_){*viewport_=viewport_->translated(e.delta.x,e.delta.y);viewport_->center_x=std::clamp(viewport_->center_x,-32000.f,32000.f);viewport_->center_y=std::clamp(viewport_->center_y,-32000.f,32000.f);return {SystemWorkspaceCommandKind::none,true};}if(e.type==InputEventType::LeftReleased){dragging_=false;return {SystemWorkspaceCommandKind::none,true};}return {SystemWorkspaceCommandKind::none,true};}

void NativeSystemWorkspace::render(DrawList &out,int width,int height){if(!snapshot_||!spatial_||!viewport_)return;resize(width,height);for(std::uint32_t i=0;i<96;++i){const auto a=mix(static_cast<std::uint32_t>(snapshot_->system_id)*131u+i);const auto b=mix(a+17u);const Point p{static_cast<float>(a%static_cast<std::uint32_t>(std::max(1,width))),static_cast<float>(b%static_cast<std::uint32_t>(std::max(1,height)))};out.world.emplace_back(Circle{p,(a&3u)?0.65f:1.1f,{102,133,169,static_cast<std::uint8_t>(70u+a%80u)}});}
  const auto layout=SystemWorkspaceLayout::for_viewport(width,height);const auto panel=layout.inspector;const auto field=layout.world_field;std::map<int,const SystemSpatialBodyMarker*> markers;for(const auto&m:spatial_->bodies)markers.emplace(m.body_id,&m);
  for(const auto &body:spatial_->bodies){if(body.parent_body_id&&!viewport_->is_body_visible(*spatial_,body))continue;float cx=0,cy=0;if(body.parent_body_id&&markers.contains(*body.parent_body_id)){cx=markers.at(*body.parent_body_id)->offset_x;cy=markers.at(*body.parent_body_id)->offset_y;}const auto path=orbit_path(body.orbit_radius,body.parent_body_id?0.f:static_cast<float>(body.orbital_eccentricity),body.parent_body_id?0.f:static_cast<float>(body.orbital_inclination_degrees));for(std::size_t i=1;i<path.size();++i){const auto a=viewport_->world_to_screen(cx+path[i-1].x,cy+path[i-1].y),b=viewport_->world_to_screen(cx+path[i].x,cy+path[i].y);if(const auto segment=clipped({a.x,a.y},{b.x,b.y},field))out.world.emplace_back(Line{segment->first,segment->second,orbit});}}
  const auto star_radius=star_screen_radius(viewport_->scale);const auto star=star_color(snapshot_->primary_stellar_class);out.world.emplace_back(Circle{{viewport_->center_x,viewport_->center_y},star_radius*1.45f,{star.r,star.g,star.b,35}});out.world.emplace_back(Circle{{viewport_->center_x,viewport_->center_y},star_radius,star});
  for(const auto &body:spatial_->bodies){if(!viewport_->is_body_visible(*spatial_,body))continue;const auto p=viewport_->world_to_screen(body.offset_x,body.offset_y);const auto radius=viewport_->body_radius(body);if(!intersects(field,p.x,p.y,radius+4))continue;std::shared_ptr<const RgbaImage> image;if(image_provider_)image=image_provider_({snapshot_->campaign_generation,body.body_id,snapshot_->survey_level==SystemSurveyLevel::fully_surveyed,body.visual_class,body.sol_texture_key,mix(static_cast<std::uint32_t>(body.body_id)),std::atan2(-body.offset_y,-body.offset_x)});if(image)out.world.emplace_back(Image{image,{p.x-radius,p.y-radius,2*radius,2*radius},std::nullopt,{255,255,255,255},field});else out.world.emplace_back(Circle{{p.x,p.y},radius,visual_color(body.visual_class)});if(selected_body_id_==body.body_id)out.world.emplace_back(Circle{{p.x,p.y},radius+4,{122,230,190,90}});out.world.emplace_back(Text{{p.x+radius+5,p.y-7},body.label,text,13,0,field});}
  overlay_fill(out,layout.controls_row,{5,15,28,238});overlay_stroke(out,layout.controls_row,border);overlay_fill(out,layout.back,{10,27,47,245});overlay_stroke(out,layout.back,border);overlay_text(out,40,140,"BACK",text,15);overlay_fill(out,layout.reset,{10,27,47,245});overlay_stroke(out,layout.reset,border);overlay_text(out,164,140,"RESET FIT",text,15);
  overlay_text(out,292,138,snapshot_->catalog_name,text,20);overlay_text(out,292,158,snapshot_->survey_level==SystemSurveyLevel::fully_surveyed?"FULL SURVEY":"RECONNAISSANCE",muted,12);
  overlay_fill(out,panel,{6,18,33,242});overlay_stroke(out,panel,border);float y=panel.y+14;const auto add=[&](std::string value,Color color,int size=14,float step=20){overlay_text(out,panel.x+14,y,std::move(value),color,size,panel.width-28,panel);y+=step;};add("SYSTEM INSPECTOR",text,18,31);if(const auto *body=selected_body()){add(body->name,text,17,26);add(kind_name(body->kind)+"  |  Orbit "+std::to_string(body->orbit_index),muted,13,19);add("Radius  "+number(body->radius_earth)+" Earth",text,14,27);add("POSITIVE SIGNATURES",muted,13,20);if(body->positive_signatures.empty())add("No positive signature observed yet",muted,13,20);else for(const auto signature:body->positive_signatures)add(signature_name(signature),text,13,19);if(body->details){y+=5;add("CONFIRMED ENVIRONMENT",muted,13,20);add("Mass  "+number(body->details->mass_earth)+" Earth",text,13,19);add("Gravity  "+number(body->details->gravity_g)+" g",text,13,19);add("Temperature  "+number(body->details->temperature_kelvin,0)+" K",text,13,19);add("Pressure  "+number(body->details->pressure_kpa,1)+" kPa",text,13,19);}}else add("Select a visible body",muted,14,20);}
const NativeSystemBody *NativeSystemWorkspace::selected_body()const noexcept{if(!snapshot_||!selected_body_id_)return nullptr;const auto found=std::ranges::find(snapshot_->bodies,*selected_body_id_,&NativeSystemBody::id);return found==snapshot_->bodies.end()?nullptr:&*found;}
} // namespace stellar::native_system_ui
