"""Keep the 2D fallback's procedural material identical to the production sphere."""
import argparse
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / "assets/visual/shaders/planet_identity_orbit.gdshader").read_text()
result = "// Generated by scripts/sync_planet_disc_shader.py; edit the orbital shader.\n" + source.replace(
    "shader_type spatial;", "shader_type canvas_item;").replace(
    "varying vec3 unit_position;", "").replace("void vertex(){unit_position=normalize(VERTEX);}", "").replace(
    "vec3 p=normalize(unit_position);",
    "vec2 disc=(UV-.5)*2.0; float r=length(disc); if(r>1.0){COLOR=vec4(0.0);}else{ vec3 p=vec3(disc.x,-disc.y,sqrt(max(0.0,1.0-r*r)));").replace(
    "dot(NORMAL,VIEW)", "p.z").replace("ALBEDO=color;", "COLOR=vec4(color,1.0); }")
parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true");args=parser.parse_args()
target=root / "assets/visual/shaders/planet_identity_disc.gdshader"
if args.check:
    if target.read_text()!=result:raise SystemExit("2D fallback diverged from the orbital shader; run this script without --check.")
else:target.write_text(result,encoding="utf-8")
