"""Rebuild embedded Vulkan shaders with an explicit glslang executable.

No shader compiler or SDK is required by ordinary builds or the shipped game.
The checked-in manifest lets CMake reject stale source/binary pairs offline.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("--compiler", required=True, type=Path)
args = parser.parse_args()
compiler = args.compiler.resolve()
version = subprocess.check_output([str(compiler), "--version"], text=True).strip()
header = ["// Generated by tools/compile_scene3d_shaders.py; edit engine/shaders sources.",
          "#pragma once", "#include <cstdint>", "namespace stellar::native_map::shaders {"]
files = {}
programs = ("scene3d", "tonemap", "scene3d_shadow")
with tempfile.TemporaryDirectory(prefix="stellar-scene3d-") as folder:
    for program in programs:
        for stage in ("vert", "frag"):
            relative = f"engine/shaders/{program}.{stage}"
            source = root / relative
            output = Path(folder) / f"{program}-{stage}.spv"
            subprocess.run([str(compiler), "-V", "--target-env", "vulkan1.0", "-o", str(output), str(source)], check=True)
            binary = output.read_bytes()
            words = struct.unpack(f"<{len(binary)//4}I", binary)
            header.append(f"inline constexpr std::uint32_t {program}_{stage}[] = {{")
            header.extend("  " + ",".join(f"0x{x:08x}" for x in words[i:i+8]) + "," for i in range(0,len(words),8))
            header.append("};")
            files[relative] = hashlib.sha256(source.read_bytes()).hexdigest()
header.append("}")
destination = root / "engine/src/generated/scene3d_shaders.hpp"
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text("\n".join(header)+"\n", encoding="utf-8", newline="\n")
files[destination.relative_to(root).as_posix()] = hashlib.sha256(destination.read_bytes()).hexdigest()
(root / "engine/shaders/scene3d-manifest.json").write_text(json.dumps({
    "compiler": version, "compilerSha256": hashlib.sha256(compiler.read_bytes()).hexdigest(),
    "compilerSource": "https://github.com/KhronosGroup/glslang",
    "target": "vulkan1.0", "files": files,
}, indent=2)+"\n", encoding="utf-8", newline="\n")
