add_library(stellar_native_general_settings STATIC app/native_client/native_general_settings.cpp)
target_include_directories(stellar_native_general_settings PUBLIC app/native_client)
target_link_libraries(stellar_native_general_settings PUBLIC stellar_engine PRIVATE stellar_json)
if(MSVC)
  target_compile_options(stellar_native_general_settings PRIVATE /WX)
endif()
if(BUILD_TESTING)
  add_executable(stellar_native_general_settings_tests native-tests/native_general_settings_tests.cpp)
  target_link_libraries(stellar_native_general_settings_tests PRIVATE stellar_native_general_settings)
  target_compile_definitions(stellar_native_general_settings_tests PRIVATE STELLAR_LOCALE_DIR="${CMAKE_SOURCE_DIR}/data/locale")
  add_test(NAME native_general_settings COMMAND stellar_native_general_settings_tests "${CMAKE_BINARY_DIR}/general-settings-cases")
  set_tests_properties(native_general_settings PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
  if(MSVC)
    target_compile_options(stellar_native_general_settings_tests PRIVATE /WX)
  endif()
endif()
