file(READ "${CMAKE_SOURCE_DIR}/export/native-navigation-assets.json" STELLAR_NAV_ASSETS)
string(JSON STELLAR_NAV_SCHEMA GET "${STELLAR_NAV_ASSETS}" schemaVersion)
string(JSON STELLAR_NAV_SIZE GET "${STELLAR_NAV_ASSETS}" size)
string(JSON STELLAR_NAV_COUNT LENGTH "${STELLAR_NAV_ASSETS}" assets)
if(NOT STELLAR_NAV_SCHEMA EQUAL 1 OR NOT STELLAR_NAV_SIZE EQUAL 256 OR NOT STELLAR_NAV_COUNT EQUAL 4)
  message(FATAL_ERROR "Unsupported native navigation asset declaration")
endif()
add_custom_target(stellar_native_navigation_assets)
foreach(KEY IN ITEMS research shipyard construction relations)
  string(JSON SRC GET "${STELLAR_NAV_ASSETS}" assets ${KEY} source)
  string(JSON DST GET "${STELLAR_NAV_ASSETS}" assets ${KEY} runtimePath)
  string(JSON HASH GET "${STELLAR_NAV_ASSETS}" assets ${KEY} runtimeSha256)
  string(JSON SOURCE_HASH GET "${STELLAR_NAV_ASSETS}" assets ${KEY} sourceSha256)
  if(NOT SRC STREQUAL "assets/visual/ui/navigation/nav_${KEY}.svg" OR
     NOT DST STREQUAL "assets/visual/ui/navigation/nav_${KEY}.png")
    message(FATAL_ERROR "Unreviewed native navigation asset path: ${KEY}")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${DST}" ACTUAL)
  file(SHA256 "${CMAKE_SOURCE_DIR}/${SRC}" SOURCE_ACTUAL)
  string(TOLOWER "${HASH}" HASH_LOWER)
  string(TOLOWER "${SOURCE_HASH}" SOURCE_HASH_LOWER)
  if(NOT ACTUAL STREQUAL HASH_LOWER OR NOT SOURCE_ACTUAL STREQUAL SOURCE_HASH_LOWER)
    message(FATAL_ERROR "Native navigation icon differs from reviewed content: ${DST}")
  endif()
  get_filename_component(DEST "${CMAKE_BINARY_DIR}/${DST}" DIRECTORY)
  add_custom_command(TARGET stellar_native_navigation_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${DEST}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/${DST}" "${CMAKE_BINARY_DIR}/${DST}")
endforeach()

add_library(stellar_native_navigation_art STATIC app/native_client/native_navigation_art.cpp)
target_include_directories(stellar_native_navigation_art PUBLIC app/native_client engine/include)
target_link_libraries(stellar_native_navigation_art PUBLIC stellar_native_image)
if(BUILD_TESTING)
  add_executable(stellar_native_navigation_art_tests native-tests/native_navigation_art_tests.cpp)
  target_include_directories(stellar_native_navigation_art_tests PRIVATE app/native_client engine/include)
  target_link_libraries(stellar_native_navigation_art_tests PRIVATE stellar_native_navigation_art)
  add_test(NAME native_navigation_art COMMAND stellar_native_navigation_art_tests "${CMAKE_SOURCE_DIR}")
  set_tests_properties(native_navigation_art PROPERTIES TIMEOUT 30)
  if(MSVC)
    target_compile_options(stellar_native_navigation_art_tests PRIVATE /WX)
  endif()
endif()
