file(READ "${CMAKE_SOURCE_DIR}/export/native-small-body-assets.json" SMALL_BODY_ASSETS)
string(JSON SMALL_BODY_COUNT LENGTH "${SMALL_BODY_ASSETS}" assets)
if(NOT SMALL_BODY_COUNT EQUAL 36)
  message(FATAL_ERROR "Small-body artwork requires all 36 named sources")
endif()
add_custom_target(stellar_native_small_body_assets)
foreach(INDEX RANGE 0 35)
  string(JSON SOURCE GET "${SMALL_BODY_ASSETS}" assets ${INDEX} source)
  string(JSON RUNTIME GET "${SMALL_BODY_ASSETS}" assets ${INDEX} runtimePath)
  string(JSON EXPECTED GET "${SMALL_BODY_ASSETS}" assets ${INDEX} sha256)
  if(NOT SOURCE MATCHES "^assets/visual/small-bodies/[^/]+ [1-4]\\.png$" OR NOT SOURCE STREQUAL RUNTIME)
    message(FATAL_ERROR "Invalid small-body source path")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${SOURCE}" ACTUAL)
  if(NOT ACTUAL STREQUAL EXPECTED)
    message(FATAL_ERROR "Small-body asset differs from reviewed content: ${SOURCE}")
  endif()
  add_custom_command(TARGET stellar_native_small_body_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/assets/visual/small-bodies"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/${SOURCE}" "${CMAKE_BINARY_DIR}/${RUNTIME}")
endforeach()
