# Only the native graphical client packages these approved audio streams.
file(READ "${CMAKE_SOURCE_DIR}/export/native-audio-assets.json" STELLAR_AUDIO_ASSETS)
string(JSON STELLAR_AUDIO_SCHEMA GET "${STELLAR_AUDIO_ASSETS}" schemaVersion)
string(JSON STELLAR_AUDIO_COUNT LENGTH "${STELLAR_AUDIO_ASSETS}" assets)
if(NOT STELLAR_AUDIO_SCHEMA EQUAL 1 OR NOT STELLAR_AUDIO_COUNT EQUAL 8)
  message(FATAL_ERROR "Unsupported native audio asset declaration")
endif()
file(SHA256 "${CMAKE_SOURCE_DIR}/third_party/dr_mp3/dr_mp3.h" STELLAR_DR_MP3_SHA256)
if(NOT STELLAR_DR_MP3_SHA256 STREQUAL "997b7ee18de6e6b81e2a83f1ea9fc62aef25c62b28d48db95635f49e65de0a2f")
  message(FATAL_ERROR "Vendored dr_mp3 differs from the reviewed header; review and pin dependency changes explicitly")
endif()
add_custom_target(stellar_native_audio_assets)
foreach(STELLAR_AUDIO_KEY IN ITEMS music ui-hover ui-confirm discovery-reveal construction-complete ship-launch strategic-alert license)
  if(STELLAR_AUDIO_KEY STREQUAL "license")
    set(STELLAR_AUDIO_EXPECTED "third_party/dr_mp3/LICENSE.txt")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "Licenses/dr_mp3-MIT-0.txt")
  elseif(STELLAR_AUDIO_KEY STREQUAL "music")
    set(STELLAR_AUDIO_EXPECTED "assets/audio/music/claimed-by-the-void-loop.mp3")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "${STELLAR_AUDIO_EXPECTED}")
  else()
    set(STELLAR_AUDIO_EXPECTED "assets/audio/sfx/${STELLAR_AUDIO_KEY}.wav")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "${STELLAR_AUDIO_EXPECTED}")
  endif()
  string(JSON STELLAR_AUDIO_SOURCE GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} source)
  string(JSON STELLAR_AUDIO_RUNTIME GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} runtimePath)
  string(JSON STELLAR_AUDIO_EXPECTED_HASH GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} sha256)
  if(NOT STELLAR_AUDIO_SOURCE STREQUAL STELLAR_AUDIO_EXPECTED OR
     NOT STELLAR_AUDIO_RUNTIME STREQUAL STELLAR_AUDIO_EXPECTED_RUNTIME)
    message(FATAL_ERROR "Unreviewed native audio ${STELLAR_AUDIO_KEY} path")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${STELLAR_AUDIO_SOURCE}" STELLAR_AUDIO_ACTUAL_HASH)
  if(NOT STELLAR_AUDIO_ACTUAL_HASH STREQUAL STELLAR_AUDIO_EXPECTED_HASH)
    message(FATAL_ERROR "Native audio ${STELLAR_AUDIO_KEY} differs from reviewed content")
  endif()
  get_filename_component(STELLAR_AUDIO_DESTINATION "${CMAKE_BINARY_DIR}/${STELLAR_AUDIO_RUNTIME}" DIRECTORY)
  add_custom_command(TARGET stellar_native_audio_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${STELLAR_AUDIO_DESTINATION}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
      "${CMAKE_SOURCE_DIR}/${STELLAR_AUDIO_SOURCE}" "${CMAKE_BINARY_DIR}/${STELLAR_AUDIO_RUNTIME}")
endforeach()
