# Only the native graphical client packages these approved audio files.
file(READ "${CMAKE_SOURCE_DIR}/export/native-audio-assets.json" STELLAR_AUDIO_ASSETS)
string(JSON STELLAR_AUDIO_SCHEMA GET "${STELLAR_AUDIO_ASSETS}" schemaVersion)
string(JSON STELLAR_AUDIO_COUNT LENGTH "${STELLAR_AUDIO_ASSETS}" assets)
if(NOT STELLAR_AUDIO_SCHEMA EQUAL 1 OR NOT STELLAR_AUDIO_COUNT EQUAL 8)
  message(FATAL_ERROR "Unsupported native audio asset declaration")
endif()
add_custom_target(stellar_native_audio_assets)
foreach(STELLAR_AUDIO_KEY IN ITEMS main-music ui-hover ui-confirm discovery-reveal construction-complete ship-launch strategic-alert credits)
  if(STELLAR_AUDIO_KEY STREQUAL "main-music")
    set(STELLAR_AUDIO_EXPECTED_SOURCE "assets/audio/music/claimed-by-the-void-loop.mp3")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "${STELLAR_AUDIO_EXPECTED_SOURCE}")
  elseif(STELLAR_AUDIO_KEY STREQUAL "credits")
    set(STELLAR_AUDIO_EXPECTED_SOURCE "docs/engine/NATIVE_AUDIO_SOURCES.md")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "Licenses/Audio-sources.md")
  else()
    set(STELLAR_AUDIO_EXPECTED_SOURCE "assets/audio/sfx/${STELLAR_AUDIO_KEY}.wav")
    set(STELLAR_AUDIO_EXPECTED_RUNTIME "${STELLAR_AUDIO_EXPECTED_SOURCE}")
  endif()
  string(JSON STELLAR_AUDIO_SOURCE GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} source)
  string(JSON STELLAR_AUDIO_RUNTIME GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} runtimePath)
  string(JSON STELLAR_AUDIO_EXPECTED_HASH GET "${STELLAR_AUDIO_ASSETS}" assets ${STELLAR_AUDIO_KEY} sha256)
  if(NOT STELLAR_AUDIO_SOURCE STREQUAL STELLAR_AUDIO_EXPECTED_SOURCE OR NOT STELLAR_AUDIO_RUNTIME STREQUAL STELLAR_AUDIO_EXPECTED_RUNTIME)
    message(FATAL_ERROR "Unreviewed native audio ${STELLAR_AUDIO_KEY} path")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${STELLAR_AUDIO_SOURCE}" STELLAR_AUDIO_ACTUAL_HASH)
  if(NOT STELLAR_AUDIO_ACTUAL_HASH STREQUAL STELLAR_AUDIO_EXPECTED_HASH)
    message(FATAL_ERROR "Native audio ${STELLAR_AUDIO_KEY} differs from reviewed content")
  endif()
  get_filename_component(STELLAR_AUDIO_DESTINATION "${CMAKE_BINARY_DIR}/${STELLAR_AUDIO_RUNTIME}" DIRECTORY)
  add_custom_command(TARGET stellar_native_audio_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${STELLAR_AUDIO_DESTINATION}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/${STELLAR_AUDIO_SOURCE}" "${CMAKE_BINARY_DIR}/${STELLAR_AUDIO_RUNTIME}")
endforeach()
