add_library(stellar_native_video_settings STATIC
  app/native_client/native_video_settings.cpp app/native_client/native_video_controller.cpp)
target_include_directories(stellar_native_video_settings PUBLIC app/native_client)
target_link_libraries(stellar_native_video_settings PUBLIC stellar_engine PRIVATE stellar_json)
if(MSVC)
  target_compile_options(stellar_native_video_settings PRIVATE /WX)
endif()
if(BUILD_TESTING)
  foreach(kind settings controller)
    add_executable(stellar_native_video_${kind}_tests native-tests/native_video_${kind}_tests.cpp)
    target_link_libraries(stellar_native_video_${kind}_tests PRIVATE stellar_native_video_settings)
    add_test(NAME native_video_${kind} COMMAND stellar_native_video_${kind}_tests)
    set_tests_properties(native_video_${kind} PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
    if(MSVC)
      target_compile_options(stellar_native_video_${kind}_tests PRIVATE /WX)
    endif()
  endforeach()
endif()

if(BUILD_TESTING)
  add_executable(stellar_native_video_platform_tests native-tests/native_video_platform_tests.cpp)
  target_link_libraries(stellar_native_video_platform_tests PRIVATE stellar_native_platform SDL3::SDL3)
  add_test(NAME native_video_platform COMMAND stellar_native_video_platform_tests
    "${CMAKE_SOURCE_DIR}/assets/visual/fonts/Rajdhani-SemiBold.ttf")
  set_tests_properties(native_video_platform PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE
    SKIP_REGULAR_EXPRESSION "GPU device creation failed")
  if(MSVC)
    target_compile_options(stellar_native_video_platform_tests PRIVATE /WX)
  endif()
endif()
