file(READ "${CMAKE_SOURCE_DIR}/export/native-navigation-assets.json" STELLAR_NAV_ASSETS)
string(JSON STELLAR_NAV_SCHEMA GET "${STELLAR_NAV_ASSETS}" schemaVersion)
string(JSON STELLAR_NAV_SIZE GET "${STELLAR_NAV_ASSETS}" size)
string(JSON STELLAR_NAV_COUNT LENGTH "${STELLAR_NAV_ASSETS}" assets)
if(NOT STELLAR_NAV_SCHEMA EQUAL 1 OR NOT STELLAR_NAV_SIZE EQUAL 256 OR NOT STELLAR_NAV_COUNT EQUAL 14)
  message(FATAL_ERROR "Unsupported native navigation asset declaration")
endif()
set(STELLAR_NAV_KEYS galaxy home inspection zoom_in zoom_out economy research shipyard construction exploration colonization logistics relations settings)
set(STELLAR_NAV_galaxy_PATH "assets/visual/space/campaign-galaxy-four-arm-v1.png")
set(STELLAR_NAV_home_PATH "assets/visual/sol/earth.jpg")
set(STELLAR_NAV_inspection_PATH "assets/visual/sol/earth-map.jpg")
set(STELLAR_NAV_zoom_in_PATH "assets/visual/space/deep-field-v2.png")
set(STELLAR_NAV_zoom_out_PATH "assets/visual/space/galactic-dust-detail-v1.png")
set(STELLAR_NAV_economy_PATH "assets/visual/catalog/portraits/research-economic_trade.png")
set(STELLAR_NAV_research_PATH "assets/visual/catalog/portraits/research-foundations.png")
set(STELLAR_NAV_shipyard_PATH "assets/visual/ships/interstellar-bulk-freighter.png")
set(STELLAR_NAV_construction_PATH "assets/visual/catalog/portraits/human_station_industry--l1.png")
set(STELLAR_NAV_exploration_PATH "assets/visual/ships/pathfinder-scout.jpg")
set(STELLAR_NAV_colonization_PATH "assets/visual/ships/interstellar-colony-ship.jpg")
set(STELLAR_NAV_logistics_PATH "assets/visual/ships/resource-outpost-ship.png")
set(STELLAR_NAV_relations_PATH "assets/visual/catalog/portraits/research-social_admin.png")
set(STELLAR_NAV_settings_PATH "assets/visual/catalog/portraits/research-computing.png")
add_custom_target(stellar_native_navigation_assets)
foreach(KEY IN LISTS STELLAR_NAV_KEYS)
  string(JSON SRC GET "${STELLAR_NAV_ASSETS}" assets ${KEY} source)
  string(JSON DST GET "${STELLAR_NAV_ASSETS}" assets ${KEY} runtimePath)
  string(JSON HASH GET "${STELLAR_NAV_ASSETS}" assets ${KEY} runtimeSha256)
  string(JSON SOURCE_HASH GET "${STELLAR_NAV_ASSETS}" assets ${KEY} sourceSha256)
  if(NOT SRC STREQUAL "${STELLAR_NAV_${KEY}_PATH}" OR NOT DST STREQUAL "${STELLAR_NAV_${KEY}_PATH}")
    message(FATAL_ERROR "Unapproved native navigation photo path: ${KEY}")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${DST}" ACTUAL)
  file(SHA256 "${CMAKE_SOURCE_DIR}/${SRC}" SOURCE_ACTUAL)
  string(TOLOWER "${HASH}" HASH_LOWER)
  string(TOLOWER "${SOURCE_HASH}" SOURCE_HASH_LOWER)
  if(NOT ACTUAL STREQUAL HASH_LOWER OR NOT SOURCE_ACTUAL STREQUAL SOURCE_HASH_LOWER)
    message(FATAL_ERROR "Native navigation photo differs from reviewed content: ${DST}")
  endif()
  get_filename_component(DEST "${CMAKE_BINARY_DIR}/${DST}" DIRECTORY)
  add_custom_command(TARGET stellar_native_navigation_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${DEST}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/${DST}" "${CMAKE_BINARY_DIR}/${DST}")
endforeach()
add_library(stellar_native_navigation_art STATIC app/native_client/native_navigation_art.cpp)
target_include_directories(stellar_native_navigation_art PUBLIC app/native_client engine/include)
target_link_libraries(stellar_native_navigation_art PUBLIC stellar_native_image)
if(BUILD_TESTING)
  add_executable(stellar_native_navigation_art_tests native-tests/native_navigation_art_tests.cpp)
  target_include_directories(stellar_native_navigation_art_tests PRIVATE app/native_client engine/include)
  target_link_libraries(stellar_native_navigation_art_tests PRIVATE stellar_native_navigation_art)
  add_test(NAME native_navigation_art COMMAND stellar_native_navigation_art_tests "${CMAKE_SOURCE_DIR}")
  set_tests_properties(native_navigation_art PROPERTIES TIMEOUT 30)
  if(MSVC)
    target_compile_options(stellar_native_navigation_art_tests PRIVATE /WX)
  endif()
endif()
