file(READ "${CMAKE_SOURCE_DIR}/assets/visual/branding/icon-provenance-v1.json" STELLAR_BRANDING_PROVENANCE)
string(JSON STELLAR_ICON_PNG_HASH GET "${STELLAR_BRANDING_PROVENANCE}" files stellar-continuum-icon-v1.png)
string(JSON STELLAR_ICON_ICO_HASH GET "${STELLAR_BRANDING_PROVENANCE}" files stellar-continuum-v1.ico)
foreach(ASSET IN ITEMS stellar-continuum-icon-v1.png stellar-continuum-v1.ico)
  file(SHA256 "${CMAKE_SOURCE_DIR}/assets/visual/branding/${ASSET}" ACTUAL_HASH)
  if(ASSET STREQUAL "stellar-continuum-icon-v1.png")
    set(EXPECTED_HASH "${STELLAR_ICON_PNG_HASH}")
  else()
    set(EXPECTED_HASH "${STELLAR_ICON_ICO_HASH}")
  endif()
  string(TOLOWER "${EXPECTED_HASH}" EXPECTED_HASH_LOWER)
  if(NOT ACTUAL_HASH STREQUAL EXPECTED_HASH_LOWER)
    message(FATAL_ERROR "Native application icon differs from its recorded provenance: ${ASSET}")
  endif()
endforeach()
