# Only the native graphical client packages these approved original images.
file(READ "${CMAKE_SOURCE_DIR}/export/native-celestial-assets.json" STELLAR_CELESTIAL_ASSETS)
string(JSON STELLAR_CELESTIAL_SCHEMA GET "${STELLAR_CELESTIAL_ASSETS}" schemaVersion)
string(JSON STELLAR_CELESTIAL_COUNT LENGTH "${STELLAR_CELESTIAL_ASSETS}" assets)
if(NOT STELLAR_CELESTIAL_SCHEMA EQUAL 1 OR NOT STELLAR_CELESTIAL_COUNT EQUAL 27)
  message(FATAL_ERROR "Unsupported native celestial asset declaration")
endif()
add_custom_target(stellar_native_celestial_assets)
foreach(STELLAR_BODY_KEY IN ITEMS mercury venus earth mars jupiter saturn uranus neptune moon credits
    earth-map earth-night-map earth-clouds building-portraits-v1 colony-panorama-v1 globe-credits planetary-credits
    mars-map jupiter-map authored-planet-credits mercury-map venus-map earth-authored-map moon-map saturn-map uranus-map neptune-map)
  if(STELLAR_BODY_KEY STREQUAL "credits")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "docs/SOL_VISUAL_SOURCES.md")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "Licenses/Sol-visual-sources.md")
  elseif(STELLAR_BODY_KEY STREQUAL "globe-credits")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "docs/IMMERSIVE_TEXTURE_PROVENANCE.md")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "Licenses/Globe-texture-provenance.md")
  elseif(STELLAR_BODY_KEY STREQUAL "planetary-credits")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "assets/visual/planetary/ARTWORK.md")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "Licenses/Planetary-artwork.md")
  elseif(STELLAR_BODY_KEY STREQUAL "authored-planet-credits")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "docs/AUTHORED_PLANET_TEXTURE_PROVENANCE.md")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "Licenses/Authored-planet-texture-provenance.md")
  elseif(STELLAR_BODY_KEY STREQUAL "earth-authored-map")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "assets/visual/sol/earth-map.png")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "${STELLAR_CELESTIAL_EXPECTED_SOURCE}")
  elseif(STELLAR_BODY_KEY MATCHES "^(mars|jupiter|mercury|venus|moon|saturn|uranus|neptune)-map$")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "assets/visual/sol/${STELLAR_BODY_KEY}.png")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "${STELLAR_CELESTIAL_EXPECTED_SOURCE}")
  elseif(STELLAR_BODY_KEY STREQUAL "building-portraits-v1" OR STELLAR_BODY_KEY STREQUAL "colony-panorama-v1")
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "assets/visual/planetary/${STELLAR_BODY_KEY}.png")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "${STELLAR_CELESTIAL_EXPECTED_SOURCE}")
  else()
    set(STELLAR_CELESTIAL_EXPECTED_SOURCE "assets/visual/sol/${STELLAR_BODY_KEY}.jpg")
    set(STELLAR_CELESTIAL_EXPECTED_RUNTIME "${STELLAR_CELESTIAL_EXPECTED_SOURCE}")
  endif()
  string(JSON STELLAR_CELESTIAL_SOURCE GET "${STELLAR_CELESTIAL_ASSETS}" assets ${STELLAR_BODY_KEY} source)
  string(JSON STELLAR_CELESTIAL_RUNTIME GET "${STELLAR_CELESTIAL_ASSETS}" assets ${STELLAR_BODY_KEY} runtimePath)
  string(JSON STELLAR_CELESTIAL_EXPECTED_HASH GET "${STELLAR_CELESTIAL_ASSETS}" assets ${STELLAR_BODY_KEY} sha256)
  if(NOT STELLAR_CELESTIAL_SOURCE STREQUAL STELLAR_CELESTIAL_EXPECTED_SOURCE OR
     NOT STELLAR_CELESTIAL_RUNTIME STREQUAL STELLAR_CELESTIAL_EXPECTED_RUNTIME)
    message(FATAL_ERROR "Unreviewed native celestial ${STELLAR_BODY_KEY} path")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${STELLAR_CELESTIAL_SOURCE}" STELLAR_CELESTIAL_ACTUAL_HASH)
  if(NOT STELLAR_CELESTIAL_ACTUAL_HASH STREQUAL STELLAR_CELESTIAL_EXPECTED_HASH)
    message(FATAL_ERROR "Native celestial ${STELLAR_BODY_KEY} differs from reviewed content")
  endif()
  get_filename_component(STELLAR_CELESTIAL_DESTINATION "${CMAKE_BINARY_DIR}/${STELLAR_CELESTIAL_RUNTIME}" DIRECTORY)
  add_custom_command(TARGET stellar_native_celestial_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${STELLAR_CELESTIAL_DESTINATION}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
      "${CMAKE_SOURCE_DIR}/${STELLAR_CELESTIAL_SOURCE}" "${CMAKE_BINARY_DIR}/${STELLAR_CELESTIAL_RUNTIME}")
endforeach()
