# Only the current observer-facing research illustrations are runtime assets.
file(READ "${CMAKE_SOURCE_DIR}/export/native-research-assets.json" RESEARCH_ART_MANIFEST)
string(JSON RESEARCH_ART_SCHEMA GET "${RESEARCH_ART_MANIFEST}" schemaVersion)
string(JSON RESEARCH_ART_COUNT LENGTH "${RESEARCH_ART_MANIFEST}" assets)
if(NOT RESEARCH_ART_SCHEMA EQUAL 1 OR RESEARCH_ART_COUNT LESS 3)
  message(FATAL_ERROR "Unsupported native research artwork declaration")
endif()
add_custom_target(stellar_native_research_assets)
math(EXPR RESEARCH_ART_LAST "${RESEARCH_ART_COUNT} - 1")
foreach(INDEX RANGE 0 ${RESEARCH_ART_LAST})
  string(JSON SRC GET "${RESEARCH_ART_MANIFEST}" assets ${INDEX} path)
  string(JSON EXPECTED GET "${RESEARCH_ART_MANIFEST}" assets ${INDEX} sha256)
  if(NOT SRC STREQUAL "assets/visual/catalog/catalog.json" AND
     NOT SRC STREQUAL "assets/visual/catalog/production/provenance.json" AND
     NOT SRC MATCHES "^assets/visual/catalog/(thumbnails|portraits)/research-[a-z_]+[.]png$")
    message(FATAL_ERROR "Unreviewed native research artwork path: ${SRC}")
  endif()
  file(SHA256 "${CMAKE_SOURCE_DIR}/${SRC}" ACTUAL)
  if(NOT ACTUAL STREQUAL EXPECTED)
    message(FATAL_ERROR "Research artwork differs from reviewed content: ${SRC}")
  endif()
  get_filename_component(DEST "${CMAKE_BINARY_DIR}/${SRC}" DIRECTORY)
  add_custom_command(TARGET stellar_native_research_assets POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${DEST}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/${SRC}" "${CMAKE_BINARY_DIR}/${SRC}")
endforeach()
add_library(stellar_native_research_art STATIC app/native_client/native_research_art.cpp)
target_include_directories(stellar_native_research_art PUBLIC app/native_client)
target_link_libraries(stellar_native_research_art PUBLIC stellar_native_image PRIVATE stellar_json)
if(BUILD_TESTING)
  add_executable(stellar_native_research_art_tests native-tests/native_research_art_tests.cpp)
  target_link_libraries(stellar_native_research_art_tests PRIVATE stellar_native_research_art stellar_json)
  add_test(NAME native_research_art COMMAND stellar_native_research_art_tests "${CMAKE_SOURCE_DIR}")
  set_tests_properties(native_research_art PROPERTIES TIMEOUT 30)
endif()
