add_library(stellar_native_audio_settings STATIC app/native_client/native_audio_settings.cpp)
target_include_directories(stellar_native_audio_settings PUBLIC app/native_client)
target_link_libraries(stellar_native_audio_settings PUBLIC stellar_engine PRIVATE stellar_json)
if(MSVC)
  target_compile_options(stellar_native_audio_settings PRIVATE /WX)
endif()
if(BUILD_TESTING)
  add_executable(stellar_native_audio_settings_tests native-tests/native_audio_settings_tests.cpp)
  target_link_libraries(stellar_native_audio_settings_tests PRIVATE stellar_native_audio_settings)
  add_test(NAME native_audio_settings COMMAND stellar_native_audio_settings_tests
    "${CMAKE_BINARY_DIR}/audio-settings-cases")
  set_tests_properties(native_audio_settings PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
  if(MSVC)
    target_compile_options(stellar_native_audio_settings_tests PRIVATE /WX)
  endif()
endif()
