# Invoked only by the opt-in native client target. Headless builds stay offline.
if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "The pinned native client dependency supports MSVC Windows x64")
endif()
file(READ "${CMAKE_SOURCE_DIR}/third_party/SDL3/runtime-lock.json" STELLAR_SDL_LOCK)
foreach(field archiveUrl archiveSha256 archiveRoot)
  string(JSON STELLAR_SDL_${field} GET "${STELLAR_SDL_LOCK}" ${field})
endforeach()
set(STELLAR_SDL3_ARCHIVE "" CACHE FILEPATH "Optional offline SDL archive; the pinned hash is mandatory")
set(STELLAR_SDL_CACHE "${CMAKE_BINARY_DIR}/_deps/stellar-sdl3")
file(MAKE_DIRECTORY "${STELLAR_SDL_CACHE}")
if(STELLAR_SDL3_ARCHIVE)
  get_filename_component(STELLAR_SDL_ARCHIVE "${STELLAR_SDL3_ARCHIVE}" ABSOLUTE)
  if(NOT EXISTS "${STELLAR_SDL_ARCHIVE}")
    message(FATAL_ERROR "Offline SDL archive is missing: ${STELLAR_SDL_ARCHIVE}")
  endif()
  file(SHA256 "${STELLAR_SDL_ARCHIVE}" STELLAR_SDL_ACTUAL_HASH)
  if(NOT STELLAR_SDL_ACTUAL_HASH STREQUAL STELLAR_SDL_archiveSha256)
    message(FATAL_ERROR "Offline SDL archive does not match the reviewed release")
  endif()
else()
  set(STELLAR_SDL_ARCHIVE "${STELLAR_SDL_CACHE}/SDL3-reviewed.zip")
  file(DOWNLOAD "${STELLAR_SDL_archiveUrl}" "${STELLAR_SDL_ARCHIVE}"
    EXPECTED_HASH "SHA256=${STELLAR_SDL_archiveSha256}" TLS_VERIFY ON
    TIMEOUT 120 STATUS STELLAR_SDL_DOWNLOAD_STATUS)
  list(GET STELLAR_SDL_DOWNLOAD_STATUS 0 STELLAR_SDL_DOWNLOAD_CODE)
  if(NOT STELLAR_SDL_DOWNLOAD_CODE EQUAL 0)
    message(FATAL_ERROR "Pinned SDL download failed: ${STELLAR_SDL_DOWNLOAD_STATUS}")
  endif()
endif()
# Refresh only the verified archive contents; never consume an arbitrary SDK.
file(ARCHIVE_EXTRACT INPUT "${STELLAR_SDL_ARCHIVE}" DESTINATION "${STELLAR_SDL_CACHE}")
set(STELLAR_SDL_ROOT "${STELLAR_SDL_CACHE}/${STELLAR_SDL_archiveRoot}")
foreach(field runtime importLibrary license)
  string(JSON STELLAR_SDL_RELATIVE GET "${STELLAR_SDL_LOCK}" ${field} path)
  string(JSON STELLAR_SDL_EXPECTED GET "${STELLAR_SDL_LOCK}" ${field} sha256)
  set(STELLAR_SDL_${field} "${STELLAR_SDL_ROOT}/${STELLAR_SDL_RELATIVE}")
  file(SHA256 "${STELLAR_SDL_${field}}" STELLAR_SDL_ACTUAL_HASH)
  if(NOT STELLAR_SDL_ACTUAL_HASH STREQUAL STELLAR_SDL_EXPECTED)
    message(FATAL_ERROR "SDL ${field} differs from the reviewed dependency")
  endif()
endforeach()
add_library(SDL3::SDL3 SHARED IMPORTED GLOBAL)
set_target_properties(SDL3::SDL3 PROPERTIES
  IMPORTED_LOCATION "${STELLAR_SDL_runtime}"
  IMPORTED_IMPLIB "${STELLAR_SDL_importLibrary}"
  INTERFACE_INCLUDE_DIRECTORIES "${STELLAR_SDL_ROOT}/include")
