using System.Globalization;using System.Security.Cryptography;using System.Text;using System.Text.Json;using Game.Simulation.AI;using Game.Simulation.Construction;using Game.Simulation.Knowledge;using Game.Simulation.Models;using Game.Simulation.Research;using Game.Simulation.Research.Adaptive;using Game.Simulation.Shipbuilding;using Game.Simulation.Species;
CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;CultureInfo.CurrentUICulture=CultureInfo.InvariantCulture;var dr=args.Length>0?args[0]:"<missing>";var df=args.Length>1?args[1]:"<missing>";
try{if(args.Length!=2)throw new ArgumentException("Expected canonical research directory and output fixture path.");var root=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);string Fingerprint(){using var h=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);foreach(var p in Directory.GetFiles(root,"*.json").OrderBy(Path.GetFileName,StringComparer.Ordinal)){h.AppendData(Encoding.UTF8.GetBytes(Path.GetFileName(p)));h.AppendData(File.ReadAllBytes(p));}return Convert.ToHexString(h.GetHashAndReset());}object Error(Exception?e)=>e is null?null!:new{Type=e.GetType().Name,e.Message};object Number(double v)=>double.IsNaN(v)?"NaN":v==double.PositiveInfinity?"Infinity":v==double.NegativeInfinity?"-Infinity":v;var options=new JsonSerializerOptions{PropertyNamingPolicy=JsonNamingPolicy.CamelCase,Converters={new System.Text.Json.Serialization.JsonStringEnumConverter(JsonNamingPolicy.CamelCase)}};
CivilizationState Civ(int id,bool ancient=false,CivilizationDevelopmentStage stage=CivilizationDevelopmentStage.WarpCapable,bool player=true)=>new(id,$"C{id}",0,CivilizationArchetype.Adaptive,CivilizationTraits.Balanced,player,stage,ancient,SpeciesId:SpeciesCatalog.TerranBaselineId);
GalaxyState World(params CivilizationState[] civs)=>new(){Seed=42,Systems=Array.Empty<StarSystemState>(),PlanetaryBodies=Array.Empty<PlanetaryBodyState>(),Civilizations=civs.ToList(),Fleets=new List<FleetState>(),Colonies=new List<ColonyState>(),Economies=civs.Select(c=>new CivilizationEconomyState{CivilizationId=c.Id,Credits=100}).ToArray(),Technologies=new List<TechnologyState>(),ConstructionStates=civs.Select(c=>new ConstructionState{CivilizationId=c.Id}).ToList(),ShipyardStates=new List<ShipyardState>(),PlayerCivilizationId=civs.FirstOrDefault()?.Id??0,Knowledge=new CivilizationKnowledgeState()};
GalaxyState WorldWithoutEconomy(CivilizationState civ)=>new(){Seed=42,Systems=Array.Empty<StarSystemState>(),PlanetaryBodies=Array.Empty<PlanetaryBodyState>(),Civilizations=new List<CivilizationState>{civ},Fleets=new List<FleetState>(),Colonies=new List<ColonyState>(),Economies=Array.Empty<CivilizationEconomyState>(),Technologies=new List<TechnologyState>(),ConstructionStates=new List<ConstructionState>{new(){CivilizationId=civ.Id}},ShipyardStates=new List<ShipyardState>(),PlayerCivilizationId=civ.Id,Knowledge=new CivilizationKnowledgeState()};
var beforeLoad=Fingerprint();var runtime=AdaptiveResearchStrategicRuntime.LoadFromDirectory(root);var factory=new AdaptiveResearchCampaignFactory(runtime);var codec=new AdaptiveResearchCampaignSnapshotCodec(runtime);var simulation=new AdaptiveResearchCampaignSimulation();if(Fingerprint()!=beforeLoad)throw new InvalidOperationException("Load changed inputs.");object Projection(GalaxyState w,AdaptiveResearchCampaignState c)=>new{w.Seed,Civilizations=w.Civilizations.Select(x=>new{x.Id,x.SpeciesId,x.IsPlayer,x.IsSeededAncient,x.DevelopmentStage}).ToArray(),Economies=w.Economies.Select(e=>new{e.CivilizationId,Credits=Number(e.Credits),LastResearchSpendingPerDay=Number(e.LastResearchSpendingPerDay),LastResearchFundingFraction=Number(e.LastResearchFundingFraction),LastCreditsPerSecond=Number(e.LastCreditsPerSecond)}).ToArray(),Construction=w.ConstructionStates.Select(x=>new{x.CivilizationId,CompletedProjectIds=x.CompletedProjectIds.ToArray()}).ToArray(),Colonies=w.Colonies.Select(x=>new{x.Id,x.CivilizationId,x.SystemId,x.Name,x.PopulationMillions,Buildings=x.SurfaceBuildings.Select(b=>new{b.Id,b.TypeId,b.IndustryProgress,b.IsComplete,b.IsEnabled,b.Condition,b.StoredPowerDays}).ToArray()}).ToArray(),Campaign=JsonSerializer.SerializeToNode(codec.Capture(c),options),Revisions=c.Civilizations.Values.Select(s=>new{s.CivilizationId,s.Revision,s.MaterializedViewRevision,Expertise=s.Expertise.Revision}).ToArray()};var rows=new List<object>();
AdaptiveResearchCampaignState Case(string name,GalaxyState w,AdaptiveResearchCampaignState c,double days,double now,bool replayable=true){if(replayable)c=codec.Restore(w,codec.Capture(c));var input=new{Days=Number(days),Now=Number(now)};var before=Fingerprint();var beforeState=Projection(w,c);IReadOnlyList<AdaptiveResearchCampaignEvent>?events=null;Exception?error=null;try{events=simulation.Advance(w,c,days,now);}catch(Exception e){error=e;}var after=Fingerprint();rows.Add(new{Name=name,Kind="advance",SetupKind=replayable?"Recovered":"Fresh",Input=input,BeforeFingerprint=before,AfterFingerprint=after,Error=Error(error),Events=events,BeforeState=beforeState,State=Projection(w,c)});return c;}
(GalaxyState World,AdaptiveResearchCampaignState Campaign,string Node,int Labs) Active(){var world=World(Civ(1));var campaign=factory.Create(world);var state=campaign.GetCivilization(1);var visible=runtime.Authority.BuildView(state).VisibleNodes.First(n=>n.State==ResearchMaturity.Investigable&&n.Blockers.Count==0&&n.MinimumLabs is not null);var result=AdaptiveResearchCampaignCommands.StartDirectedResearch(world,campaign,1,visible.NodeId,visible.MinimumLabs!.Value,"species:terran_baseline");if(!result.Accepted)throw new InvalidOperationException(result.Message);return(world,campaign,visible.NodeId,visible.MinimumLabs.Value);}
var w0=World(Civ(1));var c0=factory.Create(w0);Case("zero",w0,c0,0,0,false);foreach(var (n,d,t) in new[]{("negative-days",-1d,0d),("nan-days",double.NaN,0d),("positive-infinity-days",double.PositiveInfinity,0d),("negative-now",1d,-1d),("nan-now",1d,double.NaN),("positive-infinity-now",1d,double.PositiveInfinity)}){var w=World(Civ(1));Case(n,w,factory.Create(w),d,t);}var wn=World(Civ(1));wn.ConstructionStates[0].CompletedProjectIds.Add("research_network");var cn=factory.Create(wn);cn=Case("network-add",wn,cn,1,1);wn.ConstructionStates[0].CompletedProjectIds.Clear();cn=Case("network-remove",wn,cn,1,2);var ww=World(Civ(1));ww.ConstructionStates[0].CompletedProjectIds.Add("warp_test_facility");var cw=factory.Create(ww);cw=Case("warp-add",ww,cw,1,1);ww.ConstructionStates[0].CompletedProjectIds.Clear();cw=Case("warp-retained",ww,cw,1,2);var wa=World(Civ(9,true));var empty=factory.Create(World());Case("ancient-skip-missing-campaign",wa,empty,1,1,false);
var ws=World(Civ(1));ws.Colonies.Add(new ColonyState{Id=7,CivilizationId=1,SystemId=0,Name="Lab",PopulationMillions=1000,SurfaceBuildings={new SurfaceBuildingState{Id=1,TypeId="power_generator",IsComplete=true,IndustryProgress=300},new SurfaceBuildingState{Id=2,TypeId="science_lab",IsComplete=true,IndustryProgress=400}}});var cs=factory.Create(ws);cs=Case("surface-lab-add",ws,cs,1,1);ws.Colonies[0].SurfaceBuildings[1].IsEnabled=false;cs=Case("surface-lab-remove",ws,cs,1,2);
var wf=World(Civ(1));var cf=factory.Create(wf);var sf=cf.GetCivilization(1);var candidate=runtime.Authority.BuildView(sf).VisibleNodes.First(n=>n.State==ResearchMaturity.Investigable&&n.Blockers.Count==0&&n.MinimumLabs is not null);var started=AdaptiveResearchCampaignCommands.StartDirectedResearch(wf,cf,1,candidate.NodeId,candidate.MinimumLabs!.Value,"species:terran_baseline");if(!started.Accepted)throw new InvalidOperationException(started.Message);wf.Economies[0].Credits=0;cf=Case("funding-shortfall",wf,cf,1,10);wf.Economies[0].Credits=1000;cf=Case("funding-restored",wf,cf,1,11);cf=Case("long-advance-milestones",wf,cf,365.25*8,365.25*8);
var wai=World(Civ(4,player:false));var cai=factory.Create(wai);Case("ai-first-candidate",wai,cai,1,1);
var wd=World(Civ(1));for(var i=0;i<40;i++)wd.Colonies.Add(new ColonyState{Id=7,CivilizationId=1,SystemId=0,Name=$"Duplicate {i}",PopulationMillions=1000,SurfaceBuildings={new SurfaceBuildingState{Id=1,TypeId="power_generator",IsComplete=true,IndustryProgress=300},new SurfaceBuildingState{Id=2,TypeId=i==39?"advanced_science_lab":"science_lab",IsComplete=true,IndustryProgress=i==39?600:400}}});Case("surface-duplicate-replacement-stable-40",wd,factory.Create(wd),1,1);
var an=Active();an.World.Economies[0].Credits=double.NaN;Case("nonfinite-economy-nan",an.World,an.Campaign,1,1);
var ao=Active();ao.World.Economies[0].Credits=double.MaxValue;Case("requested-credits-overflow",ao.World,ao.Campaign,double.MaxValue,1);
foreach(var (name,fraction) in new[]{("percent-bankers-12",0.125d),("percent-bankers-38",0.375d)}){var ap=Active();var perDay=AdaptiveResearchFundingPolicy.Quote(runtime.Authority.Catalog.GetNode(ap.Node),ap.Labs,runtime.Authority.Catalog).OperatingCreditsPerDay;ap.World.Economies[0].Credits=perDay*fraction;Case(name,ap.World,ap.Campaign,1,1);}
var we=World();Case("empty-world-positive",we,factory.Create(we),1,1);
var wmc=World(Civ(1));wmc.ConstructionStates.Clear();Case("missing-construction",wmc,factory.Create(wmc),1,1);
var wme=WorldWithoutEconomy(Civ(1,stage:CivilizationDevelopmentStage.PreWarp));Case("missing-economy-after-facilities-pressure",wme,factory.Create(wme),1,1);
var wo=World(Civ(2,stage:CivilizationDevelopmentStage.PreWarp),Civ(1,stage:CivilizationDevelopmentStage.PreWarp),Civ(9,true));Case("numeric-civilization-order",wo,factory.Create(wo),1,1);
var wnn=World(Civ(1));wnn.ConstructionStates[0].CompletedProjectIds.Add("research_network");var cnn=factory.Create(wnn);cnn=Case("network-add-for-noop",wnn,cnn,1,1);cnn=Case("network-exact-noop",wnn,cnn,1,2);
var wx=World(Civ(1));wx.Colonies.Add(new ColonyState{Id=8,CivilizationId=1,SystemId=0,Name="Advanced",PopulationMillions=1000,SurfaceBuildings={new SurfaceBuildingState{Id=1,TypeId="power_generator",IsComplete=true,IndustryProgress=300},new SurfaceBuildingState{Id=2,TypeId="advanced_science_lab",IsComplete=true,IndustryProgress=400}}});Case("surface-advanced-base",wx,factory.Create(wx),1,1);
var wdist=World(Civ(1));wdist.Colonies.Add(new ColonyState{Id=9,CivilizationId=1,SystemId=0,Name="District",PopulationMillions=1000,SurfaceBuildings={new SurfaceBuildingState{Id=1,TypeId="power_generator",IsComplete=true,IndustryProgress=300},new SurfaceBuildingState{Id=2,TypeId="power_generator",IsComplete=true,IndustryProgress=300},new SurfaceBuildingState{Id=3,TypeId="science_lab",IsComplete=true,IndustryProgress=400},new SurfaceBuildingState{Id=4,TypeId="science_lab",IsComplete=true,IndustryProgress=400},new SurfaceBuildingState{Id=5,TypeId="advanced_science_lab",IsComplete=true,IndustryProgress=400}}});Case("surface-district-archetypes",wdist,factory.Create(wdist),1,1);
var doc=new{Authority="AdaptiveResearchCampaignSimulation.cs",Culture="InvariantCulture",CanonicalFingerprint=beforeLoad,Rows=rows};Directory.CreateDirectory(Path.GetDirectoryName(output)!);File.WriteAllText(output,JsonSerializer.Serialize(doc,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine($"campaign simulation oracle: {rows.Count} rows -> {output}");return 0;}catch(Exception e){Console.Error.WriteLine(e);Console.Error.WriteLine($"CurrentDirectory: {Environment.CurrentDirectory}");Console.Error.WriteLine($"ResearchRoot: {dr}");Console.Error.WriteLine($"FixturePath: {df}");return 1;}
